"""Render unchanged SS=1 ODF values in the phi1=0..90 degree window.

Input grids are generated by tools/mtex/export_odf_phi1_0_90.m.
No quadrant folding, symmetrization, or window renormalization is applied.
"""
from pathlib import Path
import json
import hashlib
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, Normalize

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results/mtex_odf_phi1_0_90"
reference = pd.read_csv(ROOT / "results/mtex_odf_selected_phi2/odf_selected_phi2_summary.csv")
summary = pd.read_csv(OUT / "odf_full_space_summary.csv")
assert reference["sample"].equals(summary["sample"])
assert np.allclose(reference.odf_maximum_mrd, summary.odf_maximum_mrd, atol=0.03, rtol=0)
assert np.array_equal(reference.valid_ti_hex_orientation_count, summary.valid_ti_hex_orientation_count)
cmax = float(reference.global_color_limit_max_mrd.iloc[0])
cmap = ListedColormap(np.loadtxt(OUT / "parula.csv", delimiter=","))
plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 12, "axes.linewidth": 0.7})
fig, axs = plt.subplots(6, 3, figsize=(8.6, 14.4))
fig.subplots_adjust(left=0.25, right=0.89, bottom=0.05, top=0.95, wspace=0.25, hspace=0.48)
x = np.arange(0, 91, 5)
hashes = {}
for i, row in summary.iterrows():
    for j, phi2 in enumerate((0, 30, 60)):
        path = OUT / f"density_{row['sample']}_phi2_{phi2:02d}.csv"
        hashes[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
        grid = np.loadtxt(path, delimiter=",")
        assert grid.shape == (91, 91) and np.isfinite(grid).all()
        ax = axs[i, j]
        z = np.maximum(grid[::5, ::5], 0)  # Same display-only clipping as source figure.
        levels = np.linspace(0, cmax, 16)
        ax.contourf(x, x, z, levels=levels, cmap=cmap, vmin=0, vmax=cmax)
        ax.contour(x, x, z, levels=levels[1:-1], colors="#263958", linewidths=0.3)
        ax.set(xlim=(0, 90), ylim=(90, 0), xticks=(0, 30, 60, 90), yticks=(0, 30, 60, 90))
        ax.set_aspect("equal", adjustable="box")
        ax.set_box_aspect(1)
        ax.tick_params(length=3, pad=2)
        ax.set_xlabel(r"$\varphi_1$ (°)", labelpad=1)
        if j == 0:
            ax.set_ylabel(r"$\Phi$ (°)", labelpad=3)
        if i == 0:
            ax.set_title(rf"$\varphi_2 = {phi2}^\circ$", pad=9, fontsize=12)
    pos = axs[i, 0].get_position()
    fig.text(0.165, (pos.y0 + pos.y1)/2,
             f"{row.diameter_mm:.2f} mm\n{row.cold_reduction_percent:.2f}% reduction\n"
             f"Max ODF = {reference.odf_maximum_mrd.iloc[i]:.2f} MRD",
             ha="right", va="center", fontsize=11, linespacing=1.5)
fig.suptitle("Selected ODF sections (SS = 1)", fontsize=14, y=0.987)
cax = fig.add_axes([0.925, 0.05, 0.016, 0.9])
cb = fig.colorbar(plt.cm.ScalarMappable(norm=Normalize(0, cmax), cmap=cmap), cax=cax)
cb.set_label("ODF intensity (MRD)", labelpad=9)
cb.set_ticks(np.arange(0, 11, 2))
fig.canvas.draw()
panel_pixel_sizes = [list(ax.get_window_extent().size) for ax in axs.flat]
assert all(abs(w-h) < 1e-6 for w,h in panel_pixel_sizes), "ODF panels must be square"
fig.savefig(OUT / "odf_selected_phi2_phi1_0_90.png", dpi=400, facecolor="white", bbox_inches="tight", pad_inches=0.12)
fig.savefig(OUT / "odf_selected_phi2_phi1_0_90.pdf", facecolor="white", bbox_inches="tight", pad_inches=0.12)
plt.close(fig)
(OUT / "plot_provenance.json").write_text(json.dumps({
    "phi1_display_deg": [0, 90], "Phi_display_deg": [0, 90],
    "phi2_sections_deg": [0, 30, 60], "specimen_symmetry": "1",
    "display_grid_deg": 5, "density_csv_grid_deg": 1,
    "mrd_color_limits": [0, cmax], "window_renormalized": False,
    "panel_box_aspect": 1, "data_aspect": 1,
    "panel_pixel_sizes_at_canvas_dpi": panel_pixel_sizes,
    "max_odf_labels": "Full orientation space, retained from original figure",
    "display_negative_density": "clipped at zero, same as original figure",
    "density_sha256": hashes,
}, indent=2)+"\n")
print("ODF_PHI1_0_90_PLOT_OK")
