function audit = audit_native_grid_pairs(endpointEbsdId, mappedEbsdId, ...
  mappedXY, xStepUm, yStepUm, context)
%AUDIT_NATIVE_GRID_PAIRS Map persistent IDs and require native face neighbors.
arguments
  endpointEbsdId (:,2) double
  mappedEbsdId (:,1) double
  mappedXY (:,2) double
  xStepUm (1,1) double {mustBeFinite,mustBePositive}
  yStepUm (1,1) double {mustBeFinite,mustBePositive}
  context (1,1) string = "boundary endpoint pairs"
end

assert(numel(mappedEbsdId) == size(mappedXY, 1), ...
  "Mapped EBSD IDs and coordinates must have equal length.");
assert(all(isfinite(mappedEbsdId)) && ...
  all(mappedEbsdId > 0 & mappedEbsdId == fix(mappedEbsdId)) && ...
  numel(unique(mappedEbsdId)) == numel(mappedEbsdId), ...
  "Mapped EBSD IDs must be unique positive finite integers.");
assert(all(isfinite(mappedXY), "all"), ...
  "Mapped EBSD coordinates must be finite.");
xValues = unique(mappedXY(:,1));
yValues = unique(mappedXY(:,2));
gridTolerance = 1e-8;
completeCartesianGrid = numel(xValues) > 1 && numel(yValues) > 1 && ...
  size(unique(mappedXY, "rows"), 1) == size(mappedXY, 1) && ...
  size(mappedXY, 1) == numel(xValues) * numel(yValues) && ...
  all(abs(diff(xValues) / xStepUm - 1) <= gridTolerance) && ...
  all(abs(diff(yValues) / yStepUm - 1) <= gridTolerance);
if ~completeCartesianGrid
  error("audit_native_grid_pairs:IncompleteNativeGrid", ...
    "%s do not reference a complete regularly spaced Cartesian EBSD " + ...
    "grid; a coordinate is duplicated, missing, or off-step.", context);
end
assert(all(isfinite(endpointEbsdId), "all") && ...
  all(endpointEbsdId > 0 & endpointEbsdId == fix(endpointEbsdId), "all"), ...
  "Boundary endpoint EBSD IDs must be positive finite integers.");

[endpointMapped, endpointRow] = ismember(endpointEbsdId(:), mappedEbsdId);
if any(~endpointMapped)
  error("audit_native_grid_pairs:UnmappedEndpoint", ...
    "%s contain %d endpoint ID(s) absent from the full EBSD object.", ...
    context, nnz(~endpointMapped));
end
endpointRow = reshape(endpointRow, size(endpointEbsdId));
endpoint1XY = mappedXY(endpointRow(:,1), :);
endpoint2XY = mappedXY(endpointRow(:,2), :);

deltaXSteps = abs(endpoint1XY(:,1) - endpoint2XY(:,1)) / xStepUm;
deltaYSteps = abs(endpoint1XY(:,2) - endpoint2XY(:,2)) / yStepUm;
xAligned = abs(deltaXSteps) <= gridTolerance | ...
  abs(deltaXSteps - 1) <= gridTolerance;
yAligned = abs(deltaYSteps) <= gridTolerance | ...
  abs(deltaYSteps - 1) <= gridTolerance;
nativeAdjacent = xAligned & yAligned & ...
  abs(deltaXSteps + deltaYSteps - 1) <= gridTolerance;
distanceUm = hypot(endpoint1XY(:,1) - endpoint2XY(:,1), ...
  endpoint1XY(:,2) - endpoint2XY(:,2));

audit.endpoint_pair_count = size(endpoint1XY, 1);
audit.nonlocal_endpoint_pair_count = nnz(~nativeAdjacent);
if isempty(distanceUm)
  audit.max_endpoint_distance_um = 0;
else
  audit.max_endpoint_distance_um = max(distanceUm);
end

if audit.nonlocal_endpoint_pair_count > 0
  error("audit_native_grid_pairs:NonlocalEndpoint", ...
    "%s contain %d nonlocal pair(s); maximum endpoint distance is %.12g um.", ...
    context, audit.nonlocal_endpoint_pair_count, ...
    audit.max_endpoint_distance_um);
end
end
