function metadata = build_c_axis_figure_metadata( ...
  sharedMaximum,yLimits,rawPlot,denoisedPlot)
output_name = ["c_axis_pole_figures_raw.png"; ...
  "c_axis_pole_figures_denoised.png"; ...
  "c_axis_mean_orientation_raw.png"; ...
  "c_axis_mean_orientation_denoised.png"];
variant = ["raw";"denoised";"raw";"denoised"];
figure_kind = ["pole_montage";"pole_montage"; ...
  "mean_orientation";"mean_orientation"];
pole_color_max_mrd = [sharedMaximum;sharedMaximum;NaN;NaN];
y_min_deg = [NaN;NaN;yLimits(1);yLimits(1)];
y_max_deg = [NaN;NaN;yLimits(2);yLimits(2)];
plotted_x = {[];[];rawPlot.x;denoisedPlot.x};
plotted_mean_deg = {[];[];rawPlot.mean_deg;denoisedPlot.mean_deg};
plotted_p10_deg = {[];[];rawPlot.p10_deg;denoisedPlot.p10_deg};
plotted_p90_deg = {[];[];rawPlot.p90_deg;denoisedPlot.p90_deg};
metadata = table(output_name,variant,figure_kind, ...
  pole_color_max_mrd,y_min_deg,y_max_deg,plotted_x, ...
  plotted_mean_deg,plotted_p10_deg,plotted_p90_deg);
end
