function contract = comprehensive_ebsd_output_contract
%COMPREHENSIVE_EBSD_OUTPUT_CONTRACT Return the registered output schema.

contract = struct();

contract.directories = [
  "00_audit"
  "01_standard_maps"
  "02_grain_morphology"
  "03_boundaries"
  "04_intragranular"
  "05_texture"
  "06_axial_propensity"
  "07_raw_denoised_comparison"
  "08_tensile_integration"
];

contract.artifacts = struct();
contract.artifacts.root = ["README.md"; "analysis_manifest.csv"];
contract.artifacts.dir_00_audit = [
  "scan_inventory.csv"
  "raw_denoised_pair_audit.csv"
  "raw_denoised_change_maps.png"
];
contract.artifacts.dir_01_standard_maps = "sample_variant_maps.png";
contract.artifacts.dir_02_grain_morphology = [
  "grain_morphology_by_grain.csv"
  "grain_morphology_summary.csv"
  "grain_morphology_trends.png"
];
contract.artifacts.dir_03_boundaries = [
  "boundary_segments.csv"
  "boundary_summary.csv"
  "boundary_angle_distributions.csv"
  "boundary_trends.png"
];
contract.artifacts.dir_04_intragranular = [
  "intragranular_by_pixel.csv"
  "intragranular_by_grain.csv"
  "intragranular_summary.csv"
  "intragranular_trends.png"
];
contract.artifacts.dir_05_texture = [
  "texture_summary.csv"
  "c_axis_orientation_distribution.csv"
  "pole_figures.png"
  "inverse_pole_figures.png"
  "odf_sections.png"
  "texture_trends.png"
  "texture_numerical_diagnostics.csv"
  "raw_denoised_odf_distance.csv"
  "task4_analysis_parameters.csv"
  "texture_plot_color_limits.csv"
  "c_axis_ad_distribution_function.csv"
  "c_axis_spherical_distribution_function.csv"
  "c_axis_distribution_parameters.csv"
  "c_axis_ad_distribution_raw.png"
  "c_axis_ad_distribution_denoised.png"
  "c_axis_spherical_distribution_raw.png"
  "c_axis_spherical_distribution_denoised.png"
];
contract.artifacts.dir_06_axial_propensity = [
  "axial_propensity_by_grain.csv"
  "axial_propensity_summary.csv"
  "axial_propensity_trends.png"
];
contract.artifacts.dir_07_raw_denoised_comparison = [
  "raw_denoised_metric_comparison.csv"
  "raw_denoised_rank_agreement.csv"
  "raw_denoised_metric_comparison.png"
];
contract.artifacts.dir_08_tensile_integration = [
  "ebsd_tensile_merged.csv"
  "ebsd_tensile_rank_correlations.csv"
  "tensile_condition_aggregates.csv"
  "ebsd_tensile_comparison.png"
];

common = ["sample", "diameter_mm", "cold_reduction_percent", "variant"];
contract.summaryColumns = struct();
contract.summaryColumns.scan_inventory = [common, ...
  "folder", "input_file", "sha256", "x_cells", "y_cells", ...
  "x_step_um", "y_step_um", "total_pixels", "indexed_pixels", ...
  "indexed_fraction", "ti_hex_pixels", "ti_cubic_pixels", ...
  "unindexed_pixels", "has_bands", "has_error", "has_mad", ...
  "has_bc", "has_bs"];
contract.summaryColumns.raw_denoised_pair_audit = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "total_pixels", ...
  "coordinate_mismatch_count", "phase_changed_pixels", ...
  "indexing_changed_pixels", "orientation_changed_pixels", ...
  "orientation_change_mean_deg", "orientation_change_p95_deg", ...
  "mad_changed_pixels", "bc_changed_pixels", "bs_changed_pixels", ...
  "bands_changed_pixels", "error_changed_pixels"];
contract.summaryColumns.grain_morphology_summary = [common, ...
  "grain_detection_deg", "min_grain_pixels", "grain_count", ...
  "total_area_um2", "ecd_number_median_um", ...
  "ecd_area_weighted_median_um", "aspect_ratio_number_median", ...
  "aspect_ratio_area_weighted_median", ...
  "max_feret_number_median_um", "min_feret_number_median_um", ...
  "shape_factor_number_median", ...
  "long_axis_ad_angle_area_weighted_median_deg", ...
  "boundary_touching_grain_fraction"];
contract.summaryColumns.boundary_summary = [common, ...
  "grain_detection_deg", "classification_deg", ...
  "total_boundary_length_um", "boundary_line_density_per_um", ...
  "lagb_2_5_length_um", "lagb_5_15_length_um", ...
  "hagb_ge15_length_um", "lagb_2_15_length_fraction", ...
  "hagb_ge15_length_fraction", "lagb_2_15_count_fraction", ...
  "hagb_ge15_count_fraction", "twin_candidate_length_fraction"];
contract.summaryColumns.intragranular_summary = [common, ...
  "grain_detection_deg", "min_grain_pixels", "kam_order", ...
  "kam_threshold_deg", "valid_pixel_count", "kam_mean_deg", ...
  "kam_median_deg", "kam_p90_deg", "grod_mean_deg", ...
  "grod_median_deg", "grod_p90_deg", "gos_number_mean_deg", ...
  "gos_area_weighted_mean_deg"];
contract.summaryColumns.texture_summary = [common, "weighting", ...
  "texture_kernel_halfwidth_deg", "texture_grid_resolution_deg", ...
  "max_mrd", "texture_index", "m_index", "clipped_grid_entropy", ...
  "c_axis_ad_mean_deg", "c_axis_ad_median_deg", ...
  "c_axis_ad_p10_deg", "c_axis_ad_p90_deg", ...
  "c_axis_within_15deg_fraction", "c_axis_within_30deg_fraction", ...
  "c_axis_azimuth_resultant"];
contract.summaryColumns.c_axis_orientation_distribution = [common, ...
  "weighting", "source_id", ...
  "source_weight", "normalized_weight", "c_axis_x_ad", ...
  "c_axis_y_td_rd", "c_axis_z_nd", "c_axis_ad_acute_deg", ...
  "c_axis_azimuth_about_ad_deg"];
contract.summaryColumns.texture_numerical_diagnostics = [common, ...
  "weighting", "texture_kernel_halfwidth_deg", ...
  "texture_grid_resolution_deg", "harmonic_bandwidth", ...
  "total_ti_hex_grain_count", "retained_ti_hex_grain_count", ...
  "excluded_small_grain_count", ...
  "excluded_small_grain_area_fraction", "grid_point_count", ...
  "density_normalization_factor", "minimum_raw_odf", ...
  "negative_grid_fraction", "clipped_negative_l1_fraction", ...
  "clipped_normalization_mean"];
contract.summaryColumns.raw_denoised_odf_distance = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "weighting", ...
  "kernel_halfwidth_deg", "harmonic_bandwidth", ...
  "odf_harmonic_l2_distance"];
contract.summaryColumns.task4_analysis_parameters = [common, ...
  "grain_detection_deg", "min_grain_pixels", "kam_orders", ...
  "kam_thresholds_deg", "grod_axis_cutoff_deg", ...
  "grod_axis_aggregation", ...
  "texture_kernel_family", "texture_kernel_halfwidth_deg", ...
  "harmonic_bandwidth", "texture_evaluation_grid_resolution_deg", ...
  "coordinate_x", "coordinate_y", "coordinate_z", ...
  "primary_variant", "comparison_variant", ...
  "c_axis_hemisphere_convention", ...
  "c_axis_component_zero_tolerance", ...
  "clipped_grid_entropy_definition", ...
  "odf_harmonic_l2_distance_definition"];
contract.summaryColumns.texture_plot_color_limits = [ ...
  "plot_kind", "weighting", "scan_count", "grid_resolution_deg", ...
  "color_limit_min_mrd", "color_limit_max_mrd"];
contract.summaryColumns.c_axis_ad_distribution_function = [common, ...
  "support", "weighting", "bin_width_deg", "bin_lower_deg", ...
  "bin_upper_deg", "bin_center_deg", "valid_source_count", ...
  "valid_source_weight", "observed_probability", "pdf_per_degree", ...
  "random_probability", "mrd"];
contract.summaryColumns.c_axis_spherical_distribution_function = [common, ...
  "support", "weighting", "kernel_halfwidth_deg", "n_mu", "n_phi", ...
  "grid_index", "theta_ad_deg", "phi_about_ad_deg", "cell_weight", ...
  "mrd"];
contract.summaryColumns.c_axis_distribution_parameters = [ ...
  "scope", "sample", "variant", "support", "weighting", ...
  "parameter", "value", "unit", "role", "definition"];
contract.summaryColumns.axial_propensity_summary = [common, "family", ...
  "assumption", "grain_count", "area_weighted_mean_max_schmid", ...
  "area_weighted_median_max_schmid", ...
  "area_fraction_schmid_ge_0_4", ...
  "taylor_factor_area_weighted_mean"];
contract.summaryColumns.raw_denoised_metric_comparison = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "module", ...
  "metric", "raw_value", "denoised_value", "absolute_difference", ...
  "relative_difference_percent", "trend_direction_defined", ...
  "trend_direction_agrees", ...
  "interpretation_change_flag"];
contract.summaryColumns.raw_denoised_rank_agreement = [ ...
  "module", "metric", "n_states", "spearman_rank_agreement", ...
  "adjacent_direction_agreement_fraction", ...
  "interpretation_change_flag"];
contract.summaryColumns.tensile_condition_aggregates = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", ...
  "tensile_metric", "tensile_mean", "tensile_sd", ...
  "tensile_n_valid"];
contract.summaryColumns.ebsd_tensile_merged = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "ebsd_metric", ...
  "ebsd_value", "tensile_sample", "tensile_repeat", ...
  "tensile_metric", "tensile_value", "yield_status", ...
  "included_in_aggregate", "tensile_mean", "tensile_sd", ...
  "tensile_n_valid", "reliability_rule"];
contract.summaryColumns.ebsd_tensile_rank_correlations = [ ...
  "ebsd_metric", "tensile_metric", "n_states", "spearman_rho", ...
  "leave_one_out_rho_min", "leave_one_out_rho_max", ...
  "tensile_n_valid_min", "tensile_n_valid_max", "interpretation"];

contract.parameters = struct();
contract.parameters.coordinate_x = "AD";
contract.parameters.coordinate_y = "TD_RD";
contract.parameters.coordinate_z = "ND";
contract.parameters.grid_x_cells = 600;
contract.parameters.grid_y_cells = 600;
contract.parameters.x_step_um = 0.5;
contract.parameters.y_step_um = 0.5;
contract.parameters.orientation_change_tolerance_deg = 1e-4;
contract.parameters.primary_grain_detection_deg = 2;
contract.parameters.boundary_classification_deg = 15;
contract.parameters.min_grain_pixels = 5;
contract.parameters.detection_sensitivity_deg = [0.5 1 2 5];
contract.parameters.kam_orders = [1 2];
contract.parameters.kam_thresholds_deg = [2 5];
contract.parameters.texture_kernel_halfwidth_deg = 5;
contract.parameters.texture_grid_resolution_deg = 5;
contract.parameters.texture_kernel_family = "SO3DeLaValleePoussinKernel";
contract.parameters.min_boundary_axis_deg = 5;
contract.parameters.grod_axis_aggregation = ...
  "antipodal_second_moment_tensor";
contract.parameters.c_axis_component_zero_tolerance = 1e-12;
contract.parameters.c_axis_hemisphere_convention = ...
  "AD_positive_then_TD_RD_positive_then_ND_positive";
contract.parameters.texture_entropy_metric = "clipped_grid_entropy";
contract.parameters.clipped_grid_entropy_definition = ...
  "clip_negative_ODF_to_zero_mean_normalize_then_negative_mean_f_ln_f";
contract.parameters.raw_denoised_odf_distance_metric = ...
  "L2_norm_of_raw_minus_denoised_unit_mean_harmonic_ODFs";
contract.parameters.c_axis_ad_bin_widths_deg = [1 2 5];
contract.parameters.c_axis_ad_primary_bin_width_deg = 2;
contract.parameters.c_axis_spherical_halfwidths_deg = [5 7.5 10];
contract.parameters.c_axis_spherical_primary_halfwidth_deg = 5;
contract.parameters.c_axis_spherical_n_mu = 36;
contract.parameters.c_axis_spherical_n_phi = 144;
contract.parameters.c_axis_spherical_audit_n_mu = 72;
contract.parameters.c_axis_spherical_audit_n_phi = 288;
contract.parameters.c_axis_spherical_peak_tolerance_deg = 3;
contract.parameters.c_axis_spherical_peak_tie_exclusion_deg = 10;
contract.parameters.c_axis_distribution_primary_weighting = ...
  "pixel_weighted";
contract.parameters.c_axis_distribution_primary_support = "raw_full";
contract.parameters.c_axis_distribution_common_supports = ...
  ["raw_common","denoised_raw_common"];
contract.parameters.c_axis_distribution_color_percentile = 99.9;
contract.parameters.twin_candidate_tolerance_deg = 5;
contract.parameters.primary_variant = "raw";
contract.parameters.comparison_variant = "denoised";
end
