function contract = comprehensive_ebsd_output_contract
%COMPREHENSIVE_EBSD_OUTPUT_CONTRACT Return the registered output schema.

contract = struct();

contract.directories = [
  "00_audit"
  "01_standard_maps"
  "02_grain_morphology"
  "03_boundaries"
  "04_intragranular"
  "05_texture"
  "06_axial_propensity"
  "07_raw_denoised_comparison"
  "08_tensile_integration"
];

contract.artifacts = struct();
contract.artifacts.root = ["README.md"; "analysis_manifest.csv"];
contract.artifacts.dir_00_audit = [
  "scan_inventory.csv"
  "raw_denoised_pair_audit.csv"
  "raw_denoised_change_maps.png"
];
contract.artifacts.dir_01_standard_maps = "sample_variant_maps.png";
contract.artifacts.dir_02_grain_morphology = [
  "grain_morphology_by_grain.csv"
  "grain_morphology_summary.csv"
  "grain_morphology_trends.png"
];
contract.artifacts.dir_03_boundaries = [
  "boundary_segments.csv"
  "boundary_summary.csv"
  "boundary_angle_distributions.csv"
  "boundary_trends.png"
];
contract.artifacts.dir_04_intragranular = [
  "intragranular_by_pixel.csv"
  "intragranular_by_grain.csv"
  "intragranular_summary.csv"
  "intragranular_trends.png"
];
contract.artifacts.dir_05_texture = [
  "texture_summary.csv"
  "c_axis_orientation_distribution.csv"
  "pole_figures.png"
  "inverse_pole_figures.png"
  "odf_sections.png"
  "texture_trends.png"
];
contract.artifacts.dir_06_axial_propensity = [
  "axial_propensity_by_grain.csv"
  "axial_propensity_summary.csv"
  "axial_propensity_trends.png"
];
contract.artifacts.dir_07_raw_denoised_comparison = [
  "raw_denoised_metric_comparison.csv"
  "raw_denoised_metric_comparison.png"
];
contract.artifacts.dir_08_tensile_integration = [
  "ebsd_tensile_merged.csv"
  "ebsd_tensile_rank_correlations.csv"
  "ebsd_tensile_comparison.png"
];

common = ["sample", "diameter_mm", "cold_reduction_percent", "variant"];
contract.summaryColumns = struct();
contract.summaryColumns.scan_inventory = [common, ...
  "folder", "input_file", "sha256", "x_cells", "y_cells", ...
  "x_step_um", "y_step_um", "total_pixels", "indexed_pixels", ...
  "indexed_fraction", "ti_hex_pixels", "ti_cubic_pixels", ...
  "unindexed_pixels", "has_bands", "has_error", "has_mad", ...
  "has_bc", "has_bs"];
contract.summaryColumns.raw_denoised_pair_audit = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "total_pixels", ...
  "coordinate_mismatch_count", "phase_changed_pixels", ...
  "indexing_changed_pixels", "orientation_changed_pixels", ...
  "orientation_change_mean_deg", "orientation_change_p95_deg", ...
  "mad_changed_pixels", "bc_changed_pixels", "bs_changed_pixels", ...
  "bands_changed_pixels", "error_changed_pixels"];
contract.summaryColumns.grain_morphology_summary = [common, ...
  "grain_detection_deg", "min_grain_pixels", "grain_count", ...
  "total_area_um2", "ecd_number_median_um", ...
  "ecd_area_weighted_median_um", "aspect_ratio_number_median", ...
  "aspect_ratio_area_weighted_median", ...
  "max_feret_number_median_um", "min_feret_number_median_um", ...
  "shape_factor_number_median", ...
  "long_axis_ad_angle_area_weighted_median_deg", ...
  "boundary_touching_grain_fraction"];
contract.summaryColumns.boundary_summary = [common, ...
  "grain_detection_deg", "classification_deg", ...
  "total_boundary_length_um", "boundary_line_density_per_um", ...
  "lagb_2_5_length_um", "lagb_5_15_length_um", ...
  "hagb_ge15_length_um", "lagb_2_15_length_fraction", ...
  "hagb_ge15_length_fraction", "lagb_2_15_count_fraction", ...
  "hagb_ge15_count_fraction", "twin_candidate_length_fraction"];
contract.summaryColumns.intragranular_summary = [common, ...
  "grain_detection_deg", "min_grain_pixels", "kam_order", ...
  "kam_threshold_deg", "valid_pixel_count", "kam_mean_deg", ...
  "kam_median_deg", "kam_p90_deg", "grod_mean_deg", ...
  "grod_median_deg", "grod_p90_deg", "gos_number_mean_deg", ...
  "gos_area_weighted_mean_deg"];
contract.summaryColumns.texture_summary = [common, "weighting", ...
  "texture_kernel_halfwidth_deg", "texture_grid_resolution_deg", ...
  "max_mrd", "texture_index", "m_index", "entropy", ...
  "c_axis_ad_mean_deg", "c_axis_ad_median_deg", ...
  "c_axis_ad_p10_deg", "c_axis_ad_p90_deg", ...
  "c_axis_within_15deg_fraction", "c_axis_within_30deg_fraction", ...
  "c_axis_azimuth_resultant"];
contract.summaryColumns.axial_propensity_summary = [common, "family", ...
  "assumption", "grain_count", "area_weighted_mean_max_schmid", ...
  "area_weighted_median_max_schmid", ...
  "area_fraction_schmid_ge_0_4", ...
  "taylor_factor_area_weighted_mean"];
contract.summaryColumns.raw_denoised_metric_comparison = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "module", ...
  "metric", "raw_value", "denoised_value", "absolute_difference", ...
  "relative_difference_percent", "trend_direction_agrees", ...
  "interpretation_change_flag"];
contract.summaryColumns.ebsd_tensile_merged = [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "ebsd_metric", ...
  "ebsd_value", "tensile_metric", "tensile_mean", "tensile_sd", ...
  "tensile_n", "reliability_rule"];
contract.summaryColumns.ebsd_tensile_rank_correlations = [ ...
  "ebsd_metric", "tensile_metric", "n_states", "spearman_rho", ...
  "leave_one_out_rho_min", "leave_one_out_rho_max", "interpretation"];

contract.parameters = struct();
contract.parameters.coordinate_x = "AD";
contract.parameters.coordinate_y = "TD_RD";
contract.parameters.coordinate_z = "ND";
contract.parameters.grid_x_cells = 600;
contract.parameters.grid_y_cells = 600;
contract.parameters.x_step_um = 0.5;
contract.parameters.y_step_um = 0.5;
contract.parameters.orientation_change_tolerance_deg = 1e-4;
contract.parameters.primary_grain_detection_deg = 2;
contract.parameters.boundary_classification_deg = 15;
contract.parameters.min_grain_pixels = 5;
contract.parameters.detection_sensitivity_deg = [0.5 1 2 5];
contract.parameters.kam_orders = [1 2];
contract.parameters.kam_thresholds_deg = [2 5];
contract.parameters.texture_kernel_halfwidth_deg = 5;
contract.parameters.texture_grid_resolution_deg = 5;
contract.parameters.min_boundary_axis_deg = 5;
contract.parameters.twin_candidate_tolerance_deg = 5;
contract.parameters.primary_variant = "raw";
contract.parameters.comparison_variant = "denoised";
end
