function [pairRow, pixelTable] = compare_raw_denoised_ebsd( ...
  rawEbsd, denoisedEbsd, sampleMeta)
%COMPARE_RAW_DENOISED_EBSD Audit pointwise changes on the native grid.

arguments
  rawEbsd EBSD
  denoisedEbsd EBSD
  sampleMeta
end

assert(istable(sampleMeta) && height(sampleMeta) == 1, ...
  "sampleMeta must be a one-row catalog table.");
assert(length(rawEbsd) == length(denoisedEbsd), ...
  "Raw and denoised scans must conserve pixel count.");
rawXY = [double(rawEbsd.x(:)), double(rawEbsd.y(:))];
denoisedXY = [double(denoisedEbsd.x(:)), double(denoisedEbsd.y(:))];
coordinateMismatch = any(rawXY ~= denoisedXY, 2);
coordinateMismatchCount = nnz(coordinateMismatch);
if coordinateMismatchCount > 0
  error("compare_raw_denoised_ebsd:CoordinateMismatch", ...
    "Raw and denoised coordinates differ at %d pixel(s).", ...
    coordinateMismatchCount);
end

rawPhase = double(rawEbsd.phaseId(:));
denoisedPhase = double(denoisedEbsd.phaseId(:));
rawIndexed = logical(rawEbsd.isIndexed(:));
denoisedIndexed = logical(denoisedEbsd.isIndexed(:));

rawHexPhaseId = find(strcmp(rawEbsd.mineralList, "Ti-Hex"), 1);
denoisedHexPhaseId = find(strcmp(denoisedEbsd.mineralList, "Ti-Hex"), 1);
assert(~isempty(rawHexPhaseId) && ~isempty(denoisedHexPhaseId), ...
  "Both scans must define the Ti-Hex phase.");
commonHex = rawIndexed & denoisedIndexed & ...
  rawPhase == rawHexPhaseId & denoisedPhase == denoisedHexPhaseId;
orientationCandidateDeg = nan(length(rawEbsd), 1);
rawOrientation = rawEbsd(commonHex).orientations;
denoisedOrientation = denoisedEbsd(commonHex).orientations;
orientationCandidateDeg(commonHex) = ...
  double(angle(rawOrientation, denoisedOrientation) / degree);

requiredProperties = ["mad","bc","bs","bands","error"];
rawFields = string(fieldnames(rawEbsd.prop));
denoisedFields = string(fieldnames(denoisedEbsd.prop));
assert(all(ismember(requiredProperties, rawFields)) && ...
  all(ismember(requiredProperties, denoisedFields)), ...
  "Raw and denoised scans must contain MAD, BC, BS, Bands, and Error.");

rawMad = double(rawEbsd.prop.mad(:));
denoisedMad = double(denoisedEbsd.prop.mad(:));
rawBc = double(rawEbsd.prop.bc(:));
denoisedBc = double(denoisedEbsd.prop.bc(:));
rawBs = double(rawEbsd.prop.bs(:));
denoisedBs = double(denoisedEbsd.prop.bs(:));
rawBands = double(rawEbsd.prop.bands(:));
denoisedBands = double(denoisedEbsd.prop.bands(:));
rawError = double(rawEbsd.prop.error(:));
denoisedError = double(denoisedEbsd.prop.error(:));
rawQuality = struct("mad", rawMad, "bc", rawBc, "bs", rawBs, ...
  "bands", rawBands, "error", rawError);
denoisedQuality = struct("mad", denoisedMad, "bc", denoisedBc, ...
  "bs", denoisedBs, "bands", denoisedBands, "error", denoisedError);
changes = compare_raw_denoised_ebsd_arrays(rawPhase, denoisedPhase, ...
  rawIndexed, denoisedIndexed, rawHexPhaseId, denoisedHexPhaseId, ...
  orientationCandidateDeg, rawQuality, denoisedQuality, ...
  comprehensive_ebsd_output_contract().parameters. ...
  orientation_change_tolerance_deg);

validAngles = changes.orientation_change_deg( ...
  isfinite(changes.orientation_change_deg));
if isempty(validAngles)
  orientationMean = NaN;
  orientationP95 = NaN;
else
  orientationMean = mean(validAngles);
  orientationP95 = prctile(validAngles, 95);
end

pairRow = table(string(sampleMeta.sample), sampleMeta.diameter_mm, ...
  sampleMeta.cold_reduction_percent, length(rawEbsd), ...
  coordinateMismatchCount, nnz(changes.phase_changed), ...
  nnz(changes.indexing_changed), nnz(changes.orientation_changed), ...
  orientationMean, orientationP95, nnz(changes.mad_changed), ...
  nnz(changes.bc_changed), nnz(changes.bs_changed), ...
  nnz(changes.bands_changed), nnz(changes.error_changed), ...
  'VariableNames', cellstr( ...
  comprehensive_ebsd_output_contract().summaryColumns. ...
  raw_denoised_pair_audit));

pixelTable = table(rawXY(:,1), rawXY(:,2), rawPhase, denoisedPhase, ...
  rawIndexed, denoisedIndexed, changes.phase_changed, ...
  changes.indexing_changed, ...
  changes.orientation_change_deg, changes.orientation_changed, ...
  rawMad, denoisedMad, changes.mad_difference, rawBc, denoisedBc, ...
  changes.bc_difference, rawBs, denoisedBs, changes.bs_difference, ...
  rawBands, denoisedBands, changes.bands_difference, rawError, ...
  denoisedError, changes.error_difference, 'VariableNames', cellstr([ ...
  "x_um","y_um","raw_phase_id","denoised_phase_id", ...
  "raw_indexed","denoised_indexed","phase_changed", ...
  "indexing_changed","orientation_change_deg","orientation_changed", ...
  "raw_mad","denoised_mad","mad_difference","raw_bc", ...
  "denoised_bc","bc_difference","raw_bs","denoised_bs", ...
  "bs_difference","raw_bands","denoised_bands","bands_difference", ...
  "raw_error","denoised_error","error_difference"]));
end
