function rows = compute_morphology_sensitivity_rows( ...
  grains, meta, objectType, grainDetectionDeg, minGrainPixels)
%COMPUTE_MORPHOLOGY_SENSITIVITY_ROWS Aggregate unsmoothed shape sensitivity.

arguments
  grains grain2d
  meta table
  objectType (1,1) string
  grainDetectionDeg (1,1) double
  minGrainPixels (1,:) double
end

assert(ismember(objectType, ["orientation_domain","hagb_grain"]));
assert(isfinite(grainDetectionDeg) && grainDetectionDeg > 0);
assert(~isempty(minGrainPixels) && ...
  all(isfinite(minGrainPixels) & minGrainPixels >= 1 & ...
  minGrainPixels == fix(minGrainPixels)));
assert(numel(unique(minGrainPixels)) == numel(minGrainPixels));
assert(~isempty(grains), "No Ti-Hex objects were supplied.");

allAreaUm2 = sum(double(area(grains)));
allObjectCount = length(grains);
assert(isfinite(allAreaUm2) && allAreaUm2 > 0);

rows = table();
for minPixels = minGrainPixels
  options = struct("grain_detection_deg", grainDetectionDeg, ...
    "min_grain_pixels", minPixels);
  [~, morphologySummary] = compute_grain_morphology_metrics( ...
    grains, meta, options);
  retainedObjectCount = morphologySummary.grain_count;
  retainedAreaUm2 = morphologySummary.total_area_um2;
  retainedAreaFraction = retainedAreaUm2 / allAreaUm2;
  assert(retainedAreaFraction > 0 && retainedAreaFraction <= 1 + 1e-12);
  retainedAreaFraction = min(1, retainedAreaFraction);

  retainedDomainCount = NaN;
  retainedGrainCount = NaN;
  if objectType == "orientation_domain"
    retainedDomainCount = retainedObjectCount;
  else
    retainedGrainCount = retainedObjectCount;
  end

  row = table(string(meta.sample), double(meta.diameter_mm), ...
    double(meta.cold_reduction_percent), string(meta.variant), ...
    objectType, grainDetectionDeg, minPixels, "AD", false, ...
    allObjectCount, retainedObjectCount, ...
    allObjectCount - retainedObjectCount, retainedDomainCount, ...
    retainedGrainCount, allAreaUm2, retainedAreaUm2, ...
    retainedAreaFraction, 1 - retainedAreaFraction, ...
    morphologySummary.ecd_number_median_um, ...
    morphologySummary.ecd_area_weighted_median_um, ...
    morphologySummary.aspect_ratio_number_median, ...
    morphologySummary.aspect_ratio_area_weighted_median, ...
    morphologySummary.long_axis_ad_angle_area_weighted_median_deg, ...
    'VariableNames', {'sample','diameter_mm', ...
    'cold_reduction_percent','variant','object_type', ...
    'grain_detection_deg','min_grain_pixels','coordinate_x', ...
    'grain_smoothing_applied','reconstructed_object_count_all', ...
    'retained_object_count','excluded_object_count', ...
    'retained_domain_count','retained_grain_count', ...
    'all_object_area_um2','retained_area_um2', ...
    'retained_area_fraction','excluded_area_fraction', ...
    'ecd_number_median_um','ecd_area_weighted_median_um', ...
    'aspect_ratio_number_median', ...
    'aspect_ratio_area_weighted_median', ...
    'long_axis_ad_angle_area_weighted_median_deg'});
  if width(rows) == 0
    rows = row;
  else
    rows = [rows; row]; %#ok<AGROW>
  end
end
end
