function outputs = generate_reference_style_fig11_schmid( ...
  scanRoot, outputRoot, samples)
%GENERATE_REFERENCE_STYLE_FIG11_SCHMID Create a Fig. 11-style SF panel.
%
% The figure creates one panel for each requested denoised EBSD state and,
% when both endpoints are present, a 7d-5d comparison under AD uniaxial
% tension. Maps include all reconstructed Ti-Hex grains; distributions use
% grains with at least five pixels. Each grain value is the maximum absolute
% Schmid factor across all symmetrised variants in the requested slip family.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
  samples (:,1) string = ["7d"; "5d"]
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

contract = comprehensive_ebsd_output_contract();
catalog = comprehensive_ebsd_catalog(scanRoot);
reconstructionOptions = struct( ...
  "detection_threshold_deg", ...
  contract.parameters.primary_grain_detection_deg, ...
  "min_grain_pixels", contract.parameters.min_grain_pixels);

allowedSamples = ["7d"; "6.48d"; "6.02d"; "5.6d"; ...
  "5.25d"; "5d"];
assert(~isempty(samples) && numel(unique(samples)) == numel(samples) && ...
  all(ismember(samples, allowedSamples)), ...
  "samples must contain unique registered diameter states.");
families = ["basal_a"; "prismatic_a"; "pyramidal_ca"];
displayNames = ["Basal <a>"; "Prismatic <a>"; ...
  "Pyramidal <c+a>"];
crssMPa = [252; 154; 756];
familyColors = [0.12 0.35 0.72; 0.91 0.61 0.04; 0.78 0.10 0.12];
binEdges = (0:0.02:0.50)';
binCenters = (binEdges(1:end-1) + binEdges(2:end)) / 2;

stateData = cell(numel(samples), 1);
summary = table();
distribution = table();

for stateIndex = 1:numel(samples)
  catalogRow = catalog(catalog.sample == samples(stateIndex) & ...
    catalog.variant == "denoised", :);
  assert(height(catalogRow) == 1, ...
    "Expected one denoised catalog row for %s.", samples(stateIndex));
  fprintf("REFERENCE_FIG11 sample=%s variant=denoised\n", ...
    samples(stateIndex));

  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalogRow);
  [grains, ebsdFull, ~] = reconstruct_comprehensive_grains( ...
    ebsdFull, reconstructionOptions);
  retained = grains("Ti-Hex");
  retained = retained(retained.numPixel >= ...
    reconstructionOptions.min_grain_pixels);
  assert(~isempty(retained), ...
    "No retained Ti-Hex grains for %s.", samples(stateIndex));

  [byGrain, metricSummary] = compute_axial_propensity_metrics( ...
    retained.meanOrientation, double(retained.id(:)), ...
    double(area(retained)), struct("include_twins", false));
  mapGrains = grains("Ti-Hex");
  [mapByGrain, ~] = compute_axial_propensity_metrics( ...
    mapGrains.meanOrientation, double(mapGrains.id(:)), ...
    double(area(mapGrains)), struct("include_twins", false));
  [xValues, yValues, nativeIndices] = native_grid_indices(ebsdFull);
  [boundaryX, boundaryY] = boundary_coordinates(grains.boundary);

  maps = cell(numel(families), 1);
  frequencies = zeros(numel(binCenters), numel(families));
  stateSummary = table();
  stateDistribution = table();
  for familyIndex = 1:numel(families)
    familyRows = byGrain.family == families(familyIndex);
    familyData = byGrain(familyRows, :);
    mapFamilyData = mapByGrain( ...
      mapByGrain.family == families(familyIndex), :);
    familyMetric = metricSummary( ...
      metricSummary.family == families(familyIndex), :);
    assert(height(familyMetric) == 1 && ~isempty(familyData));

    maps{familyIndex} = grain_values_to_native_image( ...
      ebsdFull, nativeIndices, xValues, yValues, mapFamilyData);
    binIndex = discretize(familyData.max_abs_schmid, binEdges);
    assert(all(isfinite(binIndex)), ...
      "Schmid value outside configured bins for %s %s.", ...
      samples(stateIndex), families(familyIndex));
    frequencies(:, familyIndex) = 100 * accumarray( ...
      binIndex, familyData.area_weight, ...
      [numel(binCenters), 1], @sum, 0);
    assert(abs(sum(frequencies(:, familyIndex)) - 100) < 1e-8);

    meanSchmid = familyMetric.area_weighted_mean_max_schmid;
    familySummaryRow = table( ...
      catalogRow.sample, catalogRow.diameter_mm, ...
      catalogRow.cold_reduction_percent, catalogRow.variant, ...
      families(familyIndex), displayNames(familyIndex), ...
      crssMPa(familyIndex), height(familyData), meanSchmid, ...
      familyMetric.area_weighted_median_max_schmid, ...
      100 * familyMetric.area_fraction_schmid_ge_0_4, ...
      meanSchmid / crssMPa(familyIndex), NaN, ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'family', 'display_name', ...
      'source_crss_mpa', 'grain_count', ...
      'area_weighted_mean_max_abs_schmid', ...
      'area_weighted_median_max_abs_schmid', ...
      'area_fraction_schmid_ge_0_4_percent', ...
      'mean_drive_per_mpa', 'mean_drive_relative_to_prismatic'});
    stateSummary = append_table(stateSummary, familySummaryRow);

    nBins = numel(binCenters);
    familyDistribution = table( ...
      repmat(catalogRow.sample, nBins, 1), ...
      repmat(catalogRow.diameter_mm, nBins, 1), ...
      repmat(catalogRow.cold_reduction_percent, nBins, 1), ...
      repmat(catalogRow.variant, nBins, 1), ...
      repmat(families(familyIndex), nBins, 1), ...
      repmat(displayNames(familyIndex), nBins, 1), ...
      binEdges(1:end-1), binEdges(2:end), binCenters, ...
      frequencies(:, familyIndex), ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'family', 'display_name', ...
      'bin_left', 'bin_right', 'bin_center', ...
      'area_weighted_frequency_percent'});
    stateDistribution = append_table( ...
      stateDistribution, familyDistribution);
  end

  prismDrive = stateSummary.mean_drive_per_mpa( ...
    stateSummary.family == "prismatic_a");
  stateSummary.mean_drive_relative_to_prismatic = ...
    stateSummary.mean_drive_per_mpa / prismDrive;
  summary = append_table(summary, stateSummary);
  distribution = append_table(distribution, stateDistribution);

  stateData{stateIndex} = struct( ...
    "sample", catalogRow.sample, ...
    "diameter_mm", catalogRow.diameter_mm, ...
    "cold_reduction_percent", catalogRow.cold_reduction_percent, ...
    "maps", {maps}, "frequencies", frequencies, ...
    "summary", stateSummary, "x_values", xValues, ...
    "y_values", yValues, "boundary_x", boundaryX, ...
    "boundary_y", boundaryY);

  clear ebsdFull grains retained mapGrains byGrain mapByGrain metricSummary
end

summary = sortrows(summary, {'cold_reduction_percent', 'source_crss_mpa'});
distribution = sortrows(distribution, ...
  {'cold_reduction_percent', 'family', 'bin_left'});
writetable(summary, fullfile(outputRoot, ...
  "reference_style_fig11_schmid_summary.csv"));
writetable(distribution, fullfile(outputRoot, ...
  "reference_style_fig11_schmid_distribution.csv"));
write_parameters(outputRoot, reconstructionOptions, binEdges, crssMPa, ...
  samples);

for stateIndex = 1:numel(stateData)
  plot_single_state_figure(stateData{stateIndex}, outputRoot, ...
    families, displayNames, familyColors, binCenters);
end
initialIndex = find(samples == "7d");
finalIndex = find(samples == "5d");
if isscalar(initialIndex) && isscalar(finalIndex)
  endpointData = {stateData{initialIndex}; stateData{finalIndex}};
  plot_reference_figure(endpointData, outputRoot, families, ...
    displayNames, familyColors, binCenters);
end

outputs = struct("summary", summary, "distribution", distribution);
end

function imageData = grain_values_to_native_image(ebsdFull, ...
  nativeIndices, xValues, yValues, familyData)
[isRetained, familyLocation] = ismember( ...
  double(ebsdFull.grainId(:)), double(familyData.grain_id));
pixelValues = nan(length(ebsdFull), 1);
pixelValues(isRetained) = familyData.max_abs_schmid( ...
  familyLocation(isRetained));
imageData = nan(numel(yValues), numel(xValues));
imageData(nativeIndices) = pixelValues;
end

function [xValues, yValues, linearIndices] = native_grid_indices(ebsd)
xCoordinates = double(ebsd.x(:));
yCoordinates = double(ebsd.y(:));
xValues = unique(xCoordinates);
yValues = unique(yCoordinates);
[xFound, xIndex] = ismember(xCoordinates, xValues);
[yFound, yIndex] = ismember(yCoordinates, yValues);
assert(all(xFound & yFound));
linearIndices = sub2ind([numel(yValues), numel(xValues)], ...
  yIndex, xIndex);
assert(numel(unique(linearIndices)) == length(ebsd));
end

function [xCoordinates, yCoordinates] = boundary_coordinates(boundary)
if isempty(boundary)
  xCoordinates = nan;
  yCoordinates = nan;
  return
end
vertices = boundary.allV.xyz;
faces = boundary.F;
xCoordinates = reshape(vertices(faces.', 1), 2, []);
yCoordinates = reshape(vertices(faces.', 2), 2, []);
separator = nan(1, size(xCoordinates, 2));
xCoordinates = reshape([xCoordinates; separator], [], 1);
yCoordinates = reshape([yCoordinates; separator], [], 1);
end

function output = append_table(input, row)
if isempty(input)
  output = row;
else
  output = [input; row];
end
end

function write_parameters(outputRoot, reconstructionOptions, ...
  binEdges, crssMPa, samples)
parameter = [ ...
  "figure_basis"; "states"; "input_variant"; "load_geometry"; ...
  "load_axis"; "grain_orientation"; "family_grain_value"; ...
  "map_population"; "map_value"; "distribution_population"; ...
  "distribution_weighting"; "bin_edges"; ...
  "prismatic_a_crss_mpa"; "basal_a_crss_mpa"; ...
  "pyramidal_ca_crss_mpa"; "crss_source"; ...
  "grain_detection_threshold_deg"; "minimum_grain_pixels"; ...
  "interpretive_limit"];
value = [ ...
  "layout and content adapted from Xia et al. MSEA 975 (2026) Fig. 11"; ...
  join(samples, ","); "denoised CTF"; "uniaxial tension"; ...
  "AD (vector3d.X)"; ...
  "mean orientation of each reconstructed Ti-Hex grain"; ...
  "maximum absolute value across all symmetrised variants"; ...
  "all reconstructed Ti-Hex grains"; ...
  "one constant family value assigned to every pixel in each mapped grain"; ...
  "reconstructed Ti-Hex grains with at least five pixels"; ...
  "retained reconstructed-grain area"; ...
  join(string(compose("%.2f", binEdges)), ","); ...
  string(crssMPa(2)); string(crssMPa(1)); string(crssMPa(3)); ...
  "Xiong et al., Acta Materialia 199 (2020) 561-577, Table 4"; ...
  string(reconstructionOptions.detection_threshold_deg); ...
  string(reconstructionOptions.min_grain_pixels); ...
  "geometric and fixed-CRSS screening only; Schmid maps do not directly identify operative slip"];
writetable(table(parameter, value), fullfile(outputRoot, ...
  "reference_style_fig11_schmid_parameters.csv"));
end

function plot_single_state_figure(current, outputRoot, families, ...
  displayNames, familyColors, binCenters)
figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.4 0.4 12.6 7.5], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 6, ...
  "Padding", "compact", "TileSpacing", "compact");

mapAxes = gobjects(3, 1);
for familyIndex = 1:3
  startTile = (familyIndex - 1) * 2 + 1;
  axesHandle = nexttile(layout, startTile, [1 2]);
  mapAxes(familyIndex) = axesHandle;
  rgbImage = schmid_scalar_to_rgb(current.maps{familyIndex});
  imagesc(axesHandle, current.x_values, current.y_values, rgbImage);
  format_map_axes(axesHandle);
  line(axesHandle, current.boundary_x, current.boundary_y, ...
    "Color", [0.32 0.32 0.32], "LineWidth", 0.10);
  draw_scale_bar(axesHandle, current.x_values, current.y_values, 50);
  title(axesHandle, sprintf("(%c) %s", ...
    char('a' + familyIndex - 1), displayNames(familyIndex)), ...
    "FontWeight", "normal", "FontSize", 10.0, ...
    "Interpreter", "none");
end

axesDistribution = nexttile(layout, 7, [1 6]);
hold(axesDistribution, "on");
legendLabels = strings(3, 1);
for familyIndex = 1:3
  area(axesDistribution, binCenters, ...
    current.frequencies(:, familyIndex), ...
    "FaceColor", familyColors(familyIndex, :), ...
    "FaceAlpha", 0.10, "EdgeColor", "none", ...
    "HandleVisibility", "off");
  stairs(axesDistribution, binCenters, ...
    current.frequencies(:, familyIndex), ...
    "Color", familyColors(familyIndex, :), "LineWidth", 1.7);
  meanValue = current.summary.area_weighted_mean_max_abs_schmid( ...
    current.summary.family == families(familyIndex));
  legendLabels(familyIndex) = sprintf("%s, mean = %.3f", ...
    displayNames(familyIndex), meanValue);
end
yMaximum = max(5, ceil(1.18 * max(current.frequencies, [], "all") ...
  / 5) * 5);
xlim(axesDistribution, [0 0.5]);
ylim(axesDistribution, [0 yMaximum]);
xticks(axesDistribution, 0:0.05:0.5);
grid(axesDistribution, "on");
axesDistribution.GridAlpha = 0.13;
axesDistribution.Layer = "top";
axesDistribution.FontName = "Arial";
axesDistribution.FontSize = 9.2;
axesDistribution.LineWidth = 0.8;
xlabel(axesDistribution, ...
  "Maximum absolute Schmid factor, |m|max", "Interpreter", "none");
ylabel(axesDistribution, "Grain-area frequency (%)");
title(axesDistribution, "(d) Area-weighted distributions", ...
  "FontWeight", "normal");
legend(axesDistribution, legendLabels, "Location", "northwest", ...
  "Box", "off", "FontSize", 8.2, "Interpreter", "none");

title(layout, sprintf( ...
  "Slip-family Schmid factors: %s (%.2f mm, %.2f%% cold reduction)", ...
  current.sample, current.diameter_mm, current.cold_reduction_percent), ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold", ...
  "Interpreter", "none");
subtitle(layout, ...
  "AD tension; maps: all Ti-Hex grains; distributions: >=5-pixel grains", ...
  "FontName", "Arial", "FontSize", 9.3);
drawnow;
draw_common_color_scale(figureHandle, mapAxes(1));
drawnow;

sampleStem = replace(current.sample, ".", "_");
figureStem = fullfile(outputRoot, ...
  "reference_style_fig11_schmid_" + sampleStem);
exportgraphics(figureHandle, figureStem + ".png", ...
  "Resolution", 600, "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", ...
  "Resolution", 600, "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".pdf", ...
  "ContentType", "image", "Resolution", 600, ...
  "BackgroundColor", "white");
clear cleanupFigure
end

function plot_reference_figure(stateData, outputRoot, families, ...
  displayNames, familyColors, binCenters)
figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.4 0.4 12.6 10.2], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 3, 6, ...
  "Padding", "compact", "TileSpacing", "compact");

mapAxes = gobjects(6, 1);
panelLetters = ['a', 'b', 'c'; 'd', 'e', 'f'];
for stateIndex = 1:2
  current = stateData{stateIndex};
  for familyIndex = 1:3
    startTile = (stateIndex - 1) * 6 + ...
      (familyIndex - 1) * 2 + 1;
    axesHandle = nexttile(layout, startTile, [1 2]);
    mapAxes((stateIndex - 1) * 3 + familyIndex) = axesHandle;
    rgbImage = schmid_scalar_to_rgb(current.maps{familyIndex});
    imagesc(axesHandle, current.x_values, ...
      current.y_values, rgbImage);
    format_map_axes(axesHandle);
    line(axesHandle, current.boundary_x, current.boundary_y, ...
      "Color", [0.32 0.32 0.32], "LineWidth", 0.10);
    draw_scale_bar(axesHandle, current.x_values, ...
      current.y_values, 50);
    title(axesHandle, sprintf("(%c) %s: %s", ...
      panelLetters(stateIndex, familyIndex), current.sample, ...
      displayNames(familyIndex)), "FontWeight", "normal", ...
      "FontSize", 9.5, "Interpreter", "none");
  end
end

yMaximum = 0;
for stateIndex = 1:2
  yMaximum = max(yMaximum, max( ...
    stateData{stateIndex}.frequencies, [], "all"));
end
yMaximum = max(5, ceil(1.18 * yMaximum / 5) * 5);
for stateIndex = 1:2
  startTile = 13 + (stateIndex - 1) * 3;
  axesHandle = nexttile(layout, startTile, [1 3]);
  hold(axesHandle, "on");
  current = stateData{stateIndex};
  legendLabels = strings(3, 1);
  for familyIndex = 1:3
    area(axesHandle, binCenters, ...
      current.frequencies(:, familyIndex), ...
      "FaceColor", familyColors(familyIndex, :), ...
      "FaceAlpha", 0.10, "EdgeColor", "none", ...
      "HandleVisibility", "off");
    stairs(axesHandle, binCenters, ...
      current.frequencies(:, familyIndex), ...
      "Color", familyColors(familyIndex, :), ...
      "LineWidth", 1.65);
    meanValue = current.summary.area_weighted_mean_max_abs_schmid( ...
      current.summary.family == families(familyIndex));
    legendLabels(familyIndex) = sprintf("%s, mean = %.3f", ...
      displayNames(familyIndex), meanValue);
  end
  xlim(axesHandle, [0 0.5]);
  ylim(axesHandle, [0 yMaximum]);
  xticks(axesHandle, 0:0.1:0.5);
  grid(axesHandle, "on");
  axesHandle.GridAlpha = 0.13;
  axesHandle.Layer = "top";
  axesHandle.FontName = "Arial";
  axesHandle.FontSize = 8.7;
  axesHandle.LineWidth = 0.8;
  xlabel(axesHandle, "Maximum absolute Schmid factor, |m|max", ...
    "Interpreter", "none");
  ylabel(axesHandle, "Grain-area frequency (%)");
  title(axesHandle, sprintf("(%c) %s distribution", ...
    char('g' + stateIndex - 1), current.sample), ...
    "FontWeight", "normal");
  legend(axesHandle, legendLabels, "Location", "northwest", ...
    "Box", "off", "FontSize", 7.7, "Interpreter", "none");
end

title(layout, ...
  "Slip-family Schmid-factor maps and distributions under AD tension", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold");
subtitle(layout, ...
  "Maps: all Ti-Hex grains; distributions: >=5-pixel grains; no contours", ...
  "FontName", "Arial", "FontSize", 9.3);
drawnow;
draw_common_color_scale(figureHandle, mapAxes(1));
drawnow;

figureStem = fullfile(outputRoot, ...
  "reference_style_fig11_schmid_7d_5d");
exportgraphics(figureHandle, figureStem + ".png", ...
  "Resolution", 600, "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", ...
  "Resolution", 600, "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".pdf", ...
  "ContentType", "image", "Resolution", 600, ...
  "BackgroundColor", "white");
clear cleanupFigure
end

function format_map_axes(axesHandle)
axis(axesHandle, "image");
set(axesHandle, "YDir", "normal", "XTick", [], "YTick", [], ...
  "Box", "on", "LineWidth", 0.55, "FontName", "Arial");
hold(axesHandle, "on");
end

function rgbImage = schmid_scalar_to_rgb(values)
colorTable = turbo(256);
valid = isfinite(values);
bounded = min(0.5, max(0, values));
colorIndex = 1 + floor(255 * bounded / 0.5);
colorIndex(~valid) = 1;
rgbImage = ind2rgb(colorIndex, colorTable);
for channelIndex = 1:3
  channel = rgbImage(:, :, channelIndex);
  channel(~valid) = 0.88;
  rgbImage(:, :, channelIndex) = channel;
end
end

function draw_scale_bar(axesHandle, xValues, yValues, lengthUm)
xRange = max(xValues) - min(xValues);
yRange = max(yValues) - min(yValues);
xStart = min(xValues) + 0.06 * xRange;
yPosition = min(yValues) + 0.07 * yRange;
line(axesHandle, [xStart xStart + lengthUm], ...
  [yPosition yPosition], "Color", "black", "LineWidth", 2.0);
text(axesHandle, xStart + lengthUm / 2, ...
  yPosition + 0.018 * yRange, sprintf("%d um", lengthUm), ...
  "HorizontalAlignment", "center", "VerticalAlignment", "bottom", ...
  "FontName", "Arial", "FontSize", 6.8, ...
  "BackgroundColor", "white", "Margin", 0.6);
end

function draw_common_color_scale(figureHandle, referenceAxes)
referencePosition = referenceAxes.Position;
scaleAxes = axes(figureHandle, "Units", "normalized", ...
  "Position", [referencePosition(1) + 0.55 * referencePosition(3), ...
  referencePosition(2) + 0.91 * referencePosition(4), ...
  0.40 * referencePosition(3), 0.026 * referencePosition(4)]);
imagesc(scaleAxes, linspace(0, 0.5, 256), 1, 1:256);
set(scaleAxes, "YTick", [], "XTick", [0 0.25 0.5], ...
  "XLim", [0 0.5], "FontName", "Arial", "FontSize", 7.2, ...
  "Box", "on", "XAxisLocation", "top");
colormap(scaleAxes, turbo(256));
end
