function envelope = generate_ca_preferred_orientation_envelope( ...
  scanRoot, outputRoot)
%GENERATE_CA_PREFERRED_ORIENTATION_ENVELOPE Sweep c-axis angle and azimuth.
%
% The loading direction is represented in crystal coordinates. At every
% c-axis-to-load angle and azimuth, this calculation compares maximum
% absolute family Schmid factor divided by literature CRSS.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

catalog = comprehensive_ebsd_catalog(scanRoot);
[ebsd, ~] = load_comprehensive_ebsd_scan(catalog(1, :));
cs = ebsd("Ti-Hex").CS;
clear ebsd

thetaValuesDeg = (0:0.1:25)';
azimuthValuesDeg = (0:0.25:359.75)';
[thetaGridDeg, azimuthGridDeg] = ndgrid( ...
  thetaValuesDeg, azimuthValuesDeg);
loadDirections = vector3d.byPolar(thetaGridDeg(:) * degree, ...
  azimuthGridDeg(:) * degree);

prismatic = slipSystem.prismaticA(cs).symmetrise("antipodal");
basal = slipSystem.basal(cs).symmetrise("antipodal");
pyramidalCA = slipSystem.pyramidalCA(cs).symmetrise("antipodal");
prismaticM = max(abs(prismatic.SchmidFactor(loadDirections)), [], 2);
basalM = max(abs(basal.SchmidFactor(loadDirections)), [], 2);
caM = max(abs(pyramidalCA.SchmidFactor(loadDirections)), [], 2);
bestADrive = max(prismaticM / 154, basalM / 252);
caDrive = caM / 756;
ratio = caDrive ./ bestADrive;
ratio(bestADrive == 0 & caDrive > 0) = Inf;
preferred = caDrive > bestADrive;

nTheta = numel(thetaValuesDeg);
nAzimuth = numel(azimuthValuesDeg);
preferred = reshape(preferred, nTheta, nAzimuth);
ratio = reshape(ratio, nTheta, nAzimuth);
prismaticM = reshape(prismaticM, nTheta, nAzimuth);
basalM = reshape(basalM, nTheta, nAzimuth);
caM = reshape(caM, nTheta, nAzimuth);

azimuth_fraction_ca_preferred = mean(preferred, 2);
minimum_drive_ratio = min(ratio, [], 2);
median_drive_ratio = median(ratio, 2);
maximum_drive_ratio = max(ratio, [], 2);
minimum_ca_max_abs_schmid = min(caM, [], 2);
maximum_ca_max_abs_schmid = max(caM, [], 2);
maximum_prismatic_max_abs_schmid = max(prismaticM, [], 2);
maximum_basal_max_abs_schmid = max(basalM, [], 2);
envelope = table(thetaValuesDeg, azimuth_fraction_ca_preferred, ...
  minimum_drive_ratio, median_drive_ratio, maximum_drive_ratio, ...
  minimum_ca_max_abs_schmid, maximum_ca_max_abs_schmid, ...
  maximum_prismatic_max_abs_schmid, maximum_basal_max_abs_schmid, ...
  'VariableNames', {'c_axis_ad_angle_deg', ...
  'azimuth_fraction_ca_preferred', 'minimum_drive_ratio', ...
  'median_drive_ratio', 'maximum_drive_ratio', ...
  'minimum_ca_max_abs_schmid', 'maximum_ca_max_abs_schmid', ...
  'maximum_prismatic_max_abs_schmid', ...
  'maximum_basal_max_abs_schmid'});

allAzimuth = azimuth_fraction_ca_preferred >= 1 - 1e-12;
anyAzimuth = azimuth_fraction_ca_preferred > 0;
assert(allAzimuth(1) && any(anyAzimuth));
allAzimuthMaximumDeg = max(thetaValuesDeg(allAzimuth));
anyAzimuthMaximumDeg = max(thetaValuesDeg(anyAzimuth));
fprintf("CA_ALL_AZIMUTH_MAX_ANGLE_DEG=%.3f\n", ...
  allAzimuthMaximumDeg);
fprintf("CA_ANY_AZIMUTH_MAX_ANGLE_DEG=%.3f\n", ...
  anyAzimuthMaximumDeg);

writetable(envelope, fullfile(outputRoot, ...
  "ca_preferred_orientation_envelope.csv"));
write_parameters(outputRoot, thetaValuesDeg, azimuthValuesDeg, ...
  allAzimuthMaximumDeg, anyAzimuthMaximumDeg);
plot_envelope(envelope, outputRoot);
end

function write_parameters(outputRoot, thetaValuesDeg, ...
  azimuthValuesDeg, allAzimuthMaximumDeg, anyAzimuthMaximumDeg)
parameter = [ ...
  "preference_metric"; "ca_preferred_condition"; ...
  "prismatic_a_crss_mpa"; "basal_a_crss_mpa"; ...
  "pyramidal_ca_crss_mpa"; "crss_source"; "source_doi"; ...
  "theta_range_deg"; "theta_step_deg"; "azimuth_range_deg"; ...
  "azimuth_step_deg"; "all_azimuth_maximum_angle_deg"; ...
  "any_azimuth_maximum_angle_deg"; "interpretive_limit"];
value = [ ...
  "maximum absolute family Schmid factor divided by literature CRSS"; ...
  "m_ca/756 > max(m_prismatic/154, m_basal/252)"; ...
  "154"; "252"; "756"; ...
  "Xiong et al., Acta Materialia 199 (2020) 561-577, Table 4"; ...
  "10.1016/j.actamat.2020.08.010"; ...
  sprintf("%.1f:%.1f:%.1f", min(thetaValuesDeg), ...
    thetaValuesDeg(2) - thetaValuesDeg(1), max(thetaValuesDeg)); ...
  string(thetaValuesDeg(2) - thetaValuesDeg(1)); ...
  sprintf("%.2f:%.2f:%.2f", min(azimuthValuesDeg), ...
    azimuthValuesDeg(2) - azimuthValuesDeg(1), ...
    max(azimuthValuesDeg)); ...
  string(azimuthValuesDeg(2) - azimuthValuesDeg(1)); ...
  string(allAzimuthMaximumDeg); string(anyAzimuthMaximumDeg); ...
  "orientation-space screening under uniaxial loading; local stress, hardening evolution and neighbor constraints are not resolved"];
writetable(table(parameter, value), fullfile(outputRoot, ...
  "ca_preferred_orientation_parameters.csv"));
end

function plot_envelope(envelope, outputRoot)
purple = [0.45 0.24 0.65];
blue = [0.10 0.43 0.72];

figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 9.5 6.8], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 1, ...
  "Padding", "compact", "TileSpacing", "compact");

topAxes = nexttile(layout);
plot(topAxes, envelope.c_axis_ad_angle_deg, ...
  100 * envelope.azimuth_fraction_ca_preferred, ...
  "-", "Color", purple, "LineWidth", 2.0);
format_axes(topAxes);
ylim(topAxes, [0 105]);
ylabel(topAxes, "Azimuths with <c+a> preference (%)");
title(topAxes, ...
  "Fraction of rotations about the c-axis satisfying R > 1", ...
  "FontWeight", "normal", "FontSize", 9.5);

bottomAxes = nexttile(layout);
hold(bottomAxes, "on");
plot(bottomAxes, envelope.c_axis_ad_angle_deg, ...
  envelope.minimum_drive_ratio, "--", "Color", blue, ...
  "LineWidth", 1.2, "DisplayName", "Minimum R over azimuth");
plot(bottomAxes, envelope.c_axis_ad_angle_deg, ...
  envelope.median_drive_ratio, "-", "Color", purple, ...
  "LineWidth", 1.8, "DisplayName", "Median R over azimuth");
plot(bottomAxes, envelope.c_axis_ad_angle_deg, ...
  envelope.maximum_drive_ratio, "-.", "Color", [0.86 0.33 0.10], ...
  "LineWidth", 1.4, "DisplayName", "Maximum R over azimuth");
yline(bottomAxes, 1, ":", "Color", [0.25 0.25 0.25], ...
  "LineWidth", 1.2, "DisplayName", "R = 1 threshold");
format_axes(bottomAxes);
bottomAxes.YScale = "log";
ylim(bottomAxes, [0.2 20]);
yticks(bottomAxes, [0.2 0.5 1 2 5 10 20]);
yticklabels(bottomAxes, {'0.2', '0.5', '1', '2', '5', '10', '20'});
xlabel(bottomAxes, "Acute c-axis angle to AD (degree)");
ylabel(bottomAxes, "R = P_{<c+a>} / max(P_{prismatic},P_{basal})");
legend(bottomAxes, "Location", "northeast", "Box", "off", ...
  "FontSize", 8.0);
title(bottomAxes, ...
  "CRSS-normalized drive ratio across c-axis azimuth", ...
  "FontWeight", "normal", "FontSize", 9.5);

title(layout, ...
  "Orientation envelope for pyramidal <c+a> preference", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold");
subtitle(layout, ...
  "CRSS: prismatic <a> 154 MPa; basal <a> 252 MPa; pyramidal <c+a> 756 MPa", ...
  "FontName", "Arial", "FontSize", 9.5);
drawnow;

figureStem = fullfile(outputRoot, ...
  "ca_preferred_orientation_envelope");
exportgraphics(figureHandle, figureStem + ".png", "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", "Resolution", 600, ...
  "BackgroundColor", "white");
clear cleanupFigure
end

function format_axes(axesHandle)
xlim(axesHandle, [0 25]);
xticks(axesHandle, 0:2.5:25);
grid(axesHandle, "on");
axesHandle.GridAlpha = 0.13;
axesHandle.Layer = "top";
axesHandle.FontName = "Arial";
axesHandle.FontSize = 9.2;
axesHandle.LineWidth = 0.8;
end
