function [summary, distribution, byGrain] = ...
  generate_c_axis_ad_grain_histogram(scanRoot, outputRoot)
%GENERATE_C_AXIS_AD_GRAIN_HISTOGRAM Plot area-weighted grain-mean angles.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

contract = comprehensive_ebsd_output_contract();
catalog = comprehensive_ebsd_catalog(scanRoot);
reconstructionOptions = struct( ...
  "detection_threshold_deg", ...
  contract.parameters.primary_grain_detection_deg, ...
  "min_grain_pixels", contract.parameters.min_grain_pixels);
binEdgesDeg = (0:2:90)';
binLowerDeg = binEdgesDeg(1:end-1);
binUpperDeg = binEdgesDeg(2:end);
binCenterDeg = (binLowerDeg + binUpperDeg) / 2;

summary = table();
distribution = table();
byGrain = table();
for scanIndex = 1:height(catalog)
  catalogRow = catalog(scanIndex, :);
  fprintf("C_AXIS_AD_HIST sample=%s variant=%s\n", ...
    catalogRow.sample, catalogRow.variant);
  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalogRow);
  [grains, ~, ~] = reconstruct_comprehensive_grains( ...
    ebsdFull, reconstructionOptions);
  retained = grains("Ti-Hex");
  retained = retained(retained.numPixel >= ...
    reconstructionOptions.min_grain_pixels);
  assert(~isempty(retained));

  areaUm2 = double(area(retained));
  areaUm2 = areaUm2(:);
  areaWeight = areaUm2 / sum(areaUm2);
  cAxis = Miller(0, 0, 0, 1, retained.meanOrientation.CS);
  angleDeg = c_axis_angles_to_ad(retained.meanOrientation * cAxis);
  assert(numel(angleDeg) == length(retained));
  binIndex = discretize(angleDeg, binEdgesDeg);
  assert(all(isfinite(binIndex)));
  numberFrequencyPercent = 100 * accumarray(binIndex, 1, ...
    [numel(binCenterDeg), 1], @sum, 0) / numel(angleDeg);
  areaWeightedFrequencyPercent = 100 * accumarray( ...
    binIndex, areaWeight, [numel(binCenterDeg), 1], @sum, 0);
  assert(abs(sum(numberFrequencyPercent) - 100) < 1e-10);
  assert(abs(sum(areaWeightedFrequencyPercent) - 100) < 1e-10);

  grainRows = table( ...
    repmat(catalogRow.sample, numel(angleDeg), 1), ...
    repmat(catalogRow.diameter_mm, numel(angleDeg), 1), ...
    repmat(catalogRow.cold_reduction_percent, numel(angleDeg), 1), ...
    repmat(catalogRow.variant, numel(angleDeg), 1), ...
    double(retained.id(:)), double(retained.numPixel(:)), areaUm2, ...
    areaWeight, angleDeg, ...
    'VariableNames', {'sample', 'diameter_mm', ...
    'cold_reduction_percent', 'variant', 'grain_id', 'num_pixels', ...
    'area_um2', 'area_weight', 'c_axis_ad_acute_angle_deg'});
  distributionRows = table( ...
    repmat(catalogRow.sample, numel(binCenterDeg), 1), ...
    repmat(catalogRow.diameter_mm, numel(binCenterDeg), 1), ...
    repmat(catalogRow.cold_reduction_percent, numel(binCenterDeg), 1), ...
    repmat(catalogRow.variant, numel(binCenterDeg), 1), ...
    binLowerDeg, binUpperDeg, binCenterDeg, ...
    numberFrequencyPercent, areaWeightedFrequencyPercent, ...
    'VariableNames', {'sample', 'diameter_mm', ...
    'cold_reduction_percent', 'variant', 'bin_lower_deg', ...
    'bin_upper_deg', 'bin_center_deg', 'number_frequency_percent', ...
    'area_weighted_frequency_percent'});
  angleQuantiles = weighted_quantile(angleDeg, areaWeight, ...
    [0.10 0.50 0.90]);
  summaryRow = table(catalogRow.sample, catalogRow.diameter_mm, ...
    catalogRow.cold_reduction_percent, catalogRow.variant, ...
    numel(angleDeg), sum(areaWeight .* angleDeg), ...
    angleQuantiles(1), angleQuantiles(2), angleQuantiles(3), ...
    min(angleDeg), nnz(angleDeg <= 9.1), ...
    100 * sum(areaWeight(angleDeg <= 9.1)), ...
    nnz(angleDeg <= 10.6), ...
    100 * sum(areaWeight(angleDeg <= 10.6)), ...
    'VariableNames', {'sample', 'diameter_mm', ...
    'cold_reduction_percent', 'variant', 'grain_count', ...
    'area_weighted_mean_angle_deg', 'area_weighted_p10_angle_deg', ...
    'area_weighted_median_angle_deg', 'area_weighted_p90_angle_deg', ...
    'minimum_angle_deg', 'grain_count_within_9p1deg', ...
    'grain_area_percent_within_9p1deg', ...
    'grain_count_within_10p6deg', ...
    'grain_area_percent_within_10p6deg'});
  if isempty(summary)
    summary = summaryRow;
    distribution = distributionRows;
    byGrain = grainRows;
  else
    summary = [summary; summaryRow]; %#ok<AGROW>
    distribution = [distribution; distributionRows]; %#ok<AGROW>
    byGrain = [byGrain; grainRows]; %#ok<AGROW>
  end
  clear ebsdFull grains retained grainRows distributionRows
end

summary = sortrows(summary, {'cold_reduction_percent', 'variant'});
distribution = sortrows(distribution, ...
  {'cold_reduction_percent', 'variant', 'bin_center_deg'});
byGrain = sortrows(byGrain, ...
  {'cold_reduction_percent', 'variant', 'grain_id'});
writetable(byGrain, fullfile(outputRoot, ...
  "c_axis_ad_angle_by_grain.csv"));
writetable(summary, fullfile(outputRoot, ...
  "c_axis_ad_angle_summary.csv"));
writetable(distribution, fullfile(outputRoot, ...
  "c_axis_ad_angle_histograms.csv"));
write_parameters(outputRoot, reconstructionOptions, binEdgesDeg);
plot_histograms(distribution, summary, outputRoot);
end

function result = weighted_quantile(values, weights, probabilities)
[sortedValues, order] = sort(values);
sortedWeights = weights(order) / sum(weights);
cumulative = cumsum(sortedWeights);
result = zeros(size(probabilities));
for probabilityIndex = 1:numel(probabilities)
  result(probabilityIndex) = sortedValues(find(cumulative >= ...
    probabilities(probabilityIndex), 1, "first"));
end
end

function write_parameters(outputRoot, reconstructionOptions, binEdgesDeg)
parameter = [ ...
  "metric"; "c_axis_definition"; "load_axis"; "grain_orientation"; ...
  "primary_weighting"; "bin_edges_deg"; "bin_width_deg"; ...
  "grain_detection_threshold_deg"; "minimum_grain_pixels"; ...
  "primary_input"; "sensitivity_input"; ...
  "all_azimuth_ca_preference_limit_deg"; ...
  "any_azimuth_ca_preference_limit_deg"; "interpretive_limit"];
value = [ ...
  "acute angle between grain-mean alpha-Ti c-axis and AD"; ...
  "orientation * Miller(0,0,0,1), antipodal acute angle"; ...
  "AD (vector3d.X)"; "mean orientation of retained Ti-Hex grain"; ...
  "reconstructed-grain area"; "0:2:90"; ...
  string(binEdgesDeg(2) - binEdgesDeg(1)); ...
  string(reconstructionOptions.detection_threshold_deg); ...
  string(reconstructionOptions.min_grain_pixels); ...
  "raw CTF"; "denoised CTF"; "9.1"; "10.6"; ...
  "one EBSD field per state; angle distribution does not directly identify active slip"];
writetable(table(parameter, value), fullfile(outputRoot, ...
  "c_axis_ad_angle_parameters.csv"));
end

function plot_histograms(distribution, summary, outputRoot)
colorOrder = [ ...
  0.40 0.40 0.40
  0.00 0.45 0.70
  0.34 0.71 0.91
  0.00 0.62 0.45
  0.90 0.62 0.00
  0.84 0.37 0.00];
purple = [0.45 0.24 0.65];
rawSummary = sortrows(summary(summary.variant == "raw", :), ...
  "cold_reduction_percent");
yMaximum = max(distribution.area_weighted_frequency_percent);
yMaximum = max(5, 5 * ceil(1.18 * yMaximum / 5));

figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.25 0.25 4.7 10.4], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 6, 1, ...
  "Padding", "compact", "TileSpacing", "compact");
panelLetters = 'a':'f';
for sampleIndex = 1:height(rawSummary)
  axesHandle = nexttile(layout);
  sample = rawSummary.sample(sampleIndex);
  rawRows = distribution.sample == sample & ...
    distribution.variant == "raw";
  denoisedRows = distribution.sample == sample & ...
    distribution.variant == "denoised";
  raw = sortrows(distribution(rawRows, :), "bin_center_deg");
  denoised = sortrows(distribution(denoisedRows, :), ...
    "bin_center_deg");
  assert(height(raw) == 45 && height(denoised) == 45);

  preferencePatch = patch(axesHandle, [0 10.6 10.6 0], ...
    [0 0 yMaximum yMaximum], purple, "FaceAlpha", 0.08, ...
    "EdgeColor", "none", "DisplayName", ...
    "Potential <c+a> preference envelope");
  hold(axesHandle, "on");
  bars = bar(axesHandle, raw.bin_center_deg, ...
    raw.area_weighted_frequency_percent, 0.84, ...
    "FaceColor", colorOrder(sampleIndex, :), "FaceAlpha", 0.72, ...
    "EdgeColor", [0.18 0.18 0.18], "LineWidth", 0.35, ...
    "DisplayName", "Raw histogram");
  denoisedLine = plot(axesHandle, denoised.bin_center_deg, ...
    denoised.area_weighted_frequency_percent, "--", ...
    "Color", [0.12 0.12 0.12], "LineWidth", 1.15, ...
    "DisplayName", "Denoised sensitivity");
  xline(axesHandle, 10.6, ":", "Color", purple, ...
    "LineWidth", 0.9, "HandleVisibility", "off");
  xlim(axesHandle, [0 90]);
  ylim(axesHandle, [0 yMaximum]);
  xticks(axesHandle, 0:15:90);
  set(axesHandle, "FontName", "Arial", "FontSize", 7, ...
    "TickDir", "out", "Box", "on", "LineWidth", 0.6, ...
    "Layer", "top");
  ylabel(axesHandle, "Area-weighted frequency (%)", ...
    "FontName", "Arial", "FontSize", 7);
  if sampleIndex < 6
    set(axesHandle, "XTickLabel", []);
  else
    xlabel(axesHandle, "Acute c-axis angle to AD (degree)", ...
      "FontName", "Arial", "FontSize", 8);
  end
  text(axesHandle, 0.015, 0.94, ...
    sprintf("(%c) %.2f%% | %.2f mm", panelLetters(sampleIndex), ...
    rawSummary.cold_reduction_percent(sampleIndex), ...
    rawSummary.diameter_mm(sampleIndex)), "Units", "normalized", ...
    "HorizontalAlignment", "left", "VerticalAlignment", "top", ...
    "FontName", "Arial", "FontSize", 7.5, "FontWeight", "bold");
  centralText = sprintf("Mean = %.1f deg | Median = %.1f deg", ...
    rawSummary.area_weighted_mean_angle_deg(sampleIndex), ...
    rawSummary.area_weighted_median_angle_deg(sampleIndex));
  envelopeText = sprintf("A(theta <= 10.6 deg) = %.3f%%", ...
    rawSummary.grain_area_percent_within_10p6deg(sampleIndex));
  text(axesHandle, 0.015, 0.76, centralText, "Units", "normalized", ...
    "HorizontalAlignment", "left", "VerticalAlignment", "top", ...
    "FontName", "Arial", "FontSize", 6.8, ...
    "Color", colorOrder(sampleIndex, :), "FontWeight", "bold");
  text(axesHandle, 0.015, 0.61, envelopeText, "Units", "normalized", ...
    "HorizontalAlignment", "left", "VerticalAlignment", "top", ...
    "FontName", "Arial", "FontSize", 6.5, ...
    "Color", colorOrder(sampleIndex, :), "FontWeight", "bold");
  if sampleIndex == 1
    legend(axesHandle, [bars denoisedLine preferencePatch], ...
      "Location", "southwest", "FontName", "Arial", ...
      "FontSize", 5.8, "Box", "off");
  end
end
title(layout, ...
  "Area-weighted grain-mean c-axis/AD angle | 2 deg grains; minPixel = 5", ...
  "FontName", "Arial", "FontSize", 8.4, "FontWeight", "bold");
figureStem = fullfile(outputRoot, ...
  "c_axis_ad_angle_distribution_area_weighted");
exportgraphics(figureHandle, figureStem + ".png", "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", "Resolution", 600, ...
  "BackgroundColor", "white");
clear cleanupFigure
end
