function [distribution, summary] = generate_extension_twin_schmid_distribution( ...
  scanRoot, outputRoot)
%GENERATE_EXTENSION_TWIN_SCHMID_DISTRIBUTION Extension-twin SF wrapper.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

plotSpec = struct( ...
  "target_family", "extension_twin_t1", ...
  "display_name", "{10-12} extension-twin", ...
  "file_stem", "extension_twin_schmid", ...
  "system_description", ...
  "MTEX slipSystem.twinT1 ({10-12} extension-twin family)", ...
  "interpretive_limit", ...
  "no CRSS, local-stress, or twin-polarity activity claim");
[distribution, summary] = generate_family_schmid_distribution( ...
  scanRoot, outputRoot, plotSpec);
end
