function stateSummary = generate_grain_size_distribution_matrix( ...
    scanRoot, outputDir)
%GENERATE_GRAIN_SIZE_DISTRIBUTION_MATRIX HAGB-grain ECD distributions.
% Reconstructs raw Ti-Hex grains at 15 degrees without smoothing, retains
% grains with at least five pixels, and exports number- and area-weighted
% vertical histograms with descriptive lognormal fits.

arguments
  scanRoot (1,1) string
  outputDir (1,1) string
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), "MTEX must be loaded before this function.");
if ~isfolder(outputDir)
  mkdir(outputDir);
end

hagbThresholdDeg = 15;
minGrainPixels = 5;
binWidthUm = 2;
sampleCount = 6;

catalog = comprehensive_ebsd_catalog(scanRoot);
catalog = catalog(catalog.variant == "raw", :);
[~, order] = sort(catalog.cold_reduction_percent);
catalog = catalog(order, :);
assert(height(catalog) == sampleCount, "Expected six raw EBSD states.");

ecdByState = cell(sampleCount, 1);
areaByState = cell(sampleCount, 1);
grainTables = cell(sampleCount, 1);
for sampleIndex = 1:sampleCount
  fprintf("GRAIN_SIZE sample=%s reduction=%.2f%%\n", ...
    catalog.sample(sampleIndex), catalog.cold_reduction_percent(sampleIndex));
  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalog(sampleIndex, :));
  grains = calcGrains(ebsdFull, "unitCell", ...
    "threshold", hagbThresholdDeg * degree);
  tiGrains = grains("Ti-Hex");
  keep = tiGrains.numPixel >= minGrainPixels;
  measured = tiGrains(keep);
  assert(~isempty(measured), "No Ti-Hex HAGB grains pass minPixel.");

  areaUm2 = abs(double(area(measured)));
  areaUm2 = areaUm2(:);
  ecdUm = 2 * sqrt(areaUm2 / pi);
  valid = isfinite(areaUm2) & areaUm2 > 0 & ...
    isfinite(ecdUm) & ecdUm > 0;
  areaUm2 = areaUm2(valid);
  ecdUm = ecdUm(valid);
  measured = measured(valid);
  assert(~isempty(ecdUm));

  ecdByState{sampleIndex} = ecdUm;
  areaByState{sampleIndex} = areaUm2;
  grainTables{sampleIndex} = table( ...
    repmat(catalog.sample(sampleIndex), numel(ecdUm), 1), ...
    repmat(catalog.diameter_mm(sampleIndex), numel(ecdUm), 1), ...
    repmat(catalog.cold_reduction_percent(sampleIndex), numel(ecdUm), 1), ...
    repmat(catalog.variant(sampleIndex), numel(ecdUm), 1), ...
    double(measured.id(:)), double(measured.numPixel(:)), ...
    logical(isBoundary(measured)), areaUm2, ecdUm, ...
    'VariableNames', ["sample", "diameter_mm", ...
    "cold_reduction_percent", "variant", "grain_id", "num_pixels", ...
    "boundary_touching", "area_um2", "ecd_um"]);
  clear ebsdFull grains tiGrains measured
end

allEcd = vertcat(ecdByState{:});
maxEdgeUm = max(20, binWidthUm * ceil(max(allEcd) / binWidthUm));
edgesUm = 0:binWidthUm:maxEdgeUm;
if edgesUm(end) < max(allEcd)
  edgesUm(end + 1) = edgesUm(end) + binWidthUm;
end
centersUm = edgesUm(1:end-1) + binWidthUm / 2;
binCount = numel(centersUm);

numberFrequency = zeros(sampleCount, binCount);
areaFrequency = zeros(sampleCount, binCount);
numberFit = zeros(sampleCount, binCount);
areaFit = zeros(sampleCount, binCount);
summaryRows = cell(sampleCount, 19);
histogramRows = cell(sampleCount * binCount, 12);
histogramRowIndex = 0;
for sampleIndex = 1:sampleCount
  ecdUm = ecdByState{sampleIndex};
  areaUm2 = areaByState{sampleIndex};
  binIndex = discretize(ecdUm, edgesUm);
  assert(all(isfinite(binIndex)), "Common ECD bins do not span all grains.");
  numberFrequency(sampleIndex, :) = 100 * accumarray(binIndex, 1, ...
    [binCount 1], @sum, 0).' / numel(ecdUm);
  areaFrequency(sampleIndex, :) = 100 * accumarray(binIndex, areaUm2, ...
    [binCount 1], @sum, 0).' / sum(areaUm2);

  [numberMu, numberSigma] = weighted_log_parameters( ...
    ecdUm, ones(size(ecdUm)));
  [areaMu, areaSigma] = weighted_log_parameters(ecdUm, areaUm2);
  numberFit(sampleIndex, :) = 100 * binWidthUm * ...
    lognormal_pdf(centersUm, numberMu, numberSigma);
  areaFit(sampleIndex, :) = 100 * binWidthUm * ...
    lognormal_pdf(centersUm, areaMu, areaSigma);

  numberMean = mean(ecdUm);
  numberMedian = median(ecdUm);
  areaMean = sum(ecdUm .* areaUm2) / sum(areaUm2);
  areaMedian = weighted_quantile(ecdUm, areaUm2, 0.5);
  numberP90 = prctile(ecdUm, 90);
  areaP90 = weighted_quantile(ecdUm, areaUm2, 0.9);
  boundaryTouching = grainTables{sampleIndex}.boundary_touching;
  summaryRows(sampleIndex, :) = { ...
    catalog.sample(sampleIndex), catalog.diameter_mm(sampleIndex), ...
    catalog.cold_reduction_percent(sampleIndex), ...
    catalog.variant(sampleIndex), hagbThresholdDeg, minGrainPixels, ...
    numel(ecdUm), sum(areaUm2), mean(boundaryTouching), ...
    numberMean, numberMedian, numberP90, areaMean, areaMedian, areaP90, ...
    numberMu, numberSigma, areaMu, areaSigma};

  for binIndexValue = 1:binCount
    histogramRowIndex = histogramRowIndex + 1;
    histogramRows(histogramRowIndex, :) = { ...
      catalog.sample(sampleIndex), catalog.diameter_mm(sampleIndex), ...
      catalog.cold_reduction_percent(sampleIndex), ...
      edgesUm(binIndexValue), edgesUm(binIndexValue + 1), ...
      centersUm(binIndexValue), numberFrequency(sampleIndex, binIndexValue), ...
      areaFrequency(sampleIndex, binIndexValue), ...
      numberFit(sampleIndex, binIndexValue), ...
      areaFit(sampleIndex, binIndexValue), hagbThresholdDeg, ...
      minGrainPixels};
  end
end

stateSummary = cell2table(summaryRows, 'VariableNames', [ ...
  "sample", "diameter_mm", "cold_reduction_percent", "variant", ...
  "hagb_threshold_deg", "min_grain_pixels", "grain_count", ...
  "total_retained_area_um2", "boundary_touching_grain_fraction", ...
  "ecd_number_mean_um", "ecd_number_median_um", "ecd_number_p90_um", ...
  "ecd_area_weighted_mean_um", "ecd_area_weighted_median_um", ...
  "ecd_area_weighted_p90_um", "number_lognormal_mu", ...
  "number_lognormal_sigma", "area_lognormal_mu", ...
  "area_lognormal_sigma"]);
numericNames = setdiff(string(stateSummary.Properties.VariableNames), ...
  ["sample", "variant"]);
for name = numericNames
  if iscell(stateSummary.(name))
    stateSummary.(name) = cell2mat(stateSummary.(name));
  end
end

histogramTable = cell2table(histogramRows, 'VariableNames', [ ...
  "sample", "diameter_mm", "cold_reduction_percent", ...
  "bin_lower_um", "bin_upper_um", "bin_center_um", ...
  "number_frequency_percent", "area_weighted_frequency_percent", ...
  "number_lognormal_fit_percent_per_bin", ...
  "area_lognormal_fit_percent_per_bin", "hagb_threshold_deg", ...
  "min_grain_pixels"]);
for name = setdiff(string(histogramTable.Properties.VariableNames), "sample")
  if iscell(histogramTable.(name))
    histogramTable.(name) = cell2mat(histogramTable.(name));
  end
end

byGrain = vertcat(grainTables{:});
writetable(byGrain, fullfile(outputDir, ...
  "hagb_grain_size_by_grain.csv"));
writetable(stateSummary, fullfile(outputDir, ...
  "hagb_grain_size_summary.csv"));
writetable(histogramTable, fullfile(outputDir, ...
  "hagb_grain_size_histograms.csv"));

colorOrder = [ ...
  0.40 0.40 0.40
  0.00 0.45 0.70
  0.34 0.71 0.91
  0.00 0.62 0.45
  0.90 0.62 0.00
  0.84 0.37 0.00];
render_distribution(numberFrequency, numberFit, centersUm, binWidthUm, ...
  stateSummary, catalog, colorOrder, "Number frequency (%)", ...
  "ecd_number_mean_um", "Number-weighted HAGB grain ECD", ...
  fullfile(outputDir, "grain_size_distribution_number_weighted.png"), ...
  fullfile(outputDir, "grain_size_distribution_number_weighted.tif"), ...
  fullfile(outputDir, "grain_size_distribution_number_weighted.pdf"));
render_distribution(areaFrequency, areaFit, centersUm, binWidthUm, ...
  stateSummary, catalog, colorOrder, "Area-weighted frequency (%)", ...
  "ecd_area_weighted_mean_um", "Area-weighted HAGB grain ECD", ...
  fullfile(outputDir, "grain_size_distribution_area_weighted.png"), ...
  fullfile(outputDir, "grain_size_distribution_area_weighted.tif"), ...
  fullfile(outputDir, "grain_size_distribution_area_weighted.pdf"));
end

function render_distribution(frequency, fitted, centersUm, binWidthUm, ...
    summary, catalog, colorOrder, yLabelText, meanVariable, figureTitle, ...
    pngPath, tifPath, pdfPath)
figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.25 0.25 4.7 10.4]);
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 6, 1, "Padding", "compact", ...
  "TileSpacing", "compact");
yMaximum = max(frequency, [], "all");
yMaximum = max(5, 5 * ceil(1.18 * yMaximum / 5));
xMaximum = centersUm(end) + binWidthUm / 2;
panelLetters = 'a':'f';
for sampleIndex = 1:6
  axesHandle = nexttile(layout);
  bars = bar(axesHandle, centersUm, frequency(sampleIndex, :), 0.84, ...
    "FaceColor", colorOrder(sampleIndex, :), "FaceAlpha", 0.72, ...
    "EdgeColor", [0.18 0.18 0.18], "LineWidth", 0.35);
  hold(axesHandle, "on");
  fitLine = plot(axesHandle, centersUm, fitted(sampleIndex, :), ...
    "Color", [0.15 0.15 0.15], "LineWidth", 1.25);
  xlim(axesHandle, [0 xMaximum]);
  ylim(axesHandle, [0 yMaximum]);
  set(axesHandle, "FontName", "Arial", "FontSize", 7, ...
    "TickDir", "out", "Box", "on", "LineWidth", 0.6, ...
    "Layer", "top");
  ylabel(axesHandle, yLabelText, "FontName", "Arial", "FontSize", 7);
  if sampleIndex < 6
    set(axesHandle, "XTickLabel", []);
  else
    xlabel(axesHandle, "Equivalent circle diameter (um)", ...
      "FontName", "Arial", "FontSize", 8);
  end
  text(axesHandle, 0.015, 0.94, sprintf("(%c) %.2f%% | %.2f mm", ...
    panelLetters(sampleIndex), catalog.cold_reduction_percent(sampleIndex), ...
    catalog.diameter_mm(sampleIndex)), "Units", "normalized", ...
    "HorizontalAlignment", "left", "VerticalAlignment", "top", ...
    "FontName", "Arial", "FontSize", 7.5, "FontWeight", "bold");
  text(axesHandle, 0.985, 0.91, sprintf("Mean ECD = %.2f um", ...
    summary.(meanVariable)(sampleIndex)), "Units", "normalized", ...
    "HorizontalAlignment", "right", "VerticalAlignment", "top", ...
    "FontName", "Arial", "FontSize", 7.5, ...
    "Color", colorOrder(sampleIndex, :), "FontWeight", "bold");
  if sampleIndex == 1
    legend(axesHandle, [bars fitLine], ...
      ["Histogram", "Descriptive lognormal fit"], ...
      "Location", "southeast", "FontName", "Arial", ...
      "FontSize", 6.5, "Box", "off");
  end
end
title(layout, figureTitle + ...
  " | raw EBSD; 15 deg HAGB; minPixel = 5", ...
  "FontName", "Arial", "FontSize", 9, "FontWeight", "bold");
exportgraphics(figureHandle, pngPath, "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, tifPath, "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, pdfPath, "ContentType", "vector", ...
  "BackgroundColor", "white");
clear cleanupFigure
end

function [mu, sigma] = weighted_log_parameters(values, weights)
values = double(values(:));
weights = double(weights(:));
valid = isfinite(values) & values > 0 & isfinite(weights) & weights > 0;
values = values(valid);
weights = weights(valid);
weights = weights / sum(weights);
logValues = log(values);
mu = sum(weights .* logValues);
sigma = sqrt(sum(weights .* (logValues - mu).^2));
sigma = max(sigma, sqrt(eps));
end

function density = lognormal_pdf(values, mu, sigma)
values = double(values);
density = exp(-0.5 * ((log(values) - mu) / sigma).^2) ./ ...
  (values * sigma * sqrt(2 * pi));
end

function q = weighted_quantile(values, weights, probability)
values = double(values(:));
weights = double(weights(:));
valid = isfinite(values) & isfinite(weights) & weights > 0;
values = values(valid);
weights = weights(valid);
[values, order] = sort(values);
weights = weights(order);
index = find(cumsum(weights) >= probability * sum(weights), 1);
q = values(index);
end
