function [distribution, summary] = generate_family_schmid_distribution( ...
  scanRoot, outputRoot, plotSpec)
%GENERATE_FAMILY_SCHMID_DISTRIBUTION Plot area-weighted family SF data.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
  plotSpec (1,1) struct
end

requiredFields = ["target_family", "display_name", "file_stem", ...
  "system_description", "interpretive_limit"];
assert(all(isfield(plotSpec, cellstr(requiredFields))), ...
  "plotSpec is missing one or more required fields.");
targetFamily = string(plotSpec.target_family);
displayName = string(plotSpec.display_name);
fileStem = string(plotSpec.file_stem);
systemDescription = string(plotSpec.system_description);
interpretiveLimit = string(plotSpec.interpretive_limit);
assert(all(strlength([targetFamily, displayName, fileStem, ...
  systemDescription, interpretiveLimit]) > 0));
assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

contract = comprehensive_ebsd_output_contract();
catalog = comprehensive_ebsd_catalog(scanRoot);
reconstructionOptions = struct( ...
  "detection_threshold_deg", ...
  contract.parameters.primary_grain_detection_deg, ...
  "min_grain_pixels", contract.parameters.min_grain_pixels);
binEdges = (0:0.02:0.50)';
binLeft = binEdges(1:end-1);
binRight = binEdges(2:end);
binCenter = (binLeft + binRight) / 2;

distribution = table();
summary = table();
for scanIndex = 1:height(catalog)
  catalogRow = catalog(scanIndex, :);
  fprintf("FAMILY_SF family=%s sample=%s variant=%s\n", ...
    targetFamily, catalogRow.sample, catalogRow.variant);
  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalogRow);
  [grains, ~, ~] = reconstruct_comprehensive_grains( ...
    ebsdFull, reconstructionOptions);
  retained = grains("Ti-Hex");
  retained = retained(retained.numPixel >= ...
    reconstructionOptions.min_grain_pixels);
  assert(~isempty(retained), ...
    "No retained Ti-Hex grains for %s %s.", ...
    catalogRow.sample, catalogRow.variant);

  [scanByGrain, scanSummary] = compute_axial_propensity_metrics( ...
    retained.meanOrientation, double(retained.id(:)), ...
    double(area(retained)));
  scanByGrain = scanByGrain(scanByGrain.family == targetFamily, :);
  scanSummary = scanSummary(scanSummary.family == targetFamily, :);
  assert(height(scanSummary) == 1 && ~isempty(scanByGrain), ...
    "Requested family was not produced: %s", targetFamily);

  binIndex = discretize(scanByGrain.max_abs_schmid, binEdges);
  assert(all(isfinite(binIndex)), ...
    "One or more Schmid factors lie outside the configured bins.");
  areaWeightedFrequencyPercent = 100 * accumarray( ...
    binIndex, scanByGrain.area_weight, [numel(binCenter), 1], ...
    @sum, 0);
  assert(abs(sum(areaWeightedFrequencyPercent) - 100) < 1e-8);

  nBins = numel(binCenter);
  scanDistribution = table( ...
    repmat(catalogRow.sample, nBins, 1), ...
    repmat(catalogRow.diameter_mm, nBins, 1), ...
    repmat(catalogRow.cold_reduction_percent, nBins, 1), ...
    repmat(catalogRow.variant, nBins, 1), ...
    repmat(targetFamily, nBins, 1), ...
    binLeft, binRight, binCenter, areaWeightedFrequencyPercent, ...
    'VariableNames', {'sample', 'diameter_mm', ...
    'cold_reduction_percent', 'variant', 'family', ...
    'bin_left', 'bin_right', 'bin_center', ...
    'area_weighted_frequency_percent'});
  scanSummary = add_scan_columns(scanSummary, catalogRow);

  if scanIndex == 1
    distribution = scanDistribution;
    summary = scanSummary;
  else
    distribution = [distribution; scanDistribution]; %#ok<AGROW>
    summary = [summary; scanSummary]; %#ok<AGROW>
  end
  clear ebsdFull grains retained scanByGrain scanSummary
end

assert(height(distribution) == height(catalog) * (numel(binEdges) - 1));
assert(height(summary) == height(catalog));
writetable(distribution, fullfile(outputRoot, ...
  fileStem + "_distribution.csv"));
writetable(summary, fullfile(outputRoot, fileStem + "_summary.csv"));
write_parameters(outputRoot, fileStem, targetFamily, ...
  systemDescription, interpretiveLimit, reconstructionOptions, binEdges);
plot_distribution(distribution, summary, outputRoot, fileStem, displayName);
end

function output = add_scan_columns(input, catalogRow)
nRows = height(input);
output = addvars(input, ...
  repmat(catalogRow.sample, nRows, 1), ...
  repmat(catalogRow.diameter_mm, nRows, 1), ...
  repmat(catalogRow.cold_reduction_percent, nRows, 1), ...
  repmat(catalogRow.variant, nRows, 1), ...
  'Before', 1, 'NewVariableNames', ...
  {'sample', 'diameter_mm', 'cold_reduction_percent', 'variant'});
end

function write_parameters(outputRoot, fileStem, targetFamily, ...
  systemDescription, interpretiveLimit, reconstructionOptions, binEdges)
parameter = [ ...
  "metric"; "family"; "deformation_system"; "load_geometry"; ...
  "load_axis"; "grain_value"; "weighting"; "bin_edges"; ...
  "high_factor_threshold"; "grain_detection_threshold_deg"; ...
  "minimum_grain_pixels"; "primary_input"; "sensitivity_input"; ...
  "interpretive_limit"];
value = [ ...
  "geometric absolute Schmid factor"; targetFamily; ...
  systemDescription; "uniaxial tension"; "AD (vector3d.X)"; ...
  "maximum absolute value across symmetrised variants"; ...
  "reconstructed-grain area"; "0:0.02:0.50"; "0.4"; ...
  string(reconstructionOptions.detection_threshold_deg); ...
  string(reconstructionOptions.min_grain_pixels); ...
  "raw CTF"; "denoised CTF"; interpretiveLimit];
parameters = table(parameter, value);
assert(numel(binEdges) == 26);
writetable(parameters, fullfile(outputRoot, fileStem + "_parameters.csv"));
end

function plot_distribution(distribution, summary, outputRoot, ...
  fileStem, displayName)
rawColor = [0.76 0.10 0.13];
denoisedColor = [0.16 0.16 0.16];
thresholdColor = [0.35 0.35 0.35];
stateRows = summary.variant == "raw";
states = sortrows(summary(stateRows, ...
  {'sample', 'diameter_mm', 'cold_reduction_percent'}), ...
  'cold_reduction_percent');
yMaximum = 1.18 * max(distribution.area_weighted_frequency_percent);
yMaximum = max(5, ceil(yMaximum / 5) * 5);

figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 12.2 7.7], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 3, ...
  "Padding", "compact", "TileSpacing", "compact");

for stateIndex = 1:height(states)
  axesHandle = nexttile(layout);
  hold(axesHandle, "on");
  sample = states.sample(stateIndex);
  rawRows = distribution.sample == sample & ...
    distribution.variant == "raw";
  denoisedRows = distribution.sample == sample & ...
    distribution.variant == "denoised";
  rawSummary = summary(summary.sample == sample & ...
    summary.variant == "raw", :);
  assert(sum(rawRows) == 25 && sum(denoisedRows) == 25 && ...
    height(rawSummary) == 1);

  rawBar = bar(axesHandle, distribution.bin_center(rawRows), ...
    distribution.area_weighted_frequency_percent(rawRows), 0.94, ...
    "FaceColor", rawColor, "FaceAlpha", 0.28, ...
    "EdgeColor", rawColor, "LineWidth", 0.55, ...
    "DisplayName", "Raw: area-weighted frequency");
  denoisedLine = plot(axesHandle, ...
    distribution.bin_center(denoisedRows), ...
    distribution.area_weighted_frequency_percent(denoisedRows), ...
    "--", "Color", denoisedColor, "LineWidth", 1.25, ...
    "DisplayName", "Denoised sensitivity");
  plot(axesHandle, distribution.bin_center(rawRows), ...
    distribution.area_weighted_frequency_percent(rawRows), ...
    "-", "Color", rawColor, "LineWidth", 1.6, ...
    "HandleVisibility", "off");
  thresholdLine = xline(axesHandle, 0.4, ":", ...
    "Color", thresholdColor, "LineWidth", 1.1, ...
    "DisplayName", "|m|max = 0.4");

  xlim(axesHandle, [0 0.5]);
  ylim(axesHandle, [0 yMaximum]);
  xticks(axesHandle, 0:0.1:0.5);
  grid(axesHandle, "on");
  axesHandle.GridAlpha = 0.13;
  axesHandle.Layer = "top";
  axesHandle.FontName = "Arial";
  axesHandle.FontSize = 9.2;
  axesHandle.LineWidth = 0.8;
  title(axesHandle, sprintf("(%c) %.2f%% reduction (%.2f mm)", ...
    char('a' + stateIndex - 1), ...
    states.cold_reduction_percent(stateIndex), ...
    states.diameter_mm(stateIndex)), ...
    "FontWeight", "normal", "FontSize", 10.2);
  annotationText = sprintf( ...
    "area mean = %.3f\narea median = %.3f\nA(|m|max >= 0.4) = %.1f%%", ...
    rawSummary.area_weighted_mean_max_schmid, ...
    rawSummary.area_weighted_median_max_schmid, ...
    100 * rawSummary.area_fraction_schmid_ge_0_4);
  text(axesHandle, 0.018, 0.965 * yMaximum, annotationText, ...
    "VerticalAlignment", "top", "FontName", "Arial", ...
    "FontSize", 8.2, "BackgroundColor", "white", ...
    "Margin", 2.5, "EdgeColor", [0.82 0.82 0.82], ...
    "Interpreter", "none");

  if stateIndex == 1
    legend(axesHandle, [rawBar, denoisedLine, thresholdLine], ...
      "Location", "southwest", "FontSize", 7.5, ...
      "Box", "off", "Interpreter", "none");
  end
end

xlabel(layout, "Maximum absolute Schmid factor, |m|max", ...
  "FontName", "Arial", "FontSize", 11, "Interpreter", "none");
ylabel(layout, "Area-weighted frequency (%)", ...
  "FontName", "Arial", "FontSize", 11);
title(layout, displayName + ...
  " Schmid-factor distributions under AD tension", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold", ...
  "Interpreter", "none");
subtitle(layout, ...
  "Maximum across variants; raw CTF is primary and denoised CTF is a sensitivity check", ...
  "FontName", "Arial", "FontSize", 9.5);
drawnow;

figureStem = fullfile(outputRoot, fileStem + "_distribution_6state");
exportgraphics(figureHandle, figureStem + ".png", "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".pdf", ...
  "ContentType", "vector", "BackgroundColor", "white");
clear cleanupFigure
end
