function [distribution, summary] = generate_prismatic_schmid_distribution( ...
  scanRoot, outputRoot)
%GENERATE_PRISMATIC_SCHMID_DISTRIBUTION Prismatic <a> SF wrapper.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

plotSpec = struct( ...
  "target_family", "prismatic_a", ...
  "display_name", "Prismatic <a> slip", ...
  "file_stem", "prismatic_a_schmid", ...
  "system_description", ...
  "MTEX slipSystem.prismaticA (prismatic <a> slip family)", ...
  "interpretive_limit", ...
  "no CRSS, local-stress, or slip-activity claim");
[distribution, summary] = generate_family_schmid_distribution( ...
  scanRoot, outputRoot, plotSpec);
end
