function outputs = generate_schmid_statistical_sensitivity( ...
  scanRoot, outputRoot)
%GENERATE_SCHMID_STATISTICAL_SENSITIVITY Compare Schmid statistics.
%
% This analysis deliberately reports several fixed statistical views rather
% than selecting a threshold after inspecting the result. Per retained
% reconstructed grain, each family value is the maximum absolute Schmid
% factor across all symmetrised variants under AD uniaxial tension.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

contract = comprehensive_ebsd_output_contract();
catalog = comprehensive_ebsd_catalog(scanRoot);
reconstructionOptions = struct( ...
  "detection_threshold_deg", ...
  contract.parameters.primary_grain_detection_deg, ...
  "min_grain_pixels", contract.parameters.min_grain_pixels);

families = ["prismatic_a"; "basal_a"; "pyramidal_ca"];
displayNames = ["Prismatic <a>"; "Basal <a>"; ...
  "Pyramidal <c+a>"];
crssMPa = [154; 252; 756];
sfThresholds = [0.30; 0.34; 0.38; 0.40; 0.42; 0.44; 0.46; 0.48];
ratioThresholds = [0.15; 0.20; 0.25; 0.30; 0.40; 0.50; 0.75; 1.00];

summary = table();
thresholdSensitivity = table();
ratioSummary = table();
ratioSensitivity = table();
preferredFamily = table();

for scanIndex = 1:height(catalog)
  catalogRow = catalog(scanIndex, :);
  fprintf("SCHMID_SENSITIVITY sample=%s variant=%s\n", ...
    catalogRow.sample, catalogRow.variant);
  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalogRow);
  [grains, ~, ~] = reconstruct_comprehensive_grains( ...
    ebsdFull, reconstructionOptions);
  retained = grains("Ti-Hex");
  retained = retained(retained.numPixel >= ...
    reconstructionOptions.min_grain_pixels);
  assert(~isempty(retained), ...
    "No retained Ti-Hex grains for %s %s.", ...
    catalogRow.sample, catalogRow.variant);

  byGrain = compute_axial_propensity_metrics( ...
    retained.meanOrientation, double(retained.id(:)), ...
    double(area(retained)));
  [schmid, grainIds, areaWeights] = align_family_values( ...
    byGrain, families);
  nGrains = numel(grainIds);

  for familyIndex = 1:numel(families)
    values = schmid(:, familyIndex);
    activationStress = crssMPa(familyIndex) ./ values;
    q05 = weighted_quantile(values, areaWeights, 0.05);
    q95 = weighted_quantile(values, areaWeights, 0.95);
    trimmed = values >= q05 & values <= q95;
    trimmedWeights = areaWeights(trimmed);
    trimmedWeights = trimmedWeights / sum(trimmedWeights);

    scanRow = table( ...
      catalogRow.sample, catalogRow.diameter_mm, ...
      catalogRow.cold_reduction_percent, catalogRow.variant, ...
      families(familyIndex), displayNames(familyIndex), ...
      crssMPa(familyIndex), nGrains, mean(values), ...
      sum(areaWeights .* values), median(values), ...
      weighted_quantile(values, areaWeights, 0.10), ...
      weighted_quantile(values, areaWeights, 0.25), ...
      weighted_quantile(values, areaWeights, 0.50), ...
      weighted_quantile(values, areaWeights, 0.75), ...
      weighted_quantile(values, areaWeights, 0.90), q95, ...
      sum(trimmedWeights .* values(trimmed)), ...
      100 * mean(values >= 0.40), ...
      100 * sum(areaWeights(values >= 0.40)), ...
      sum(areaWeights .* values) / crssMPa(familyIndex), ...
      weighted_quantile(activationStress, areaWeights, 0.25), ...
      weighted_quantile(activationStress, areaWeights, 0.50), ...
      weighted_quantile(activationStress, areaWeights, 0.75), ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'family', 'display_name', ...
      'source_crss_mpa', 'grain_count', 'count_weighted_mean_schmid', ...
      'area_weighted_mean_schmid', 'count_weighted_median_schmid', ...
      'area_weighted_q10_schmid', 'area_weighted_q25_schmid', ...
      'area_weighted_median_schmid', 'area_weighted_q75_schmid', ...
      'area_weighted_q90_schmid', 'area_weighted_q95_schmid', ...
      'area_weighted_trimmed_mean_q05_q95_schmid', ...
      'count_fraction_schmid_ge_0_40_percent', ...
      'area_fraction_schmid_ge_0_40_percent', ...
      'area_weighted_mean_drive_per_mpa', ...
      'area_weighted_q25_activation_stress_mpa', ...
      'area_weighted_median_activation_stress_mpa', ...
      'area_weighted_q75_activation_stress_mpa'});
    summary = append_table(summary, scanRow);

    for thresholdIndex = 1:numel(sfThresholds)
      threshold = sfThresholds(thresholdIndex);
      selected = values >= threshold;
      selectedCount = nnz(selected);
      if selectedCount == 0
        conditionalCountMean = NaN;
        conditionalAreaMean = NaN;
      else
        conditionalCountMean = mean(values(selected));
        conditionalWeights = areaWeights(selected);
        conditionalWeights = conditionalWeights / sum(conditionalWeights);
        conditionalAreaMean = sum(conditionalWeights .* values(selected));
      end
      thresholdRow = table( ...
        catalogRow.sample, catalogRow.diameter_mm, ...
        catalogRow.cold_reduction_percent, catalogRow.variant, ...
        families(familyIndex), displayNames(familyIndex), threshold, ...
        nGrains, selectedCount, 100 * mean(selected), ...
        100 * sum(areaWeights(selected)), conditionalCountMean, ...
        conditionalAreaMean, ...
        'VariableNames', {'sample', 'diameter_mm', ...
        'cold_reduction_percent', 'variant', 'family', 'display_name', ...
        'schmid_threshold', 'grain_count', 'selected_grain_count', ...
        'selected_grain_count_percent', 'selected_grain_area_percent', ...
        'conditional_count_mean_schmid', ...
        'conditional_area_mean_schmid'});
      thresholdSensitivity = append_table( ...
        thresholdSensitivity, thresholdRow);
    end
  end

  drive = schmid ./ crssMPa';
  bestADrive = max(drive(:, 1:2), [], 2);
  ratios = [drive(:, 3) ./ bestADrive, ...
    drive(:, 2) ./ drive(:, 1)];
  ratioNames = ["ca_to_best_a"; "basal_to_prismatic"];
  for ratioIndex = 1:numel(ratioNames)
    values = ratios(:, ratioIndex);
    ratioRow = table( ...
      catalogRow.sample, catalogRow.diameter_mm, ...
      catalogRow.cold_reduction_percent, catalogRow.variant, ...
      ratioNames(ratioIndex), nGrains, mean(values), ...
      sum(areaWeights .* values), ...
      weighted_quantile(values, areaWeights, 0.10), ...
      weighted_quantile(values, areaWeights, 0.25), ...
      weighted_quantile(values, areaWeights, 0.50), ...
      weighted_quantile(values, areaWeights, 0.75), ...
      weighted_quantile(values, areaWeights, 0.90), ...
      weighted_quantile(values, areaWeights, 0.95), max(values), ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'ratio_name', ...
      'grain_count', 'count_weighted_mean_ratio', ...
      'area_weighted_mean_ratio', 'area_weighted_q10_ratio', ...
      'area_weighted_q25_ratio', 'area_weighted_median_ratio', ...
      'area_weighted_q75_ratio', 'area_weighted_q90_ratio', ...
      'area_weighted_q95_ratio', 'maximum_ratio'});
    ratioSummary = append_table(ratioSummary, ratioRow);

    for thresholdIndex = 1:numel(ratioThresholds)
      threshold = ratioThresholds(thresholdIndex);
      selected = values >= threshold;
      ratioThresholdRow = table( ...
        catalogRow.sample, catalogRow.diameter_mm, ...
        catalogRow.cold_reduction_percent, catalogRow.variant, ...
        ratioNames(ratioIndex), threshold, nGrains, nnz(selected), ...
        100 * mean(selected), 100 * sum(areaWeights(selected)), ...
        'VariableNames', {'sample', 'diameter_mm', ...
        'cold_reduction_percent', 'variant', 'ratio_name', ...
        'ratio_threshold', 'grain_count', 'selected_grain_count', ...
        'selected_grain_count_percent', 'selected_grain_area_percent'});
      ratioSensitivity = append_table( ...
        ratioSensitivity, ratioThresholdRow);
    end
  end

  [~, preferredIndex] = max(drive, [], 2);
  for familyIndex = 1:numel(families)
    selected = preferredIndex == familyIndex;
    familyRow = table( ...
      catalogRow.sample, catalogRow.diameter_mm, ...
      catalogRow.cold_reduction_percent, catalogRow.variant, ...
      families(familyIndex), displayNames(familyIndex), ...
      nGrains, nnz(selected), 100 * mean(selected), ...
      100 * sum(areaWeights(selected)), ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'preferred_family', ...
      'display_name', 'grain_count', 'preferred_grain_count', ...
      'preferred_grain_count_percent', 'preferred_grain_area_percent'});
    preferredFamily = append_table(preferredFamily, familyRow);
  end

  clear ebsdFull grains retained byGrain schmid grainIds areaWeights
end

summary = sortrows(summary, ...
  {'cold_reduction_percent', 'variant', 'source_crss_mpa'});
thresholdSensitivity = sortrows(thresholdSensitivity, ...
  {'cold_reduction_percent', 'variant', 'family', 'schmid_threshold'});
ratioSummary = sortrows(ratioSummary, ...
  {'cold_reduction_percent', 'variant', 'ratio_name'});
ratioSensitivity = sortrows(ratioSensitivity, ...
  {'cold_reduction_percent', 'variant', 'ratio_name', 'ratio_threshold'});
preferredFamily = sortrows(preferredFamily, ...
  {'cold_reduction_percent', 'variant', 'preferred_family'});

initialFinal = build_initial_final_comparison( ...
  summary, thresholdSensitivity, ratioSummary, ratioSensitivity, families);

writetable(summary, fullfile(outputRoot, ...
  "schmid_statistical_summary.csv"));
writetable(thresholdSensitivity, fullfile(outputRoot, ...
  "schmid_threshold_sensitivity.csv"));
writetable(ratioSummary, fullfile(outputRoot, ...
  "crss_competition_ratio_summary.csv"));
writetable(ratioSensitivity, fullfile(outputRoot, ...
  "crss_competition_threshold_sensitivity.csv"));
writetable(preferredFamily, fullfile(outputRoot, ...
  "crss_preferred_family_summary.csv"));
writetable(initialFinal, fullfile(outputRoot, ...
  "initial_final_method_comparison.csv"));
write_parameters(outputRoot, reconstructionOptions, sfThresholds, ...
  ratioThresholds, crssMPa);
plot_sensitivity(summary, thresholdSensitivity, ratioSummary, ...
  outputRoot, families, displayNames);
plot_initial_final_ccdf(thresholdSensitivity, outputRoot, families, ...
  displayNames);

outputs = struct();
outputs.summary = summary;
outputs.threshold_sensitivity = thresholdSensitivity;
outputs.ratio_summary = ratioSummary;
outputs.ratio_sensitivity = ratioSensitivity;
outputs.preferred_family = preferredFamily;
outputs.initial_final = initialFinal;
end

function [schmid, grainIds, areaWeights] = ...
  align_family_values(byGrain, families)
familyTables = cell(numel(families), 1);
for familyIndex = 1:numel(families)
  rows = byGrain.family == families(familyIndex);
  familyTables{familyIndex} = sortrows( ...
    byGrain(rows, {'grain_id', 'max_abs_schmid', ...
    'area_weight'}), 'grain_id');
end
grainIds = familyTables{1}.grain_id;
areaWeights = familyTables{1}.area_weight;
areaWeights = areaWeights / sum(areaWeights);
schmid = zeros(numel(grainIds), numel(families));
for familyIndex = 1:numel(families)
  current = familyTables{familyIndex};
  assert(isequal(current.grain_id, grainIds), ...
    "Grain IDs do not align across slip families.");
  assert(max(abs(current.area_weight - familyTables{1}.area_weight)) ...
    < 1e-12, "Grain area weights do not align across slip families.");
  schmid(:, familyIndex) = current.max_abs_schmid;
end
assert(all(isfinite(schmid) & schmid > 0 & schmid <= 0.5 + 1e-10, ...
  "all"));
end

function comparison = build_initial_final_comparison( ...
  summary, thresholdSensitivity, ratioSummary, ratioSensitivity, families)
comparison = table();
summaryMethods = [ ...
  "count_weighted_mean_schmid"; ...
  "area_weighted_mean_schmid"; ...
  "count_weighted_median_schmid"; ...
  "area_weighted_median_schmid"; ...
  "area_weighted_q90_schmid"; ...
  "area_weighted_q95_schmid"; ...
  "area_weighted_trimmed_mean_q05_q95_schmid"];
for variant = ["raw", "denoised"]
  for familyIndex = 1:numel(families)
    initialRow = summary(summary.sample == "7d" & ...
      summary.variant == variant & summary.family == families(familyIndex), :);
    finalRow = summary(summary.sample == "5d" & ...
      summary.variant == variant & summary.family == families(familyIndex), :);
    assert(height(initialRow) == 1 && height(finalRow) == 1);
    for methodIndex = 1:numel(summaryMethods)
      method = summaryMethods(methodIndex);
      comparison = append_comparison(comparison, variant, ...
        "schmid_location", families(familyIndex), method, NaN, ...
        initialRow.(char(method)), finalRow.(char(method)), ...
        "schmid_factor");
    end
    for threshold = [0.40, 0.44, 0.46, 0.48]
      initialThreshold = thresholdSensitivity( ...
        thresholdSensitivity.sample == "7d" & ...
        thresholdSensitivity.variant == variant & ...
        thresholdSensitivity.family == families(familyIndex) & ...
        abs(thresholdSensitivity.schmid_threshold - threshold) < 1e-12, :);
      finalThreshold = thresholdSensitivity( ...
        thresholdSensitivity.sample == "5d" & ...
        thresholdSensitivity.variant == variant & ...
        thresholdSensitivity.family == families(familyIndex) & ...
        abs(thresholdSensitivity.schmid_threshold - threshold) < 1e-12, :);
      assert(height(initialThreshold) == 1 && height(finalThreshold) == 1);
      comparison = append_comparison(comparison, variant, ...
        "schmid_tail", families(familyIndex), ...
        "area_fraction_schmid_ge_threshold", threshold, ...
        initialThreshold.selected_grain_area_percent, ...
        finalThreshold.selected_grain_area_percent, "percentage_points");
      comparison = append_comparison(comparison, variant, ...
        "schmid_tail", families(familyIndex), ...
        "conditional_area_mean_schmid", threshold, ...
        initialThreshold.conditional_area_mean_schmid, ...
        finalThreshold.conditional_area_mean_schmid, "schmid_factor");
    end
  end

  for ratioName = ["ca_to_best_a", "basal_to_prismatic"]
    initialRatio = ratioSummary(ratioSummary.sample == "7d" & ...
      ratioSummary.variant == variant & ...
      ratioSummary.ratio_name == ratioName, :);
    finalRatio = ratioSummary(ratioSummary.sample == "5d" & ...
      ratioSummary.variant == variant & ...
      ratioSummary.ratio_name == ratioName, :);
    assert(height(initialRatio) == 1 && height(finalRatio) == 1);
    for method = ["area_weighted_mean_ratio", ...
        "area_weighted_median_ratio", "area_weighted_q90_ratio", ...
        "area_weighted_q95_ratio"]
      comparison = append_comparison(comparison, variant, ...
        "crss_competition", ratioName, method, NaN, ...
        initialRatio.(char(method)), finalRatio.(char(method)), "ratio");
    end
    for threshold = [0.20, 0.25, 0.30, 0.50, 1.00]
      initialThreshold = ratioSensitivity( ...
        ratioSensitivity.sample == "7d" & ...
        ratioSensitivity.variant == variant & ...
        ratioSensitivity.ratio_name == ratioName & ...
        abs(ratioSensitivity.ratio_threshold - threshold) < 1e-12, :);
      finalThreshold = ratioSensitivity( ...
        ratioSensitivity.sample == "5d" & ...
        ratioSensitivity.variant == variant & ...
        ratioSensitivity.ratio_name == ratioName & ...
        abs(ratioSensitivity.ratio_threshold - threshold) < 1e-12, :);
      assert(height(initialThreshold) == 1 && height(finalThreshold) == 1);
      comparison = append_comparison(comparison, variant, ...
        "crss_competition_tail", ratioName, ...
        "area_fraction_ratio_ge_threshold", threshold, ...
        initialThreshold.selected_grain_area_percent, ...
        finalThreshold.selected_grain_area_percent, "percentage_points");
    end
  end
end
end

function output = append_comparison(input, variant, metricGroup, target, ...
  method, threshold, initialValue, finalValue, unit)
absoluteChange = finalValue - initialValue;
if isfinite(initialValue) && abs(initialValue) > eps
  relativeChangePercent = 100 * absoluteChange / initialValue;
else
  relativeChangePercent = NaN;
end
row = table(variant, metricGroup, target, method, threshold, ...
  initialValue, finalValue, absoluteChange, relativeChangePercent, unit, ...
  'VariableNames', {'variant', 'metric_group', 'target', 'method', ...
  'threshold', 'initial_7d', 'final_5d', 'absolute_change', ...
  'relative_change_percent', 'unit'});
output = append_table(input, row);
end

function output = append_table(input, row)
if isempty(input)
  output = row;
else
  output = [input; row];
end
end

function result = weighted_quantile(values, weights, probability)
assert(isscalar(probability) && probability >= 0 && probability <= 1);
[sortedValues, order] = sort(values);
sortedWeights = weights(order) / sum(weights);
result = sortedValues(find(cumsum(sortedWeights) >= probability, ...
  1, "first"));
end

function write_parameters(outputRoot, reconstructionOptions, ...
  sfThresholds, ratioThresholds, crssMPa)
parameter = [ ...
  "purpose"; "load_geometry"; "load_axis"; "grain_orientation"; ...
  "family_grain_value"; "included_families"; ...
  "schmid_thresholds"; "crss_competition_ratio"; ...
  "ratio_thresholds"; "prismatic_a_crss_mpa"; ...
  "basal_a_crss_mpa"; "pyramidal_ca_crss_mpa"; "crss_source"; ...
  "grain_detection_threshold_deg"; "minimum_grain_pixels"; ...
  "primary_input"; "sensitivity_input"; "interpretive_limit"];
value = [ ...
  "compare fixed Schmid-factor statistical definitions without post-hoc deletion"; ...
  "uniaxial tension"; "AD (vector3d.X)"; ...
  "mean orientation of each retained reconstructed Ti-Hex grain"; ...
  "maximum absolute value across all symmetrised variants"; ...
  "prismatic_a, basal_a, pyramidal_ca"; ...
  join(string(compose("%.2f", sfThresholds)), ","); ...
  "R_ca = (m_ca/756)/max(m_prismatic/154,m_basal/252)"; ...
  join(string(compose("%.2f", ratioThresholds)), ","); ...
  string(crssMPa(1)); string(crssMPa(2)); string(crssMPa(3)); ...
  "Xiong et al., Acta Materialia 199 (2020) 561-577, Table 4"; ...
  string(reconstructionOptions.detection_threshold_deg); ...
  string(reconstructionOptions.min_grain_pixels); ...
  "raw CTF"; "denoised CTF"; ...
  "geometric and fixed-CRSS screening only; thresholds are all reported as a sensitivity grid; no row is discarded from the denominator; local stress, hardening and observed Burgers vectors are unresolved"];
writetable(table(parameter, value), fullfile(outputRoot, ...
  "schmid_statistical_sensitivity_parameters.csv"));
end

function plot_sensitivity(summary, thresholdSensitivity, ratioSummary, ...
  outputRoot, families, displayNames)
colors = [0.10 0.43 0.72; 0.86 0.33 0.10; 0.45 0.24 0.65];
markers = {'o', 's', '^'};
xValues = unique(summary.cold_reduction_percent);

figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 12.0 8.1], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 2, ...
  "Padding", "compact", "TileSpacing", "compact");

axesMean = nexttile(layout);
hold(axesMean, "on");
for familyIndex = 1:numel(families)
  plot_family_variants(axesMean, summary, families(familyIndex), ...
    "area_weighted_mean_schmid", colors(familyIndex, :), ...
    markers{familyIndex}, displayNames(familyIndex));
end
format_axes(axesMean, xValues);
ylabel(axesMean, "Area-weighted mean |m|max");
title(axesMean, "(a) Mean of grain-family maxima", ...
  "FontWeight", "normal");
legend(axesMean, "Location", "southoutside", "NumColumns", 3, ...
  "Box", "off", "FontSize", 8.0);

axesQuantile = nexttile(layout);
hold(axesQuantile, "on");
for familyIndex = [1, 3]
  plot_family_variants(axesQuantile, summary, families(familyIndex), ...
    "area_weighted_q90_schmid", colors(familyIndex, :), ...
    markers{familyIndex}, displayNames(familyIndex));
end
format_axes(axesQuantile, xValues);
ylabel(axesQuantile, "Area-weighted 90th percentile |m|max");
title(axesQuantile, "(b) Upper-distribution location", ...
  "FontWeight", "normal");
legend(axesQuantile, "Location", "southoutside", "NumColumns", 2, ...
  "Box", "off", "FontSize", 8.0);

axesTail = nexttile(layout);
hold(axesTail, "on");
for familyIndex = [1, 3]
  rows = thresholdSensitivity.family == families(familyIndex) & ...
    abs(thresholdSensitivity.schmid_threshold - 0.46) < 1e-12;
  selected = thresholdSensitivity(rows, :);
  plot_family_variants(axesTail, selected, families(familyIndex), ...
    "selected_grain_area_percent", colors(familyIndex, :), ...
    markers{familyIndex}, displayNames(familyIndex));
end
format_axes(axesTail, xValues);
ylabel(axesTail, "Grain area with |m|max >= 0.46 (%)");
title(axesTail, "(c) Fixed high-tail threshold", ...
  "FontWeight", "normal");
legend(axesTail, "Location", "southoutside", "NumColumns", 2, ...
  "Box", "off", "FontSize", 8.0);

axesRatio = nexttile(layout);
hold(axesRatio, "on");
ratioRows = ratioSummary.ratio_name == "ca_to_best_a";
selected = ratioSummary(ratioRows, :);
plot_variant_metric(axesRatio, selected, ...
  "area_weighted_median_ratio", colors(3, :), 'o', ...
  "Median Rca/best-a");
plot_variant_metric(axesRatio, selected, ...
  "area_weighted_q90_ratio", colors(1, :), '^', ...
  "90th percentile Rca/best-a");
yline(axesRatio, 1, ":", "Color", [0.25 0.25 0.25], ...
  "LineWidth", 1.0, "HandleVisibility", "off");
format_axes(axesRatio, xValues);
ylabel(axesRatio, "CRSS-normalized competition ratio");
title(axesRatio, "(d) Pyramidal <c+a> relative to best <a>", ...
  "FontWeight", "normal");
legend(axesRatio, "Location", "southoutside", "NumColumns", 2, ...
  "Box", "off", "FontSize", 8.0);

xlabel(layout, "Cold reduction (%)");
title(layout, "Schmid-factor statistical sensitivity under AD tension", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold");
subtitle(layout, ...
  "Solid: raw EBSD; dashed: denoised sensitivity; no threshold-selected rows are deleted", ...
  "FontName", "Arial", "FontSize", 9.2);
drawnow;

figureStem = fullfile(outputRoot, ...
  "schmid_statistical_sensitivity_6state");
exportgraphics(figureHandle, figureStem + ".png", ...
  "Resolution", 600, "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", ...
  "Resolution", 600, "BackgroundColor", "white");
clear cleanupFigure
end

function plot_family_variants(axesHandle, input, family, metric, ...
  color, marker, label)
rows = input.family == family;
selected = input(rows, :);
plot_variant_metric(axesHandle, selected, metric, color, marker, label);
end

function plot_variant_metric(axesHandle, input, metric, color, marker, label)
raw = sortrows(input(input.variant == "raw", :), ...
  "cold_reduction_percent");
denoised = sortrows(input(input.variant == "denoised", :), ...
  "cold_reduction_percent");
assert(height(raw) == 6 && height(denoised) == 6);
plot(axesHandle, raw.cold_reduction_percent, raw.(char(metric)), ...
  ['-' marker], "Color", color, "LineWidth", 1.55, ...
  "MarkerSize", 5.8, "MarkerFaceColor", color, ...
  "DisplayName", label);
plot(axesHandle, denoised.cold_reduction_percent, ...
  denoised.(char(metric)), ...
  ['--' marker], "Color", color, "LineWidth", 1.0, ...
  "MarkerSize", 5.0, "MarkerFaceColor", "white", ...
  "HandleVisibility", "off");
end

function plot_initial_final_ccdf(thresholdSensitivity, outputRoot, ...
  families, displayNames)
colors = [0.10 0.43 0.72; 0.45 0.24 0.65];
targetIndices = [1, 3];
figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 10.8 4.6], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 1, 2, ...
  "Padding", "compact", "TileSpacing", "compact");
for panelIndex = 1:2
  familyIndex = targetIndices(panelIndex);
  axesHandle = nexttile(layout);
  hold(axesHandle, "on");
  for variantIndex = 1:2
    variant = ["raw", "denoised"];
    lineStyle = ["-", "--"];
    for stateIndex = 1:2
      sample = ["7d", "5d"];
      marker = {'o', '^'};
      rows = thresholdSensitivity.family == families(familyIndex) & ...
        thresholdSensitivity.variant == variant(variantIndex) & ...
        thresholdSensitivity.sample == sample(stateIndex);
      selected = sortrows(thresholdSensitivity(rows, :), ...
        "schmid_threshold");
      assert(height(selected) == 8);
      visibility = "on";
      if variantIndex == 2
        visibility = "off";
      end
      lineSpec = char(lineStyle(variantIndex) + ...
        string(marker{stateIndex}));
      plot(axesHandle, selected.schmid_threshold, ...
        selected.selected_grain_area_percent, ...
        lineSpec, ...
        "Color", colors(stateIndex, :), "LineWidth", 1.4, ...
        "MarkerSize", 5.0, "MarkerFaceColor", ...
        colors(stateIndex, :), "HandleVisibility", visibility, ...
        "DisplayName", sample(stateIndex));
    end
  end
  xlim(axesHandle, [0.30 0.48]);
  xticks(axesHandle, 0.30:0.02:0.48);
  grid(axesHandle, "on");
  axesHandle.GridAlpha = 0.13;
  axesHandle.FontName = "Arial";
  axesHandle.FontSize = 9;
  xlabel(axesHandle, "Schmid threshold, mc");
  ylabel(axesHandle, "Grain area with |m|max >= mc (%)");
  title(axesHandle, displayNames(familyIndex), ...
    "FontWeight", "normal");
  legend(axesHandle, "Location", "southwest", "Box", "off");
end
title(layout, "Initial-final complementary threshold distributions", ...
  "FontName", "Arial", "FontSize", 12.5, "FontWeight", "bold");
subtitle(layout, "Solid: raw EBSD; dashed: denoised sensitivity", ...
  "FontName", "Arial", "FontSize", 9.2);
drawnow;
figureStem = fullfile(outputRoot, "schmid_initial_final_ccdf");
exportgraphics(figureHandle, figureStem + ".png", ...
  "Resolution", 600, "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", ...
  "Resolution", 600, "BackgroundColor", "white");
clear cleanupFigure
end

function format_axes(axesHandle, xValues)
xlim(axesHandle, [min(xValues) - 2, max(xValues) + 2]);
xticks(axesHandle, xValues);
xticklabels(axesHandle, compose("%.2f", xValues));
grid(axesHandle, "on");
axesHandle.GridAlpha = 0.13;
axesHandle.Layer = "top";
axesHandle.FontName = "Arial";
axesHandle.FontSize = 9.0;
axesHandle.LineWidth = 0.8;
end
