function summary = generate_crss_normalized_slip_resistance( ...
  scanRoot, outputRoot)
%GENERATE_CRSS_NORMALIZED_SLIP_RESISTANCE Estimate family activation stress.
%
% For each reconstructed grain and slip family, this calculation uses
% sigma_act = CRSS / max(|m|) under AD uniaxial tension. The literature
% CRSS values are fixed across project states; only the measured grain
% orientations and grain-area weights vary between states.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

contract = comprehensive_ebsd_output_contract();
catalog = comprehensive_ebsd_catalog(scanRoot);
reconstructionOptions = struct( ...
  "detection_threshold_deg", ...
  contract.parameters.primary_grain_detection_deg, ...
  "min_grain_pixels", contract.parameters.min_grain_pixels);

families = ["prismatic_a"; "basal_a"; "pyramidal_ca"];
displayNames = ["Prismatic <a>"; "Basal <a>"; ...
  "Pyramidal <c+a>"];
crssMPa = [154; 252; 756];
relativeCrss = crssMPa / crssMPa(1);

summary = table();
for scanIndex = 1:height(catalog)
  catalogRow = catalog(scanIndex, :);
  fprintf("CRSS_RESISTANCE sample=%s variant=%s\n", ...
    catalogRow.sample, catalogRow.variant);
  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalogRow);
  [grains, ~, ~] = reconstruct_comprehensive_grains( ...
    ebsdFull, reconstructionOptions);
  retained = grains("Ti-Hex");
  retained = retained(retained.numPixel >= ...
    reconstructionOptions.min_grain_pixels);
  assert(~isempty(retained), ...
    "No retained Ti-Hex grains for %s %s.", ...
    catalogRow.sample, catalogRow.variant);

  byGrain = compute_axial_propensity_metrics( ...
    retained.meanOrientation, double(retained.id(:)), ...
    double(area(retained)));
  for familyIndex = 1:numel(families)
    familyRows = byGrain.family == families(familyIndex);
    values = byGrain.max_abs_schmid(familyRows);
    weights = byGrain.area_weight(familyRows);
    assert(~isempty(values) && all(isfinite(values) & values > 0) && ...
      all(isfinite(weights) & weights > 0));
    weights = weights / sum(weights);
    activationStress = crssMPa(familyIndex) ./ values;
    meanSchmid = sum(weights .* values);

    scanRow = table( ...
      catalogRow.sample, catalogRow.diameter_mm, ...
      catalogRow.cold_reduction_percent, catalogRow.variant, ...
      families(familyIndex), displayNames(familyIndex), ...
      crssMPa(familyIndex), relativeCrss(familyIndex), ...
      numel(values), meanSchmid, weighted_quantile(values, weights, 0.5), ...
      crssMPa(familyIndex) / meanSchmid, ...
      weighted_quantile(activationStress, weights, 0.25), ...
      weighted_quantile(activationStress, weights, 0.50), ...
      weighted_quantile(activationStress, weights, 0.75), ...
      meanSchmid / crssMPa(familyIndex), NaN, ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'family', 'display_name', ...
      'source_crss_mpa', 'source_crss_relative_to_prismatic', ...
      'grain_count', 'area_weighted_mean_max_schmid', ...
      'area_weighted_median_max_schmid', ...
      'nominal_activation_stress_from_mean_schmid_mpa', ...
      'area_weighted_q25_grain_activation_stress_mpa', ...
      'area_weighted_median_grain_activation_stress_mpa', ...
      'area_weighted_q75_grain_activation_stress_mpa', ...
      'area_weighted_mean_driving_index_per_mpa', ...
      'relative_nominal_resistance_vs_prismatic'});
    if isempty(summary)
      summary = scanRow;
    else
      summary = [summary; scanRow]; %#ok<AGROW>
    end
  end
  clear ebsdFull grains retained byGrain
end

assert(height(summary) == height(catalog) * numel(families));
for scanIndex = 1:height(catalog)
  scanRows = summary.sample == catalog.sample(scanIndex) & ...
    summary.variant == catalog.variant(scanIndex);
  prismRow = scanRows & summary.family == "prismatic_a";
  assert(nnz(scanRows) == numel(families) && nnz(prismRow) == 1);
  prismResistance = summary. ...
    nominal_activation_stress_from_mean_schmid_mpa(prismRow);
  summary.relative_nominal_resistance_vs_prismatic(scanRows) = ...
    summary.nominal_activation_stress_from_mean_schmid_mpa(scanRows) ./ ...
    prismResistance;
end

summary = sortrows(summary, ...
  {'cold_reduction_percent', 'variant', 'source_crss_mpa'});
writetable(summary, fullfile(outputRoot, ...
  "crss_normalized_slip_resistance_summary.csv"));
write_parameters(outputRoot, reconstructionOptions);
plot_resistance(summary, outputRoot, families, displayNames);
end

function result = weighted_quantile(values, weights, probability)
assert(isscalar(probability) && probability >= 0 && probability <= 1);
[sortedValues, order] = sort(values);
sortedWeights = weights(order) / sum(weights);
index = find(cumsum(sortedWeights) >= probability, 1, "first");
result = sortedValues(index);
end

function write_parameters(outputRoot, reconstructionOptions)
parameter = [ ...
  "metric"; "grain_equation"; "aggregate_equation"; "load_geometry"; ...
  "load_axis"; "orientation_input"; "weighting"; ...
  "grain_detection_threshold_deg"; "minimum_grain_pixels"; ...
  "prismatic_a_crss_mpa"; "basal_a_crss_mpa"; ...
  "pyramidal_ca_crss_mpa"; "crss_source"; "source_doi"; ...
  "source_material"; "source_composition"; ...
  "project_composition_relevance"; "excluded_family"; ...
  "primary_input"; "sensitivity_input"; "interpretive_limit"];
value = [ ...
  "literature-CRSS-normalized nominal activation stress"; ...
  "sigma_act = CRSS / max(abs(Schmid factor))"; ...
  "reported nominal state value = CRSS / area-weighted mean max(abs(m))"; ...
  "uniaxial tension"; "AD (vector3d.X)"; ...
  "mean orientation of each retained reconstructed Ti-Hex grain"; ...
  "reconstructed-grain area"; ...
  string(reconstructionOptions.detection_threshold_deg); ...
  string(reconstructionOptions.min_grain_pixels); ...
  "154"; "252"; "756"; ...
  "Xiong et al., Acta Materialia 199 (2020) 561-577, Table 4"; ...
  "10.1016/j.actamat.2020.08.010"; ...
  "commercially pure titanium Grade 4"; ...
  "Fe 0.05-0.055 wt.%, O 0.32 wt.%, N 0.006 wt.%"; ...
  "project O 0.326-0.339 wt.% is close; project Fe 0.367-0.370 wt.% is higher"; ...
  "pyramidal_a: source does not provide an independent CRSS"; ...
  "raw CTF"; "denoised CTF"; ...
  "screening estimate only: literature CRSS is held constant across project states; local stress, latent hardening, interaction, rate dependence and deformation-history-dependent CRSS are not resolved"];
parameters = table(parameter, value);
writetable(parameters, fullfile(outputRoot, ...
  "crss_normalized_slip_resistance_parameters.csv"));
end

function plot_resistance(summary, outputRoot, families, displayNames)
colors = [0.10 0.43 0.72; 0.86 0.33 0.10; 0.45 0.24 0.65];
markers = {'o', 's', '^'};
xValues = unique(summary.cold_reduction_percent);

figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 10.8 7.6], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 1, ...
  "Padding", "compact", "TileSpacing", "compact");

topAxes = nexttile(layout);
hold(topAxes, "on");
legendHandles = gobjects(numel(families) * 2, 1);
legendLabels = strings(numel(families) * 2, 1);
for familyIndex = 1:numel(families)
  rawRows = summary.family == families(familyIndex) & ...
    summary.variant == "raw";
  denoisedRows = summary.family == families(familyIndex) & ...
    summary.variant == "denoised";
  raw = sortrows(summary(rawRows, :), "cold_reduction_percent");
  denoised = sortrows(summary(denoisedRows, :), ...
    "cold_reduction_percent");
  assert(height(raw) == numel(xValues) && height(denoised) == numel(xValues));

  medianValues = raw.area_weighted_median_grain_activation_stress_mpa;
  lowerError = medianValues - ...
    raw.area_weighted_q25_grain_activation_stress_mpa;
  upperError = raw.area_weighted_q75_grain_activation_stress_mpa - ...
    medianValues;
  legendHandles(2 * familyIndex - 1) = errorbar(topAxes, ...
    raw.cold_reduction_percent, medianValues, lowerError, upperError, ...
    ['-' markers{familyIndex}], "Color", colors(familyIndex, :), ...
    "LineWidth", 1.55, "MarkerSize", 6.0, ...
    "MarkerFaceColor", colors(familyIndex, :));
  legendLabels(2 * familyIndex - 1) = displayNames(familyIndex) + ...
    " (raw, median + IQR)";
  legendHandles(2 * familyIndex) = plot(topAxes, ...
    denoised.cold_reduction_percent, ...
    denoised.area_weighted_median_grain_activation_stress_mpa, ...
    ['--' markers{familyIndex}], "Color", colors(familyIndex, :), ...
    "LineWidth", 1.0, "MarkerSize", 5.0, ...
    "MarkerFaceColor", "white");
  legendLabels(2 * familyIndex) = displayNames(familyIndex) + ...
    " (denoised)";
end
format_axes(topAxes, xValues);
topAxes.YScale = "log";
ylim(topAxes, [250 4200]);
yticks(topAxes, [300 500 1000 2000 4000]);
yticklabels(topAxes, {'300', '500', '1000', '2000', '4000'});
ylabel(topAxes, "Grainwise nominal activation stress (MPa)", ...
  "FontName", "Arial");
legend(topAxes, legendHandles, cellstr(legendLabels), ...
  "Location", "northoutside", "NumColumns", 2, ...
  "FontSize", 8.0, "Box", "off");
title(topAxes, ...
  "Area-weighted median; error bars are the 25th-75th percentiles", ...
  "FontWeight", "normal", "FontSize", 9.5);

bottomAxes = nexttile(layout);
hold(bottomAxes, "on");
for familyIndex = 1:numel(families)
  rawRows = summary.family == families(familyIndex) & ...
    summary.variant == "raw";
  denoisedRows = summary.family == families(familyIndex) & ...
    summary.variant == "denoised";
  raw = sortrows(summary(rawRows, :), "cold_reduction_percent");
  denoised = sortrows(summary(denoisedRows, :), ...
    "cold_reduction_percent");
  plot(bottomAxes, raw.cold_reduction_percent, ...
    raw.relative_nominal_resistance_vs_prismatic, ...
    ['-' markers{familyIndex}], "Color", colors(familyIndex, :), ...
    "LineWidth", 1.55, "MarkerSize", 6.0, ...
    "MarkerFaceColor", colors(familyIndex, :), ...
    "DisplayName", displayNames(familyIndex));
  plot(bottomAxes, denoised.cold_reduction_percent, ...
    denoised.relative_nominal_resistance_vs_prismatic, ...
    ['--' markers{familyIndex}], "Color", colors(familyIndex, :), ...
    "LineWidth", 1.0, "MarkerSize", 5.0, ...
    "MarkerFaceColor", "white", "HandleVisibility", "off");
end
yline(bottomAxes, 1, ":", "Color", [0.3 0.3 0.3], ...
  "LineWidth", 1.0, "HandleVisibility", "off");
format_axes(bottomAxes, xValues);
xlabel(bottomAxes, "Cold reduction (%)", "FontName", "Arial");
ylabel(bottomAxes, "Resistance relative to prismatic <a>", ...
  "FontName", "Arial");
legend(bottomAxes, "Location", "northoutside", "NumColumns", 3, ...
  "FontSize", 8.5, "Box", "off");
title(bottomAxes, ...
  "CRSS / area-weighted mean |m|max, normalized within each state", ...
  "FontWeight", "normal", "FontSize", 9.5);

title(layout, "Literature-CRSS-normalized slip resistance under AD tension", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold");
subtitle(layout, ...
  "CRSS: prismatic <a> 154 MPa; basal <a> 252 MPa; pyramidal <c+a> 756 MPa", ...
  "FontName", "Arial", "FontSize", 9.5);
drawnow;

figureStem = fullfile(outputRoot, ...
  "crss_normalized_slip_resistance_6state");
exportgraphics(figureHandle, figureStem + ".png", "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", "Resolution", 600, ...
  "BackgroundColor", "white");
clear cleanupFigure
end

function format_axes(axesHandle, xValues)
xlim(axesHandle, [min(xValues) - 2, max(xValues) + 2]);
xticks(axesHandle, xValues);
xticklabels(axesHandle, compose("%.2f", xValues));
grid(axesHandle, "on");
axesHandle.GridAlpha = 0.13;
axesHandle.Layer = "top";
axesHandle.FontName = "Arial";
axesHandle.FontSize = 9.2;
axesHandle.LineWidth = 0.8;
end
