function [caSummary, familySummary] = ...
  generate_ca_vs_a_preference_statistics(scanRoot, outputRoot)
%GENERATE_CA_VS_A_PREFERENCE_STATISTICS Count CRSS-normalized preferences.
%
% Per retained grain, the preferred family maximizes max(abs(m))/CRSS
% under AD uniaxial tension. Literature CRSS values are 154 MPa for
% prismatic <a>, 252 MPa for basal <a>, and 756 MPa for pyramidal <c+a>.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

assert(isfolder(scanRoot), "EBSD scan folder not found: %s", scanRoot);
assert(~isempty(which("EBSD")), ...
  "MTEX is not loaded in the current MATLAB session.");
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

contract = comprehensive_ebsd_output_contract();
catalog = comprehensive_ebsd_catalog(scanRoot);
reconstructionOptions = struct( ...
  "detection_threshold_deg", ...
  contract.parameters.primary_grain_detection_deg, ...
  "min_grain_pixels", contract.parameters.min_grain_pixels);
families = ["prismatic_a"; "basal_a"; "pyramidal_ca"];
crssMPa = [154; 252; 756];

caSummary = table();
familySummary = table();
for scanIndex = 1:height(catalog)
  catalogRow = catalog(scanIndex, :);
  fprintf("CA_VS_A sample=%s variant=%s\n", ...
    catalogRow.sample, catalogRow.variant);
  [ebsdFull, ~] = load_comprehensive_ebsd_scan(catalogRow);
  [grains, ~, ~] = reconstruct_comprehensive_grains( ...
    ebsdFull, reconstructionOptions);
  retained = grains("Ti-Hex");
  retained = retained(retained.numPixel >= ...
    reconstructionOptions.min_grain_pixels);
  assert(~isempty(retained), ...
    "No retained Ti-Hex grains for %s %s.", ...
    catalogRow.sample, catalogRow.variant);

  byGrain = compute_axial_propensity_metrics( ...
    retained.meanOrientation, double(retained.id(:)), ...
    double(area(retained)));
  familyTables = cell(numel(families), 1);
  for familyIndex = 1:numel(families)
    familyRows = byGrain.family == families(familyIndex);
    familyTables{familyIndex} = sortrows( ...
      byGrain(familyRows, {'grain_id', 'max_abs_schmid', ...
      'area_um2', 'area_weight'}), 'grain_id');
  end
  prismatic = familyTables{1};
  basal = familyTables{2};
  pyramidalCA = familyTables{3};
  assert(isequal(prismatic.grain_id, basal.grain_id) && ...
    isequal(prismatic.grain_id, pyramidalCA.grain_id));
  assert(max(abs(prismatic.area_weight - basal.area_weight)) < 1e-12 && ...
    max(abs(prismatic.area_weight - pyramidalCA.area_weight)) < 1e-12);

  schmid = [prismatic.max_abs_schmid, basal.max_abs_schmid, ...
    pyramidalCA.max_abs_schmid];
  drive = schmid ./ crssMPa';
  assert(all(isfinite(drive) & drive >= 0, "all"));
  [~, preferredIndex] = max(drive, [], 2);
  weights = prismatic.area_weight / sum(prismatic.area_weight);
  cAxis = Miller(0, 0, 0, 1, retained.meanOrientation.CS);
  cAxisAngles = c_axis_angles_to_ad(retained.meanOrientation * cAxis);
  [sortedRetainedIds, grainOrder] = sort(double(retained.id(:)));
  assert(isequal(sortedRetainedIds, prismatic.grain_id));
  cAxisAngles = cAxisAngles(grainOrder);
  [minimumCAxisAngle, closestCAxisIndex] = min(cAxisAngles);
  within2 = cAxisAngles <= 2;
  within5 = cAxisAngles <= 5;
  within10 = cAxisAngles <= 10;
  within15 = cAxisAngles <= 15;
  bestADrive = max(drive(:, 1:2), [], 2);
  caDriveRatio = drive(:, 3) ./ bestADrive;
  caOverPrismatic = drive(:, 3) > drive(:, 1);
  caOverBasal = drive(:, 3) > drive(:, 2);
  caOverBoth = caOverPrismatic & caOverBasal;
  geometricCaOverBoth = schmid(:, 3) > ...
    max(schmid(:, 1:2), [], 2);

  totalCount = height(prismatic);
  caRow = table(catalogRow.sample, catalogRow.diameter_mm, ...
    catalogRow.cold_reduction_percent, catalogRow.variant, totalCount, ...
    nnz(caOverPrismatic), 100 * mean(caOverPrismatic), ...
    100 * sum(weights(caOverPrismatic)), nnz(caOverBasal), ...
    100 * mean(caOverBasal), 100 * sum(weights(caOverBasal)), ...
    nnz(caOverBoth), 100 * mean(caOverBoth), ...
    100 * sum(weights(caOverBoth)), nnz(geometricCaOverBoth), ...
    100 * mean(geometricCaOverBoth), ...
    100 * sum(weights(geometricCaOverBoth)), ...
    weighted_quantile(caDriveRatio, weights, 0.25), ...
    weighted_quantile(caDriveRatio, weights, 0.50), ...
    weighted_quantile(caDriveRatio, weights, 0.75), ...
    max(caDriveRatio), minimumCAxisAngle, ...
    nnz(within2), 100 * mean(within2), 100 * sum(weights(within2)), ...
    nnz(within5), 100 * mean(within5), 100 * sum(weights(within5)), ...
    nnz(within10), 100 * mean(within10), 100 * sum(weights(within10)), ...
    nnz(within15), 100 * mean(within15), 100 * sum(weights(within15)), ...
    prismatic.grain_id(closestCAxisIndex), ...
    schmid(closestCAxisIndex, 1), schmid(closestCAxisIndex, 2), ...
    schmid(closestCAxisIndex, 3), caDriveRatio(closestCAxisIndex), ...
    'VariableNames', {'sample', 'diameter_mm', ...
    'cold_reduction_percent', 'variant', 'total_grain_count', ...
    'ca_over_prismatic_count', 'ca_over_prismatic_count_percent', ...
    'ca_over_prismatic_area_percent', 'ca_over_basal_count', ...
    'ca_over_basal_count_percent', 'ca_over_basal_area_percent', ...
    'ca_over_both_a_count', 'ca_over_both_a_count_percent', ...
    'ca_over_both_a_area_percent', 'geometric_ca_over_both_a_count', ...
    'geometric_ca_over_both_a_count_percent', ...
    'geometric_ca_over_both_a_area_percent', ...
    'ca_to_best_a_drive_ratio_area_q25', ...
    'ca_to_best_a_drive_ratio_area_median', ...
    'ca_to_best_a_drive_ratio_area_q75', ...
    'ca_to_best_a_drive_ratio_max', 'minimum_c_axis_ad_angle_deg', ...
    'c_axis_within_2deg_count', 'c_axis_within_2deg_count_percent', ...
    'c_axis_within_2deg_area_percent', 'c_axis_within_5deg_count', ...
    'c_axis_within_5deg_count_percent', 'c_axis_within_5deg_area_percent', ...
    'c_axis_within_10deg_count', 'c_axis_within_10deg_count_percent', ...
    'c_axis_within_10deg_area_percent', 'c_axis_within_15deg_count', ...
    'c_axis_within_15deg_count_percent', 'c_axis_within_15deg_area_percent', ...
    'closest_c_axis_grain_id', 'closest_c_axis_prismatic_max_abs_schmid', ...
    'closest_c_axis_basal_max_abs_schmid', ...
    'closest_c_axis_ca_max_abs_schmid', ...
    'closest_c_axis_ca_to_best_a_drive_ratio'});
  if isempty(caSummary)
    caSummary = caRow;
  else
    caSummary = [caSummary; caRow]; %#ok<AGROW>
  end

  for familyIndex = 1:numel(families)
    preferred = preferredIndex == familyIndex;
    familyRow = table(catalogRow.sample, catalogRow.diameter_mm, ...
      catalogRow.cold_reduction_percent, catalogRow.variant, ...
      families(familyIndex), totalCount, nnz(preferred), ...
      100 * mean(preferred), 100 * sum(weights(preferred)), ...
      'VariableNames', {'sample', 'diameter_mm', ...
      'cold_reduction_percent', 'variant', 'preferred_family', ...
      'total_grain_count', 'preferred_grain_count', ...
      'preferred_grain_count_percent', 'preferred_grain_area_percent'});
    if isempty(familySummary)
      familySummary = familyRow;
    else
      familySummary = [familySummary; familyRow]; %#ok<AGROW>
    end
  end
  clear ebsdFull grains retained byGrain familyTables
end

assert(height(caSummary) == height(catalog));
assert(height(familySummary) == height(catalog) * numel(families));
for scanIndex = 1:height(catalog)
  rows = familySummary.sample == catalog.sample(scanIndex) & ...
    familySummary.variant == catalog.variant(scanIndex);
  assert(abs(sum(familySummary.preferred_grain_count_percent(rows)) - ...
    100) < 1e-10);
  assert(abs(sum(familySummary.preferred_grain_area_percent(rows)) - ...
    100) < 1e-10);
end

caSummary = sortrows(caSummary, ...
  {'cold_reduction_percent', 'variant'});
familySummary = sortrows(familySummary, ...
  {'cold_reduction_percent', 'variant', 'preferred_family'});
writetable(caSummary, fullfile(outputRoot, ...
  "ca_vs_a_preference_summary.csv"));
writetable(familySummary, fullfile(outputRoot, ...
  "preferred_slip_family_summary.csv"));
write_parameters(outputRoot, reconstructionOptions);
plot_preference(caSummary, familySummary, outputRoot, families);
end

function result = weighted_quantile(values, weights, probability)
assert(isscalar(probability) && probability >= 0 && probability <= 1);
[sortedValues, order] = sort(values);
sortedWeights = weights(order) / sum(weights);
result = sortedValues(find(cumsum(sortedWeights) >= probability, ...
  1, "first"));
end

function write_parameters(outputRoot, reconstructionOptions)
parameter = [ ...
  "preference_metric"; "ca_preferred_condition"; ...
  "prismatic_a_crss_mpa"; "basal_a_crss_mpa"; ...
  "pyramidal_ca_crss_mpa"; "crss_source"; "source_doi"; ...
  "load_geometry"; "load_axis"; "grain_orientation"; ...
  "schmid_variant_rule"; "grain_detection_threshold_deg"; ...
  "minimum_grain_pixels"; "primary_input"; "sensitivity_input"; ...
  "excluded_family"; "interpretive_limit"];
value = [ ...
  "maximum absolute Schmid factor divided by literature CRSS"; ...
  "m_ca/756 > max(m_prismatic/154, m_basal/252)"; ...
  "154"; "252"; "756"; ...
  "Xiong et al., Acta Materialia 199 (2020) 561-577, Table 4"; ...
  "10.1016/j.actamat.2020.08.010"; ...
  "uniaxial tension"; "AD (vector3d.X)"; ...
  "mean orientation of each retained reconstructed Ti-Hex grain"; ...
  "maximum absolute value across all symmetrised variants in each family"; ...
  string(reconstructionOptions.detection_threshold_deg); ...
  string(reconstructionOptions.min_grain_pixels); ...
  "raw CTF"; "denoised CTF"; ...
  "pyramidal_a: source does not provide an independent CRSS"; ...
  "comparative screening only; a preferred grain is not direct evidence of active slip; literature CRSS is fixed across all project states"];
writetable(table(parameter, value), fullfile(outputRoot, ...
  "ca_vs_a_preference_parameters.csv"));
end

function plot_preference(caSummary, familySummary, outputRoot, families)
colors = [0.10 0.43 0.72; 0.86 0.33 0.10; 0.45 0.24 0.65];
displayNames = ["Prismatic <a>"; "Basal <a>"; ...
  "Pyramidal <c+a>"];
rawCa = sortrows(caSummary(caSummary.variant == "raw", :), ...
  "cold_reduction_percent");
denoisedCa = sortrows(caSummary(caSummary.variant == "denoised", :), ...
  "cold_reduction_percent");
x = rawCa.cold_reduction_percent;
assert(height(rawCa) == 6 && height(denoisedCa) == 6);

rawArea = zeros(height(rawCa), numel(families));
for familyIndex = 1:numel(families)
  rows = familySummary.variant == "raw" & ...
    familySummary.preferred_family == families(familyIndex);
  selected = sortrows(familySummary(rows, :), ...
    "cold_reduction_percent");
  rawArea(:, familyIndex) = selected.preferred_grain_area_percent;
end

figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 10.8 7.5], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 1, ...
  "Padding", "compact", "TileSpacing", "compact");

topAxes = nexttile(layout);
bars = bar(topAxes, x, rawArea, "stacked", "BarWidth", 0.68);
for familyIndex = 1:numel(families)
  bars(familyIndex).FaceColor = colors(familyIndex, :);
  bars(familyIndex).EdgeColor = "white";
  bars(familyIndex).LineWidth = 0.6;
  bars(familyIndex).DisplayName = displayNames(familyIndex);
end
format_axes(topAxes, x);
ylim(topAxes, [0 100]);
ylabel(topAxes, "Preferred-family grain area (%)");
legend(topAxes, "Location", "northoutside", "NumColumns", 3, ...
  "Box", "off", "FontSize", 8.5);
title(topAxes, ...
  "Raw EBSD: family with maximum |m|max / CRSS in each grain", ...
  "FontWeight", "normal", "FontSize", 9.5);

bottomAxes = nexttile(layout);
hold(bottomAxes, "on");
rawValues = [rawCa.ca_to_best_a_drive_ratio_area_median, ...
  rawCa.ca_to_best_a_drive_ratio_max];
bottomBars = bar(bottomAxes, x, rawValues, "grouped", ...
  "BarWidth", 0.68);
bottomBars(1).FaceColor = colors(1, :);
bottomBars(1).DisplayName = "Raw: area-weighted median R";
bottomBars(2).FaceColor = colors(3, :);
bottomBars(2).DisplayName = "Raw: maximum R";
plot(bottomAxes, x, ...
  denoisedCa.ca_to_best_a_drive_ratio_area_median, ...
  "o--", "Color", colors(1, :), "MarkerFaceColor", "white", ...
  "LineWidth", 1.0, "DisplayName", "Denoised: median sensitivity");
plot(bottomAxes, x, denoisedCa.ca_to_best_a_drive_ratio_max, ...
  "^--", "Color", colors(3, :), "MarkerFaceColor", "white", ...
  "LineWidth", 1.0, "DisplayName", "Denoised: maximum sensitivity");
yline(bottomAxes, 1, ":", "Color", [0.25 0.25 0.25], ...
  "LineWidth", 1.2, "DisplayName", "R = 1 preference threshold");
format_axes(bottomAxes, x);
ylim(bottomAxes, [0 1.05]);
xlabel(bottomAxes, "Cold reduction (%)");
ylabel(bottomAxes, "R = P_{<c+a>} / max(P_{prismatic},P_{basal})");
legend(bottomAxes, "Location", "northoutside", "NumColumns", 2, ...
  "Box", "off", "FontSize", 8.0);
title(bottomAxes, ...
  "No raw or denoised grain reaches R > 1 (strict <c+a> preference)", ...
  "FontWeight", "normal", "FontSize", 9.5, ...
  "Interpreter", "none");

title(layout, ...
  "CRSS-normalized slip-family preference under AD tension", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold");
subtitle(layout, ...
  "Xiong et al. Grade 4 CP-Ti CRSS: 154, 252 and 756 MPa", ...
  "FontName", "Arial", "FontSize", 9.5);
drawnow;

figureStem = fullfile(outputRoot, ...
  "ca_vs_a_preference_6state");
exportgraphics(figureHandle, figureStem + ".png", "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, figureStem + ".tif", "Resolution", 600, ...
  "BackgroundColor", "white");
clear cleanupFigure
end

function format_axes(axesHandle, xValues)
xlim(axesHandle, [min(xValues) - 2, max(xValues) + 2]);
xticks(axesHandle, xValues);
xticklabels(axesHandle, compose("%.2f", xValues));
grid(axesHandle, "on");
axesHandle.GridAlpha = 0.13;
axesHandle.Layer = "top";
axesHandle.FontName = "Arial";
axesHandle.FontSize = 9.2;
axesHandle.LineWidth = 0.8;
end
