function [distribution, summary] = generate_pyramidal_ca_schmid_distribution( ...
  scanRoot, outputRoot)
%GENERATE_PYRAMIDAL_CA_SCHMID_DISTRIBUTION Pyramidal <c+a> SF wrapper.

arguments
  scanRoot (1,1) string
  outputRoot (1,1) string
end

plotSpec = struct( ...
  "target_family", "pyramidal_ca", ...
  "display_name", "Pyramidal <c+a> slip", ...
  "file_stem", "pyramidal_ca_schmid", ...
  "system_description", ...
  "MTEX slipSystem.pyramidalCA (pyramidal <c+a> slip family)", ...
  "interpretive_limit", ...
  "geometric propensity only; no CRSS, local-stress, or slip-activity claim");
[distribution, summary] = generate_family_schmid_distribution( ...
  scanRoot, outputRoot, plotSpec);
end
