function metadata = generate_c_axis_distribution_functions( ...
  textureDir,options)
%GENERATE_C_AXIS_DISTRIBUTION_FUNCTIONS Write c-axis PDFs and maps.

arguments
  textureDir (1,1) string
  options (1,1) struct = struct()
end
assert(isfolder(textureDir));
inputPath = fullfile(textureDir,"c_axis_orientation_distribution.csv");
if isfield(options,"input_path")
  inputPath = string(options.input_path);
end
assert(isfile(inputPath));
required = ["sample","diameter_mm","cold_reduction_percent", ...
  "variant","weighting","source_id","source_weight", ...
  "c_axis_x_ad","c_axis_y_td_rd","c_axis_z_nd", ...
  "c_axis_ad_acute_deg"];

binWidths = [1 2 5];
kernelHalfwidths = [5 7.5 10];
[adTable,sphericalTable,densityModels,parameterTable,metadata] = ...
  compute_all_outputs(inputPath,required,binWidths,kernelHalfwidths);
writetable(adTable,fullfile(textureDir, ...
  "c_axis_ad_distribution_function.csv"));
writetable(sphericalTable,fullfile(textureDir, ...
  "c_axis_spherical_distribution_function.csv"));
writetable(parameterTable,fullfile(textureDir, ...
  "c_axis_distribution_parameters.csv"));
render_ad_figures(adTable,textureDir);
render_spherical_figures(sphericalTable,densityModels, ...
  textureDir,parameterTable);
end

function [adTable,sphericalTable,densityModels,parameterTable, ...
  metadata] = compute_all_outputs( ...
  inputPath,required,binWidths,kernelHalfwidths)
nMu = 36;
nPhi = 144;
auditNMu = 72;
auditNPhi = 288;
peakToleranceDeg = 3;
tieRelativeTolerance = 1e-3;
peakTieExclusionDeg = 10;
parameterParts = global_parameter_rows(binWidths,kernelHalfwidths, ...
  nMu,nPhi,auditNMu,auditNPhi,peakToleranceDeg, ...
  tieRelativeTolerance,peakTieExclusionDeg);
accumulator = struct();
accumulator.adParts = cell(0,1);
accumulator.sphericalParts = cell(0,1);
accumulator.parameterParts = parameterParts;
accumulator.densityModels = struct( ...
  "sample",{},"variant",{},"support",{}, ...
  "weighting",{},"cold_reduction_percent",{},"density_function",{}, ...
  "maximum_theta_ad_deg",{}, ...
  "maximum_phi_about_ad_deg",{},"peak_grid_stable",{});
accumulator.supportStateCount = 0;
accumulator.rawPixelCache = table();
datastore = tabularTextDatastore(char(inputPath),'TextType','string');
assert(all(ismember(required,string(datastore.VariableNames))));
datastore.SelectedVariableNames = cellstr(required);
datastore.ReadSize = 100000;
pendingState = table();
currentSample = "";
currentSampleKeys = strings(0,1);
finishedSamples = strings(0,1);
while hasdata(datastore)
  chunk = read(datastore);
  chunk.sample = string(chunk.sample);
  chunk.variant = string(chunk.variant);
  chunk.weighting = string(chunk.weighting);
  change = [true;chunk.sample(2:end)~=chunk.sample(1:end-1) | ...
    chunk.variant(2:end)~=chunk.variant(1:end-1) | ...
    chunk.weighting(2:end)~=chunk.weighting(1:end-1)];
  starts = find(change);
  stops = [starts(2:end)-1;height(chunk)];
  for segmentIndex = 1:numel(starts)
    segment = chunk(starts(segmentIndex):stops(segmentIndex),:);
    if isempty(pendingState)
      pendingState = segment;
    elseif same_full_state(pendingState,segment)
      pendingState = [pendingState;segment]; %#ok<AGROW>
    else
      [accumulator,currentSample,currentSampleKeys,finishedSamples] = ...
        consume_contiguous_state(accumulator,pendingState, ...
        currentSample,currentSampleKeys,finishedSamples, ...
        binWidths,kernelHalfwidths,nMu,nPhi,auditNMu,auditNPhi, ...
        peakToleranceDeg,tieRelativeTolerance,peakTieExclusionDeg);
      pendingState = segment;
    end
  end
end
assert(~isempty(pendingState));
[accumulator,currentSample,currentSampleKeys,finishedSamples] = ...
  consume_contiguous_state(accumulator,pendingState,currentSample, ...
  currentSampleKeys,finishedSamples,binWidths,kernelHalfwidths, ...
  nMu,nPhi,auditNMu,auditNPhi,peakToleranceDeg, ...
  tieRelativeTolerance,peakTieExclusionDeg);
validate_completed_sample(currentSample,currentSampleKeys, ...
  accumulator.rawPixelCache);
finishedSamples(end+1,1) = currentSample;
assert(numel(unique(finishedSamples)) == numel(finishedSamples));

adTable = vertcat(accumulator.adParts{:});
sphericalTable = vertcat(accumulator.sphericalParts{:});
parameterParts = accumulator.parameterParts;
densityModels = accumulator.densityModels;
pooled = sphericalTable.weighting=="pixel_weighted" & ...
  sphericalTable.kernel_halfwidth_deg==5 & ...
  ismember(sphericalTable.support,["raw_full","denoised_full"]);
colorMaximum = ceil(2*prctile(sphericalTable.mrd(pooled),99.9))/2;
assert(isfinite(colorMaximum) && colorMaximum > 1);
saturatedFraction = mean(sphericalTable.mrd(pooled) > colorMaximum);
assert(saturatedFraction <= 0.002);
for modelIndex = 1:numel(densityModels)
  modelRows = sphericalTable.sample==densityModels(modelIndex).sample & ...
    sphericalTable.variant==densityModels(modelIndex).variant & ...
    sphericalTable.support==densityModels(modelIndex).support & ...
    sphericalTable.weighting=="pixel_weighted" & ...
    sphericalTable.kernel_halfwidth_deg==5;
  stateSaturatedFraction = mean( ...
    sphericalTable.mrd(modelRows) > colorMaximum);
  parameterParts = [parameterParts;color_parameter_rows( ...
    densityModels(modelIndex),colorMaximum, ...
    stateSaturatedFraction)]; %#ok<AGROW>
end
parameterTable = vertcat(parameterParts{:});
metadata = struct();
metadata.raw_state_count = nnz(string({densityModels.variant})=="raw");
metadata.denoised_state_count = nnz( ...
  string({densityModels.variant})=="denoised");
metadata.support_state_count = accumulator.supportStateCount;
metadata.color_maximum_mrd = colorMaximum;
metadata.saturated_grid_fraction = saturatedFraction;
end

function tf = same_full_state(first,second)
tf = first.sample(1)==second.sample(1) && ...
  first.variant(1)==second.variant(1) && ...
  first.weighting(1)==second.weighting(1);
end

function [accumulator,currentSample,currentSampleKeys, ...
  finishedSamples] = consume_contiguous_state( ...
  accumulator,state,currentSample,currentSampleKeys,finishedSamples, ...
  binWidths,kernelHalfwidths,nMu,nPhi,auditNMu,auditNPhi, ...
  peakToleranceDeg,tieRelativeTolerance,peakTieExclusionDeg)
assert_unique_source_ids(state);
sample = state.sample(1);
if currentSample==""
  assert(~ismember(sample,finishedSamples));
  currentSample = sample;
elseif sample~=currentSample
  validate_completed_sample(currentSample,currentSampleKeys, ...
    accumulator.rawPixelCache);
  finishedSamples(end+1,1) = currentSample;
  assert(~ismember(sample,finishedSamples), ...
    "Each sample must occupy one contiguous set of state blocks.");
  currentSample = sample;
  currentSampleKeys = strings(0,1);
end
blockKey = state.variant(1) + "|" + state.weighting(1);
assert(~ismember(blockKey,currentSampleKeys), ...
  "Each sample/variant/weighting must occupy one contiguous block.");
currentSampleKeys(end+1,1) = blockKey;
expectedPosition = numel(currentSampleKeys);
requiredOrder = [
  "raw|pixel_weighted"
  "raw|area_weighted_grain_mean"
  "denoised|pixel_weighted"
  "denoised|area_weighted_grain_mean"
];
assert(expectedPosition <= numel(requiredOrder) && ...
  blockKey==requiredOrder(expectedPosition), ...
  "Unexpected state-block order for sample %s.",sample);

variant = state.variant(1);
assert(ismember(variant,["raw","denoised"]));
support = variant + "_full";
stateRow = make_state_row(state,support);
[stateAd,stateSpherical,stateParameters,stateModel] = ...
  process_state(state,stateRow,binWidths,kernelHalfwidths,nMu,nPhi, ...
  auditNMu,auditNPhi,peakToleranceDeg,tieRelativeTolerance, ...
  peakTieExclusionDeg);
accumulator.adParts = [accumulator.adParts;stateAd];
accumulator.sphericalParts = [ ...
  accumulator.sphericalParts;stateSpherical];
accumulator.parameterParts = [ ...
  accumulator.parameterParts;stateParameters];
if ~isempty(stateModel)
  accumulator.densityModels(end+1) = stateModel;
end
accumulator.supportStateCount = accumulator.supportStateCount+1;

if blockKey=="raw|pixel_weighted"
  assert(isempty(accumulator.rawPixelCache));
  accumulator.rawPixelCache = state;
elseif blockKey=="denoised|pixel_weighted"
  rawPixel = accumulator.rawPixelCache;
  assert(~isempty(rawPixel) && rawPixel.sample(1)==sample);
  [~,rawIndex,denoisedIndex] = intersect(rawPixel.source_id, ...
    state.source_id,'stable');
  assert(~isempty(rawIndex), ...
    "Every sample requires nonempty raw/denoised pixel overlap.");
  commonStates = {rawPixel(rawIndex,:),state(denoisedIndex,:)};
  commonSupports = ["raw_common","denoised_raw_common"];
  for commonIndex = 1:2
    commonState = commonStates{commonIndex};
    commonRow = make_state_row( ...
      commonState,commonSupports(commonIndex));
    [commonAd,commonSpherical,commonParameters,commonModel] = ...
      process_state(commonState,commonRow,binWidths, ...
      kernelHalfwidths,nMu,nPhi,auditNMu,auditNPhi, ...
      peakToleranceDeg,tieRelativeTolerance,peakTieExclusionDeg);
    assert(isempty(commonModel));
    accumulator.adParts = [accumulator.adParts;commonAd];
    accumulator.sphericalParts = [ ...
      accumulator.sphericalParts;commonSpherical];
    accumulator.parameterParts = [ ...
      accumulator.parameterParts;commonParameters];
    accumulator.supportStateCount = ...
      accumulator.supportStateCount+1;
  end
  accumulator.rawPixelCache = table();
end
end

function validate_completed_sample(sample,stateKeys,rawPixelCache)
requiredOrder = [
  "raw|pixel_weighted"
  "raw|area_weighted_grain_mean"
  "denoised|pixel_weighted"
  "denoised|area_weighted_grain_mean"
];
assert(sample~="" && isequal(stateKeys,requiredOrder), ...
  "Sample %s does not contain the four registered state blocks in order.", ...
  sample);
assert(isempty(rawPixelCache), ...
  "Raw-pixel common-support cache was not released.");
end

function stateRow = make_state_row(state,support)
assert(~isempty(state));
assert(isscalar(unique(state.diameter_mm)));
assert(isscalar(unique(state.cold_reduction_percent)));
assert(isscalar(unique(state.variant)));
assert(isscalar(unique(state.weighting)));
stateRow = table(state.sample(1),state.diameter_mm(1), ...
  state.cold_reduction_percent(1),state.variant(1),string(support), ...
  state.weighting(1),'VariableNames',cellstr([
  "sample","diameter_mm","cold_reduction_percent","variant", ...
  "support","weighting"]));
end

function [adParts,sphericalParts,parameterParts,model] = ...
  process_state(state,stateRow,binWidths,kernelHalfwidths, ...
  nMu,nPhi,auditNMu,auditNPhi,peakToleranceDeg, ...
  tieRelativeTolerance,peakTieExclusionDeg)
assert_unique_source_ids(state);
weights = double(state.source_weight);
assert(all(isfinite(weights) & weights > 0));
adParts = cell(numel(binWidths),1);
for widthIndex = 1:numel(binWidths)
  width = binWidths(widthIndex);
  [distribution,audit] = compute_c_axis_ad_distribution( ...
    state.c_axis_ad_acute_deg,weights,0:width:90);
  prefix = repeat_state_prefix(stateRow,height(distribution));
  distribution.valid_source_count = repmat( ...
    audit.valid_source_count,height(distribution),1);
  distribution.valid_source_weight = repmat( ...
    audit.valid_source_weight,height(distribution),1);
  adParts{widthIndex} = [prefix,distribution(:,[
    "bin_width_deg","bin_lower_deg","bin_upper_deg", ...
    "bin_center_deg","valid_source_count","valid_source_weight", ...
    "observed_probability","pdf_per_degree", ...
    "random_probability","mrd"])];
end

xyz = [state.c_axis_x_ad,state.c_axis_y_td_rd,state.c_axis_z_nd];
sphericalParts = cell(numel(kernelHalfwidths),1);
parameterParts = cell(0,1);
primaryAudit = struct();
primaryDistribution = table();
primaryDensity = [];
for kernelIndex = 1:numel(kernelHalfwidths)
  halfwidth = kernelHalfwidths(kernelIndex);
  [distribution,densityFunction,audit] = ...
    compute_c_axis_spherical_distribution( ...
    xyz,weights,nMu,nPhi,halfwidth);
  if ismember("gridIndex", ...
      string(distribution.Properties.VariableNames))
    distribution.Properties.VariableNames{ ...
      strcmp(distribution.Properties.VariableNames,"gridIndex")} = ...
      'grid_index';
  end
  assert(all(isfinite(distribution.mrd) & distribution.mrd >= 0));
  assert(abs(sum(distribution.cell_weight.*distribution.mrd)-1) < ...
    1e-10);
  parameterParts = [parameterParts; ...
    spherical_projection_parameter_rows( ...
    stateRow,halfwidth,audit)]; %#ok<AGROW>
  prefix = repeat_state_prefix(stateRow,height(distribution));
  kernelColumn = repmat(halfwidth,height(distribution),1);
  nMuColumn = repmat(nMu,height(distribution),1);
  nPhiColumn = repmat(nPhi,height(distribution),1);
  distribution = addvars(distribution,kernelColumn,nMuColumn, ...
    nPhiColumn,'Before',1,'NewVariableNames', ...
    cellstr(["kernel_halfwidth_deg","n_mu","n_phi"]));
  sphericalParts{kernelIndex} = [prefix,distribution(:,[
    "kernel_halfwidth_deg","n_mu","n_phi","grid_index", ...
    "theta_ad_deg","phi_about_ad_deg","cell_weight","mrd"])];
  if halfwidth == 5
    primaryAudit = registered_grid_audit(audit);
    primaryDistribution = distribution;
    primaryDensity = densityFunction;
  end
end

[auditDistribution,~,auditGridRaw] = ...
  compute_c_axis_spherical_distribution( ...
  xyz,weights,auditNMu,auditNPhi,5);
auditGrid = registered_grid_audit(auditGridRaw);
peakDistanceDeg = antipodal_peak_distance(primaryAudit,auditGrid, ...
  primaryDistribution,auditDistribution);
nearTiePrimary = has_nearly_tied_distant_peak(primaryDistribution, ...
  primaryAudit,tieRelativeTolerance,peakTieExclusionDeg);
nearTieAudit = has_nearly_tied_distant_peak(auditDistribution, ...
  auditGrid,tieRelativeTolerance,peakTieExclusionDeg);
peakStable = peakDistanceDeg <= peakToleranceDeg && ...
  ~(nearTiePrimary || nearTieAudit);
parameterParts = [parameterParts;state_parameter_rows( ...
  stateRow,peakDistanceDeg,nearTiePrimary,nearTieAudit,peakStable)];

isPrimaryModel = ismember(stateRow.support, ...
  ["raw_full","denoised_full"]) && ...
  stateRow.weighting=="pixel_weighted";
model = struct([]);
if isPrimaryModel
  model = struct();
  model.sample = stateRow.sample;
  model.variant = stateRow.variant;
  model.support = stateRow.support;
  model.weighting = stateRow.weighting;
  model.cold_reduction_percent = stateRow.cold_reduction_percent;
  model.density_function = primaryDensity;
  model.maximum_theta_ad_deg = primaryAudit.maximum_theta_ad_deg;
  model.maximum_phi_about_ad_deg = ...
    primaryAudit.maximum_phi_about_ad_deg;
  model.peak_grid_stable = peakStable;
end
end

function assert_unique_source_ids(state)
assert(~isempty(state));
assert(numel(unique(state.source_id)) == height(state), ...
  "source_id must be unique within sample/variant/weighting.");
end

function prefix = repeat_state_prefix(stateRow,rowCount)
prefix = stateRow(ones(rowCount,1),:);
end

function distanceDeg = antipodal_peak_distance( ...
  primary,audit,primaryDistribution,auditDistribution)
firstPhi = canonical_polar_phi(primary,primaryDistribution);
secondPhi = canonical_polar_phi(audit,auditDistribution);
first = peak_xyz(primary.maximum_theta_ad_deg,firstPhi);
second = peak_xyz(audit.maximum_theta_ad_deg,secondPhi);
distanceDeg = acosd(min(1,max(-1,abs(dot(first,second)))));
end

function phiDeg = canonical_polar_phi(audit,distribution)
minimumTheta = min(distribution.theta_ad_deg);
if abs(audit.maximum_theta_ad_deg-minimumTheta) < 1e-10
  phiDeg = 0;
else
  phiDeg = audit.maximum_phi_about_ad_deg;
end
end

function registered = registered_grid_audit(audit)
registered = audit;
if isfield(audit,"grid_maximum_mrd")
  registered.maximum_mrd = audit.grid_maximum_mrd;
  registered.maximum_theta_ad_deg = ...
    audit.grid_maximum_theta_ad_deg;
  registered.maximum_phi_about_ad_deg = ...
    audit.grid_maximum_phi_about_ad_deg;
end
end

function xyz = peak_xyz(thetaDeg,phiDeg)
xyz = [cosd(thetaDeg), ...
  sind(thetaDeg)*cosd(phiDeg), ...
  sind(thetaDeg)*sind(phiDeg)];
end

function nearlyTied = has_nearly_tied_distant_peak( ...
  distribution,audit,relativeTolerance,exclusionDeg)
peak = peak_xyz(audit.maximum_theta_ad_deg, ...
  audit.maximum_phi_about_ad_deg);
candidatePhi = distribution.phi_about_ad_deg;
minimumTheta = min(distribution.theta_ad_deg);
peakOnPolarRing = abs(audit.maximum_theta_ad_deg-minimumTheta) < ...
  1e-10;
if peakOnPolarRing
  samePolarRing = abs(distribution.theta_ad_deg-minimumTheta) < ...
    1e-10;
  candidatePhi(samePolarRing) = ...
    audit.maximum_phi_about_ad_deg;
end
xyz = [cosd(distribution.theta_ad_deg), ...
  sind(distribution.theta_ad_deg).*cosd(candidatePhi), ...
  sind(distribution.theta_ad_deg).*sind(candidatePhi)];
distanceDeg = acosd(min(1,max(-1,abs(xyz*peak'))));
distant = distanceDeg > exclusionDeg;
if ~any(distant)
  nearlyTied = false;
  return
end
distantMaximum = max(distribution.mrd(distant));
nearlyTied = distantMaximum >= ...
  audit.maximum_mrd*(1-relativeTolerance);
end

function rows = global_parameter_rows(binWidths,kernelHalfwidths, ...
  nMu,nPhi,auditNMu,auditNPhi,peakToleranceDeg,tieTolerance, ...
  peakTieExclusionDeg)
rows = {
  parameter_row("global","","","","","ad_bin_widths_deg", ...
    join(string(binWidths),";"),"deg","fixed", ...
    "Axial-distribution bin widths.")
  parameter_row("global","","","","","ad_primary_bin_width_deg", ...
    "2","deg","plotting", ...
    "Bin width used in the registered axial figures.")
  parameter_row("global","","","","","spherical_kernel_halfwidths_deg", ...
    join(string(kernelHalfwidths),";"),"deg","fixed", ...
    "Antipodal spherical-density kernel halfwidths.")
  parameter_row("global","","","","","spherical_primary_halfwidth_deg", ...
    "5","deg","plotting", ...
    "Kernel halfwidth retained for spherical figures.")
  parameter_row("global","","","","","spherical_kernel_family", ...
    "S2DeLaValleePoussinKernel","text","fixed", ...
    "Antipodal spherical-density kernel family.")
  parameter_row("global","","","","","spherical_n_mu", ...
    string(nMu),"count","fixed", ...
    "Equal-area primary grid divisions in cos(theta).")
  parameter_row("global","","","","","spherical_n_phi", ...
    string(nPhi),"count","fixed", ...
    "Equal-area primary grid azimuth divisions.")
  parameter_row("global","","","","","spherical_audit_n_mu", ...
    string(auditNMu),"count","audit", ...
    "Equal-area audit grid divisions in cos(theta).")
  parameter_row("global","","","","","spherical_audit_n_phi", ...
    string(auditNPhi),"count","audit", ...
    "Equal-area audit grid azimuth divisions.")
  parameter_row("global","","","","","peak_stability_tolerance_deg", ...
    string(peakToleranceDeg),"deg","audit", ...
    "Maximum primary-to-audit peak angular distance.")
  parameter_row("global","","","","","peak_tie_relative_tolerance", ...
    string(tieTolerance),"fraction","audit", ...
    "Distant peak is tied when within this fraction of the maximum.")
  parameter_row("global","","","","","peak_tie_exclusion_deg", ...
    string(peakTieExclusionDeg),"deg","audit", ...
    "Angular exclusion radius separating one kernel-scale mode from distant peaks.")
  parameter_row("global","","","","","coordinate_x", ...
    "AD","text","convention","Specimen x axis.")
  parameter_row("global","","","","","coordinate_y", ...
    "TD_RD","text","convention","Specimen y axis.")
  parameter_row("global","","","","","coordinate_z", ...
    "ND","text","convention","Specimen z axis.")
  parameter_row("global","","","","","theta_ad_definition", ...
    "acos(c_axis_x_ad)","text","convention", ...
    "Acute polar angle from positive AD on the canonical hemisphere.")
  parameter_row("global","","","","","phi_about_ad_definition", ...
    "atan2(c_axis_z_nd,c_axis_y_td_rd)","text","convention", ...
    "Azimuth around AD measured from positive TD/RD.")
  parameter_row("global","","","","","phi_positive_direction", ...
    "TD_RD_toward_ND_about_positive_AD","text","convention", ...
    "Positive azimuth rotates from positive TD/RD toward positive ND.")
  parameter_row("global","","","","","hemisphere_convention", ...
    "AD_positive_then_TD_RD_positive_then_ND_positive","text", ...
    "convention","Canonical representative of each antipodal c-axis.")
  parameter_row("global","","","","","primary_weighting", ...
    "pixel_weighted","text","plotting", ...
    "Weighting selected for all registered figures.")
  parameter_row("global","","","","","primary_supports", ...
    "raw_full;denoised_full","text","plotting", ...
    "Supports selected for registered raw and denoised figures.")
  parameter_row("global","","","","","common_supports", ...
    "raw_common;denoised_raw_common","text","comparison", ...
    "Pixel-weighted supports restricted to shared source_id values.")
  parameter_row("global","","","","","color_percentile", ...
    "99.9","percentile","colour", ...
    "Pooled primary-grid MRD percentile used for the colour ceiling.")
  parameter_row("global","","","","","color_rounding_increment_mrd", ...
    "0.5","mrd","colour", ...
    "Colour ceiling is rounded upward to this MRD increment.")
  parameter_row("global","","","","", ...
    "color_saturation_limit_fraction","0.002","fraction","colour", ...
    "Maximum pooled primary-grid fraction above the shared ceiling.")
  parameter_row("global","","","","","color_range_minimum_mrd", ...
    "0","mrd","colour","Common lower colour limit for all panels.")
  parameter_row("global","","","","","color_contour_level_count", ...
    "11","count","colour", ...
    "Number of common linearly spaced spherical contour levels.")
  parameter_row("global","","","","","color_pool_definition", ...
    "pixel_weighted;kernel_5_deg;raw_full_and_denoised_full", ...
    "text","colour", ...
    "Rows pooled to determine the registered colour ceiling.")
  parameter_row("global","","","","", ...
    "nonnegative_projection_rule", ...
    "clip_negative_grid_MRD_to_zero_then_cell_weight_renormalize", ...
    "text","audit", ...
    "Helper projection applied after raw equal-area-grid normalization.")
  parameter_row("global","","","","", ...
    "maximum_negative_mass","0.01","fraction","audit", ...
    "Maximum allowed cell-weighted raw negative MRD mass.")
  };
end

function rows = spherical_projection_parameter_rows( ...
  stateRow,halfwidth,audit)
kernelToken = strrep(string(halfwidth),".","_");
suffix = "_kernel_" + kernelToken + "_deg";
rows = {
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting,"raw_minimum_mrd"+suffix, ...
    string(audit.raw_minimum_mrd),"mrd","audit", ...
    "Minimum grid MRD before nonnegative projection.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting,"raw_negative_mass"+suffix, ...
    string(audit.raw_negative_mass),"fraction","audit", ...
    "Cell-weighted raw negative MRD mass before projection.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting, ...
    "raw_negative_cell_fraction"+suffix, ...
    string(audit.raw_negative_cell_fraction),"fraction","audit", ...
    "Fraction of equal-area grid cells with raw negative MRD.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting, ...
    "maximum_negative_mass"+suffix, ...
    string(audit.maximum_negative_mass),"fraction","audit", ...
    "Maximum allowed cell-weighted raw negative MRD mass.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting, ...
    "nonnegative_projection_scale"+suffix, ...
    string(audit.nonnegative_projection_scale),"factor","audit", ...
    "Scale restoring unit cell-weighted mean after clipping.")
  };
end

function rows = state_parameter_rows( ...
  stateRow,distanceDeg,nearTiePrimary,nearTieAudit,isStable)
rows = {
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting,"peak_grid_distance_deg", ...
    string(distanceDeg),"deg","audit", ...
    "Antipodal angular distance between primary- and audit-grid maxima.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting,"peak_near_tie_primary", ...
    string(double(nearTiePrimary)),"logical","audit", ...
    "One when the primary grid has a distant nearly tied peak.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting,"peak_near_tie_audit", ...
    string(double(nearTieAudit)),"logical","audit", ...
    "One when the audit grid has a distant nearly tied peak.")
  parameter_row("state",stateRow.sample,stateRow.variant, ...
    stateRow.support,stateRow.weighting,"peak_grid_stable", ...
    string(double(isStable)),"logical","audit", ...
    "One when grid distance is within tolerance and neither grid has a distant tied peak.")
  };
end

function rows = color_parameter_rows(model,colorMaximum,saturatedFraction)
rows = {
  parameter_row("state",model.sample,model.variant,model.support, ...
    model.weighting,"color_maximum_mrd",string(colorMaximum), ...
    "mrd","colour","Shared ceiling for all registered spherical panels.")
  parameter_row("state",model.sample,model.variant,model.support, ...
    model.weighting,"saturated_grid_fraction", ...
    string(saturatedFraction),"fraction","colour", ...
    "Fraction of this state's primary grid above the shared ceiling.")
  };
end

function row = parameter_row(scope,sample,variant,support,weighting, ...
  parameter,value,unit,role,definition)
row = table(string(scope),string(sample),string(variant), ...
  string(support),string(weighting),string(parameter),string(value), ...
  string(unit),string(role),string(definition), ...
  'VariableNames',cellstr(["scope","sample","variant","support", ...
  "weighting","parameter","value","unit","role","definition"]));
end

function render_ad_figures(adTable,textureDir)
primary = adTable.weighting=="pixel_weighted" & ...
  adTable.bin_width_deg==2 & ...
  ismember(adTable.support,["raw_full","denoised_full"]);
pdfMaximum = max(adTable.pdf_per_degree(primary));
mrdMaximum = max(adTable.mrd(primary));
assert(isfinite(pdfMaximum) && pdfMaximum > 0);
assert(isfinite(mrdMaximum) && mrdMaximum > 0);
yLimits = struct("pdf",[0 1.05*pdfMaximum], ...
  "mrd",[0 max(1.05,1.05*mrdMaximum)]);
render_one_ad_figure(adTable(primary & ...
  adTable.support=="raw_full",:),"raw", ...
  fullfile(textureDir,"c_axis_ad_distribution_raw.png"),yLimits);
render_one_ad_figure(adTable(primary & ...
  adTable.support=="denoised_full",:),"denoised", ...
  fullfile(textureDir,"c_axis_ad_distribution_denoised.png"),yLimits);
end

function render_one_ad_figure(rows,variantName,outputPath,yLimits)
samples = unique(rows(:,["sample","cold_reduction_percent"]),"rows");
[~,order] = sort(samples.cold_reduction_percent);
samples = samples(order,:);
assert(height(samples) == 6);
colors = lines(6);
lineStyles = ["-","--",":","-.","-","--"];
figureHandle = figure("Visible","off","Color","white", ...
  "Position",[80 80 1300 1050]);
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle,2,1,"Padding","compact", ...
  "TileSpacing","compact");
pdfAxes = nexttile(layout);
mrdAxes = nexttile(layout);
hold(pdfAxes,"on");
hold(mrdAxes,"on");
for sampleIndex = 1:height(samples)
  selected = rows.sample==samples.sample(sampleIndex);
  sampleRows = sortrows(rows(selected,:),"bin_center_deg");
  label = sprintf("%s (%.2f%%)",samples.sample(sampleIndex), ...
    samples.cold_reduction_percent(sampleIndex));
  plot(pdfAxes,sampleRows.bin_center_deg,sampleRows.pdf_per_degree, ...
    "Color",colors(sampleIndex,:),"LineStyle", ...
    lineStyles(sampleIndex),"LineWidth",1.6,"DisplayName",label);
  plot(mrdAxes,sampleRows.bin_center_deg,sampleRows.mrd, ...
    "Color",colors(sampleIndex,:),"LineStyle", ...
    lineStyles(sampleIndex),"LineWidth",1.6,"DisplayName",label);
end
yline(mrdAxes,1,"-","Random axes (MRD = 1)", ...
  "Color",[0.35 0.35 0.35],"LineWidth",1.0, ...
  "HandleVisibility","off");
xlim(pdfAxes,[0 90]);
xlim(mrdAxes,[0 90]);
ylim(pdfAxes,yLimits.pdf);
ylim(mrdAxes,yLimits.mrd);
ylabel(pdfAxes,"Probability density (degree^{-1})");
ylabel(mrdAxes,"MRD");
xlabel(mrdAxes,"Acute c-axis angle to AD (deg)");
grid(pdfAxes,"on");
grid(mrdAxes,"on");
legend(pdfAxes,"Location","eastoutside","Interpreter","none");
title(layout,sprintf( ...
  "c-axis distribution relative to AD | %s | pixel_weighted | %s_full | bin = 2 deg", ...
  variantName,variantName),"Interpreter","none");
exportgraphics(figureHandle,char(outputPath),"Resolution",300, ...
  "BackgroundColor","white");
clear cleanupFigure
end

function render_spherical_figures(sphericalTable,densityModels, ...
  textureDir,parameterTable)
colorRows = parameterTable.parameter=="color_maximum_mrd";
colorMaximums = double(parameterTable.value(colorRows));
assert(~isempty(colorMaximums) && ...
  max(abs(colorMaximums-colorMaximums(1))) < 1e-12);
colorMaximum = colorMaximums(1);
render_one_spherical_figure(densityModels,"raw",colorMaximum, ...
  fullfile(textureDir,"c_axis_spherical_distribution_raw.png"));
render_one_spherical_figure(densityModels,"denoised",colorMaximum, ...
  fullfile(textureDir,"c_axis_spherical_distribution_denoised.png"));
pooled = sphericalTable.weighting=="pixel_weighted" & ...
  sphericalTable.kernel_halfwidth_deg==5 & ...
  ismember(sphericalTable.support,["raw_full","denoised_full"]);
assert(mean(sphericalTable.mrd(pooled) > colorMaximum) <= 0.002);
end

function render_one_spherical_figure(models,variantName, ...
  colorMaximum,outputPath)
selected = string({models.variant})'==variantName;
models = models(selected);
reductions = zeros(numel(models),1);
for modelIndex = 1:numel(models)
  reductions(modelIndex) = models(modelIndex).cold_reduction_percent;
end
[~,order] = sort(reductions);
models = models(order);
reductions = reductions(order);
assert(numel(models) == 6);

figureHandle = figure("Visible","off","Color","white", ...
  "Position",[40 40 1800 1150]);
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle,2,3,"Padding","compact", ...
  "TileSpacing","compact");
contourLevels = linspace(0,colorMaximum,11);
lastAxes = [];
for modelIndex = 1:numel(models)
  axesHandle = nexttile(layout);
  lastAxes = axesHandle;
  plot(models(modelIndex).density_function, ...
    'antipodal','earea','contourf','silent', ...
    'parent',axesHandle,'colorRange',[0 colorMaximum], ...
    'contours',contourLevels);
  title(axesHandle,sprintf("%s | %.2f%%", ...
    models(modelIndex).sample,reductions(modelIndex)), ...
    "Interpreter","none","FontWeight","normal");
  annotate_specimen_axes(axesHandle);
  if models(modelIndex).peak_grid_stable
    peak = peak_xyz(models(modelIndex).maximum_theta_ad_deg, ...
      models(modelIndex).maximum_phi_about_ad_deg);
    hold(axesHandle,"on");
    plot(vector3d(peak(1),peak(2),peak(3)), ...
      'Marker','o','MarkerSize',4,'MarkerFaceColor', ...
      [0.25 0.25 0.25],'MarkerEdgeColor',[1 1 1], ...
      'LineStyle','none','parent',axesHandle,'silent');
  end
end
colorbarHandle = colorbar(lastAxes,"eastoutside");
colorbarHandle.Label.String = "MRD";
title(layout,sprintf( ...
  "Antipodal c-axis spherical distribution | %s | pixel_weighted | %s_full | kernel = 5 deg | phi+: TD/RD to ND about +AD", ...
  variantName,variantName), ...
  "Interpreter","none");
exportgraphics(figureHandle,char(outputPath),"Resolution",300, ...
  "BackgroundColor","white");
clear cleanupFigure
end

function annotate_specimen_axes(axesHandle)
common = {'Units','normalized','BackgroundColor','white', ...
  'Margin',1,'FontSize',8,'Interpreter','none'};
text(axesHandle,0.97,0.50,'AD',common{:}, ...
  'HorizontalAlignment','right','VerticalAlignment','middle');
text(axesHandle,0.50,0.97,'TD/RD',common{:}, ...
  'HorizontalAlignment','center','VerticalAlignment','top');
text(axesHandle,0.50,0.50,'ND',common{:}, ...
  'HorizontalAlignment','center','VerticalAlignment','middle');
end
