function [thetaDeg, segLengthUm, audit, masks] = ...
  partition_ti_hex_boundary_segments(innerThetaDeg, innerLengthUm, ...
  outerThetaDeg, outerLengthUm, detectionFloorDeg, classificationAngleDeg)
%PARTITION_TI_HEX_BOUNDARY_SEGMENTS Apply source-and-angle eligibility.

innerThetaDeg = double(innerThetaDeg(:));
innerLengthUm = double(innerLengthUm(:));
outerThetaDeg = double(outerThetaDeg(:));
outerLengthUm = double(outerLengthUm(:));
angleToleranceDeg = 1e-8;
maximumHcpAngleDeg = 94;

assert(isscalar(detectionFloorDeg) && isfinite(detectionFloorDeg) && ...
  detectionFloorDeg >= 0, "Detection floor must be nonnegative and finite.");
assert(isscalar(classificationAngleDeg) && ...
  isfinite(classificationAngleDeg) && ...
  classificationAngleDeg > detectionFloorDeg, ...
  "Classification angle must exceed the detection floor.");
assert(numel(innerThetaDeg) == numel(innerLengthUm), ...
  "Inner angle and length vectors must have equal length.");
assert(numel(outerThetaDeg) == numel(outerLengthUm), ...
  "Outer angle and length vectors must have equal length.");
assert(all(isfinite(innerThetaDeg)) && ...
  all(isfinite(innerLengthUm) & innerLengthUm > 0), ...
  "Inner Ti-Hex/Ti-Hex segments must have finite angles and positive lengths.");
assert(all(isfinite(outerThetaDeg)) && ...
  all(isfinite(outerLengthUm) & outerLengthUm > 0), ...
  "Outer Ti-Hex/Ti-Hex segments must have finite angles and positive lengths.");
assert(all(innerThetaDeg >= detectionFloorDeg - angleToleranceDeg & ...
  innerThetaDeg <= maximumHcpAngleDeg + angleToleranceDeg), ...
  "Inner Ti-Hex/Ti-Hex angles fall outside the reconstructed range.");
assert(all(outerThetaDeg >= detectionFloorDeg - angleToleranceDeg & ...
  outerThetaDeg <= maximumHcpAngleDeg + angleToleranceDeg), ...
  "Outer Ti-Hex/Ti-Hex angles fall outside the reconstructed range.");

masks.inner_lagb = innerThetaDeg < classificationAngleDeg;
masks.inner_high_angle = innerThetaDeg >= classificationAngleDeg;
masks.outer_low_angle = outerThetaDeg < classificationAngleDeg;
masks.outer_hagb = outerThetaDeg >= classificationAngleDeg;
assert(all(xor(masks.inner_lagb, masks.inner_high_angle)), ...
  "Inner source-by-angle masks are not exhaustive and exclusive.");
assert(all(xor(masks.outer_low_angle, masks.outer_hagb)), ...
  "Outer source-by-angle masks are not exhaustive and exclusive.");

thetaDeg = [innerThetaDeg(masks.inner_lagb); ...
  outerThetaDeg(masks.outer_hagb)];
segLengthUm = [innerLengthUm(masks.inner_lagb); ...
  outerLengthUm(masks.outer_hagb)];

audit.inner_ti_ti_segment_count = numel(innerThetaDeg);
audit.inner_ti_ti_boundary_length_um = sum(innerLengthUm);
audit.outer_ti_ti_segment_count = numel(outerThetaDeg);
audit.outer_ti_ti_boundary_length_um = sum(outerLengthUm);
audit.audit_inner_lagb_segment_count = nnz(masks.inner_lagb);
audit.audit_inner_lagb_length_um = sum(innerLengthUm(masks.inner_lagb));
audit.audit_inner_high_angle_segment_count = ...
  nnz(masks.inner_high_angle);
audit.audit_inner_high_angle_length_um = ...
  sum(innerLengthUm(masks.inner_high_angle));
audit.audit_outer_low_angle_segment_count = nnz(masks.outer_low_angle);
audit.audit_outer_low_angle_length_um = ...
  sum(outerLengthUm(masks.outer_low_angle));
audit.audit_outer_hagb_segment_count = nnz(masks.outer_hagb);
audit.audit_outer_hagb_length_um = sum(outerLengthUm(masks.outer_hagb));
audit.source_network_segment_count = ...
  audit.inner_ti_ti_segment_count + audit.outer_ti_ti_segment_count;
audit.source_network_boundary_length_um = ...
  audit.inner_ti_ti_boundary_length_um + ...
  audit.outer_ti_ti_boundary_length_um;
audit.excluded_cross_class_segment_count = ...
  audit.audit_inner_high_angle_segment_count + ...
  audit.audit_outer_low_angle_segment_count;
audit.excluded_cross_class_boundary_length_um = ...
  audit.audit_inner_high_angle_length_um + ...
  audit.audit_outer_low_angle_length_um;
audit.eligible_segment_count = numel(thetaDeg);
audit.total_eligible_boundary_length_um = sum(segLengthUm);

assert(audit.source_network_segment_count == ...
  audit.eligible_segment_count + audit.excluded_cross_class_segment_count);
assert(abs(audit.source_network_boundary_length_um - ...
  audit.total_eligible_boundary_length_um - ...
  audit.excluded_cross_class_boundary_length_um) < 1e-8);
end
