function outputs = plot_key_method_prismatic_pyramidal_comparison( ...
  inputCsv, outputRoot)
%PLOT_KEY_METHOD_PRISMATIC_PYRAMIDAL_COMPARISON Plot saved summary table.

arguments
  inputCsv (1,1) string
  outputRoot (1,1) string
end

assert(isfile(inputCsv), "Comparison table not found: %s", inputCsv);
if ~isfolder(outputRoot)
  mkdir(outputRoot);
end

data = readtable(inputCsv, "TextType", "string");
assert(height(data) == 8, "Expected eight comparison methods.");
assert(all(data.data_variant == "denoised"), ...
  "The saved comparison table must contain denoised results only.");

locationMethods = [ ...
  "count_weighted_mean"; ...
  "area_weighted_mean"; ...
  "area_weighted_median"; ...
  "area_weighted_trimmed_mean_q05_q95"; ...
  "area_weighted_q90"];
locationLabels = { ...
  "Count-weighted mean"; ...
  "Area-weighted mean"; ...
  "Area-weighted median"; ...
  "Area-weighted 5%-95% trimmed mean"; ...
  "Area-weighted 90th percentile"};

tailMethods = [ ...
  "area_fraction_m_ge_0_44_percent"; ...
  "area_fraction_m_ge_0_46_percent"; ...
  "area_fraction_m_ge_0_48_percent"];
tailLabels = { ...
  "m >= 0.44"; ...
  "m >= 0.46"; ...
  "m >= 0.48"};

locationRows = find_rows(data, locationMethods);
tailRows = find_rows(data, tailMethods);
locationValues = [ ...
  locationRows.prismatic_a_relative_change_percent, ...
  locationRows.pyramidal_ca_relative_change_percent];
tailValues = [tailRows.prismatic_a_change, ...
  tailRows.pyramidal_ca_change];

colors = [0.10 0.43 0.72; 0.45 0.24 0.65];
figureHandle = figure("Visible", "off", "Color", "white", ...
  "Units", "inches", "Position", [0.5 0.5 10.5 7.3], ...
  "PaperPositionMode", "auto");
cleanupFigure = onCleanup(@() close(figureHandle));
layout = tiledlayout(figureHandle, 2, 1, ...
  "Padding", "compact", "TileSpacing", "compact");

axesLocation = nexttile(layout);
barsLocation = barh(axesLocation, locationValues, "grouped");
style_bars(barsLocation, colors);
format_comparison_axes(axesLocation, locationLabels, ...
  "Relative change from 7d to 5d (%)");
title(axesLocation, ...
  "(a) Distribution-location statistics", "FontWeight", "normal");
legend(axesLocation, {"Prismatic <a>", "Pyramidal <c+a>"}, ...
  "Location", "southoutside", "Orientation", "horizontal", ...
  "Box", "off");

axesTail = nexttile(layout);
barsTail = barh(axesTail, tailValues, "grouped");
style_bars(barsTail, colors);
format_comparison_axes(axesTail, tailLabels, ...
  "Change in high-Schmid grain area (percentage points)");
title(axesTail, ...
  "(b) Fixed-threshold high-tail fractions", ...
  "FontWeight", "normal");

title(layout, ...
  "Initial-to-final Schmid-factor statistical comparison", ...
  "FontName", "Arial", "FontSize", 13, "FontWeight", "bold");
subtitle(layout, ...
  "Denoised EBSD; 7d (0%) to 5d (48.98% cold reduction)", ...
  "FontName", "Arial", "FontSize", 9.5);
drawnow;

figureStem = fullfile(outputRoot, ...
  "key_method_prismatic_pyramidal_comparison");
pngPath = figureStem + ".png";
tifPath = figureStem + ".tif";
exportgraphics(figureHandle, pngPath, "Resolution", 600, ...
  "BackgroundColor", "white");
exportgraphics(figureHandle, tifPath, "Resolution", 600, ...
  "BackgroundColor", "white");

outputs = struct("png", pngPath, "tif", tifPath);
clear cleanupFigure
end

function rows = find_rows(data, methods)
indices = zeros(numel(methods), 1);
for methodIndex = 1:numel(methods)
  matched = find(data.method == methods(methodIndex));
  assert(numel(matched) == 1, ...
    "Expected one row for method %s.", methods(methodIndex));
  indices(methodIndex) = matched;
end
rows = data(indices, :);
end

function style_bars(bars, colors)
for seriesIndex = 1:numel(bars)
  bars(seriesIndex).FaceColor = colors(seriesIndex, :);
  bars(seriesIndex).EdgeColor = "none";
  bars(seriesIndex).BarWidth = 0.78;
end
end

function format_comparison_axes(axesHandle, labels, xLabelText)
axesHandle.YDir = "reverse";
yticks(axesHandle, 1:numel(labels));
yticklabels(axesHandle, labels);
xline(axesHandle, 0, "-", "Color", [0.22 0.22 0.22], ...
  "LineWidth", 0.9, "HandleVisibility", "off");
grid(axesHandle, "on");
axesHandle.GridAlpha = 0.13;
axesHandle.YGrid = "off";
axesHandle.Layer = "top";
axesHandle.FontName = "Arial";
axesHandle.FontSize = 9.5;
axesHandle.LineWidth = 0.8;
xlabel(axesHandle, xLabelText);
end
